---
title: "Report Creation use repeat feature"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r }

library(htmltools)
library(flextable)
ft <- flextable(head(iris))
tab_list <- list()
for(i in 1:3){
  tab_list[[i]] <- tagList(
    tags$h5(paste0("iteration ", i)),
    htmltools_value(ft)
  )
}
tagList(tab_list)

```

```{r}

# pagedown::chrome_print("pbi_model_document.html", "html_paged_test.pdf")
# 
# 
# 
# trimws(paste(sample(c(letters, rep(' ', 10)), 30, TRUE), collapse = ''))

text = function(len) {
  trimws(paste(sample(c(letters, rep(' ', 10)), len, TRUE), collapse = ''))
}


xx <- unlist(lapply(seq_len(10), function(i) {
  if (i %% 5 == 0) return(paste('#', text(sample(10:30, 1))))
  if (i %% 2 == 0) return(paste('##', text(sample(10:30, 1))))
  type = sample(1:3, 1, prob = c(.9, .03, .07))
  type
  # switch(type, text(sample(50:300, 1)), figure(), table())
})
)

yy = cat(xx, sep = '\n\n')


# tab_list[[1]] <- tagList(tags$h3("test"),
#                           tags$pre(paste0("    ", "test this is a paragraph")))
# 
# tagList(tab_list)

```

`r yy`
