{
  "name": "211ed541-4ecb-4f0b-b1a1-7058c5d44fc7",
  "compatibilityLevel": 1465,
  "model": {
    "culture": "en-US",
    "dataSources": [
      {
        "name": "b6e349ca-e473-4ca8-b1fc-fe221d96b0a9",
        "connectionString": "provider=Microsoft.PowerBI.OleDb;global pipe=0ce8b574-8012-4dbf-84a4-91b6acfab26f;mashup=\"UEsDBBQAAgAIAFd/0FAiESSVqgAAAPoAAAASABwAQ29uZmlnL1BhY2thZ2UueG1s\";location=AUX_Text_Expression",
        "impersonationMode": "impersonateCurrentUser"
      },
      {
        "name": "9bad31b5-83d3-45fa-84b3-92285a6ec522",
        "connectionString": "provider=Microsoft.PowerBI.OleDb;global pipe=0ce8b574-8012-4dbf-84a4-91b6acfab26f;mashup=UEsDBBQAAgAIAFd/0FAiESSVqgAAAPoAAAASABwAQ29uZmlnL1BhY2thZ;location=AUX_Segment",
        "impersonationMode": "impersonateCurrentUser"
      },
      {
        "name": "6c452806-c5b7-464a-8b10-31238986b448",
        "connectionString": "provider=Microsoft.PowerBI.OleDb;global pipe=0ce8b574-8012-4dbf-84a4-91b6acfab26f;mashup=\"UEsDBBQAAgAIAFd/0FAiESSVqgAAAPoAAAASABwAQ29uZmlnL1BhY2thZ2UueG1s\";location=AUX_Top_Selection_Geo",
        "impersonationMode": "impersonateCurrentUser"
      },
      {
        "name": "23f63ec5-51ef-4e6a-bc65-a7ddf500242b",
        "connectionString": "provider=Microsoft.PowerBI.OleDb;global pipe=0ce8b574-8012-4dbf-84a4-91b6acfab26f;mashup=UEsDBBQAAgAIAFd/0FAiESSVqgAAAPoAAAASABwAQ29uZmlnL1BhY2thZ;location=AUX_Top_Selection_Prod",
        "impersonationMode": "impersonateCurrentUser"
      },
      {
        "name": "04622af5-18a6-445d-ba0e-d2325f9932ca",
        "connectionString": "provider=Microsoft.PowerBI.OleDb;global pipe=0ce8b574-8012-4dbf-84a4-91b6acfab26f;mashup=\"UEsDBBQAAgAIAFd/0FAiESSVqgAAAPoAAAASABwAQ29uZmlnL1BhY2thZ2UueG1s\";location=Dim_Banner_Type",
        "impersonationMode": "impersonateCurrentUser"
      },
      {
        "name": "14a284e2-459f-4fcb-8d9d-51aaf37fdb0c",
        "connectionString": "provider=Microsoft.PowerBI.OleDb;global pipe=0ce8b574-8012-4dbf-84a4-91b6acfab26f;mashup=\"UEsDBBQAAgAIAFd/0FAiESSVqgAAAPoAAAASABwAQ29uZmlnL1BhY2thZ2UueG1s\";location=Client",
        "impersonationMode": "impersonateCurrentUser"
      },
      {
        "name": "32ab8cd3-e577-442b-9f0f-a18c0cb0505a",
        "connectionString": "provider=Microsoft.PowerBI.OleDb;global pipe=0ce8b574-8012-4dbf-84a4-91b6acfab26f;mashup=UEsDBBQAAgAIAFd/0FAiESSVqgAAAPoAAAASABwAQ29uZmlnL1BhY2thZ;location=Dim_Period",
        "impersonationMode": "impersonateCurrentUser"
      },
      {
        "name": "384c05f1-f56f-4e84-8299-5341c1a2fb5a",
        "connectionString": "provider=Microsoft.PowerBI.OleDb;global pipe=0ce8b574-8012-4dbf-84a4-91b6acfab26f;mashup=UEsDBBQAAgAIAFd/0FAiESSVqgAAAPoAAAASABwAQ29uZmlnL1BhY2thZ;location=Dim_Period_Base",
        "impersonationMode": "impersonateCurrentUser"
      },
      {
        "name": "2c89ead8-0a1c-4420-9c2e-55166db2dba6",
        "connectionString": "provider=Microsoft.PowerBI.OleDb;global pipe=0ce8b574-8012-4dbf-84a4-91b6acfab26f;mashup=\"UEsDBBQAAgAIAFd/0FAiESSVqgAAAPoAAAASABwAQ29uZmlnL1BhY2thZ2UueG1s\";location=Dim_Product_General",
        "impersonationMode": "impersonateCurrentUser"
      },
      {
        "name": "f5bd4fb7-feb9-45cd-b2f4-8aa6dc5dca3c",
        "connectionString": "provider=Microsoft.PowerBI.OleDb;global pipe=0ce8b574-8012-4dbf-84a4-91b6acfab26f;mashup=\"UEsDBBQAAgAIAFd/0FAiESSVqgAAAPoAAAASABwAQ29uZmlnL1BhY2thZ2UueG1s\";location=Fact_Outlet_Category_Sales",
        "impersonationMode": "impersonateCurrentUser"
      },
      {
        "name": "25dc2cb6-00b3-43ba-b06e-a63fab08d48a",
        "connectionString": "provider=Microsoft.PowerBI.OleDb;global pipe=0ce8b574-8012-4dbf-84a4-91b6acfab26f;mashup=\"UEsDBBQAAgAIAFd/0FAiESSVqgAAAPoAAAASABwAQ29uZmlnL1BhY2thZ2UueG1s\";location=Fact_SKU_State_Sales",
        "impersonationMode": "impersonateCurrentUser"
      },
      {
        "name": "a7ebfbe3-89fd-41a9-b8e2-50eafb23e8db",
        "connectionString": "provider=Microsoft.PowerBI.OleDb;global pipe=0ce8b574-8012-4dbf-84a4-91b6acfab26f;mashup=\"UEsDBBQAAgAIAFd/0FAiESSVqgAAAPoAAAASABwAQ29uZmlnL1BhY2thZ2UueG1s\";location=Dim_Market_Type",
        "impersonationMode": "impersonateCurrentUser"
      },
      {
        "name": "eecee072-1a97-49ff-b70a-3bb40031337e",
        "connectionString": "provider=Microsoft.PowerBI.OleDb;global pipe=0ce8b574-8012-4dbf-84a4-91b6acfab26f;mashup=\"UEsDBBQAAgAIAFd/0FAiESSVqgAAAPoAAAASABwAQ29uZmlnL1BhY2thZ2UueG1s\";location=Dim_Measure_Type",
        "impersonationMode": "impersonateCurrentUser"
      },
      {
        "name": "f01f39a5-af11-4eae-8334-04f2359b1600",
        "connectionString": "provider=Microsoft.PowerBI.OleDb;global pipe=0ce8b574-8012-4dbf-84a4-91b6acfab26f;mashup=\"UEsDBBQAAgAIAFd/0FAiESSVqgAAAPoAAAASABwAQ29uZmlnL1BhY2thZ2UueG1s\";location=Dim_Outlet",
        "impersonationMode": "impersonateCurrentUser"
      },
      {
        "name": "d3384ea3-0a95-4841-8d87-adfe6d53cffd",
        "connectionString": "provider=Microsoft.PowerBI.OleDb;global pipe=0ce8b574-8012-4dbf-84a4-91b6acfab26f;mashup=UEsDBBQAAgAIAFd/0FAiESSVqgAAAPoAAAASABwAQ29uZmlnL1BhY2thZ;location=Dim_Product_Ownership",
        "impersonationMode": "impersonateCurrentUser"
      },
      {
        "name": "57ce0950-4485-4e53-8bdd-071427329adb",
        "connectionString": "provider=Microsoft.PowerBI.OleDb;global pipe=0ce8b574-8012-4dbf-84a4-91b6acfab26f;mashup=\"UEsDBBQAAgAIAFd/0FAiESSVqgAAAPoAAAASABwAQ29uZmlnL1BhY2thZ2UueG1s\";location=Dim_State",
        "impersonationMode": "impersonateCurrentUser"
      },
      {
        "name": "9a00f900-5de8-4eb8-9cfb-2d9907ecac10",
        "connectionString": "provider=Microsoft.PowerBI.OleDb;global pipe=0ce8b574-8012-4dbf-84a4-91b6acfab26f;mashup=\"UEsDBBQAAgAIAFd/0FAiESSVqgAAAPoAAAASABwAQ29uZmlnL1BhY2thZ2UueG1s\";location=Fact_Sales_Metrics_SKU",
        "impersonationMode": "impersonateCurrentUser"
      },
      {
        "name": "acd0870d-7a81-4de3-8913-52efde558c05",
        "connectionString": "provider=Microsoft.PowerBI.OleDb;global pipe=0ce8b574-8012-4dbf-84a4-91b6acfab26f;mashup=UEsDBBQAAgAIAFd/0FAiESSVqgAAAPoAAAASABwAQ29uZmlnL1BhY2thZ;location=Dim_Product_Client_Hierarchy",
        "impersonationMode": "impersonateCurrentUser"
      },
      {
        "name": "b8df250c-b1c5-499c-9f69-ef10439446c7",
        "connectionString": "provider=Microsoft.PowerBI.OleDb;global pipe=0ce8b574-8012-4dbf-84a4-91b6acfab26f;mashup=\"UEsDBBQAAgAIAFd/0FAiESSVqgAAAPoAAAASABwAQ29uZmlnL1BhY2thZ2UueG1s\";location=Dim_Hierarchy_Name_Product",
        "impersonationMode": "impersonateCurrentUser"
      },
      {
        "name": "b736716f-b6ee-48c5-8351-489cc0ce7490",
        "connectionString": "provider=Microsoft.PowerBI.OleDb;global pipe=0ce8b574-8012-4dbf-84a4-91b6acfab26f;mashup=\"UEsDBBQAAgAIAFd/0FAiESSVqgAAAPoAAAASABwAQ29uZmlnL1BhY2thZ2UueG1s\";location=Dim_Hierarchy_Level_Name_Product",
        "impersonationMode": "impersonateCurrentUser"
      },
      {
        "name": "b4434604-f94f-4808-bc51-8edf0b4a6484",
        "connectionString": "provider=Microsoft.PowerBI.OleDb;global pipe=0ce8b574-8012-4dbf-84a4-91b6acfab26f;mashup=\"UEsDBBQAAgAIAFd/0FAiESSVqgAAAPoAAAASABwAQ29uZmlnL1BhY2thZ2UueG1s\";location=Dim_Product_Coding_Source",
        "impersonationMode": "impersonateCurrentUser"
      },
      {
        "name": "69a12b0a-3020-45a8-b5bb-16baa3ea4a1e",
        "connectionString": "provider=Microsoft.PowerBI.OleDb;global pipe=0ce8b574-8012-4dbf-84a4-91b6acfab26f;mashup=UEsDBBQAAgAIAFd/0FAiESSVqgAAAPoAAAASABwAQ29uZmlnL1BhY2thZ;location=Dim_Product_Client",
        "impersonationMode": "impersonateCurrentUser"
      },
      {
        "name": "62c66131-25d4-482d-b62f-75a1b0d4b978",
        "connectionString": "provider=Microsoft.PowerBI.OleDb;global pipe=0ce8b574-8012-4dbf-84a4-91b6acfab26f;mashup=UEsDBBQAAgAIAFd/0FAiESSVqgAAAPoAAAASABwAQ29uZmlnL1BhY2thZ;location=Dim_Category",
        "impersonationMode": "impersonateCurrentUser"
      },
      {
        "name": "a747a4ed-defc-446d-abcf-3be62a2a0c37",
        "connectionString": "provider=Microsoft.PowerBI.OleDb;global pipe=0ce8b574-8012-4dbf-84a4-91b6acfab26f;mashup=\"UEsDBBQAAgAIAFd/0FAiESSVqgAAAPoAAAASABwAQ29uZmlnL1BhY2thZ2UueG1s\";location=Dim_Geography",
        "impersonationMode": "impersonateCurrentUser"
      },
      {
        "name": "4badfd5a-a0ea-4fc1-aec5-647f23d7b0ec",
        "connectionString": "provider=Microsoft.PowerBI.OleDb;global pipe=0ce8b574-8012-4dbf-84a4-91b6acfab26f;mashup=\"UEsDBBQAAgAIAFd/0FAiESSVqgAAAPoAAAASABwAQ29uZmlnL1BhY2thZ2UueG1s\";location=Dim_Geography_Type",
        "impersonationMode": "impersonateCurrentUser"
      },
      {
        "name": "cb30e0f9-efc4-41e0-8385-542b1894f127",
        "connectionString": "provider=Microsoft.PowerBI.OleDb;global pipe=0ce8b574-8012-4dbf-84a4-91b6acfab26f;mashup=\"UEsDBBQAAgAIAFd/0FAiESSVqgAAAPoAAAASABwAQ29uZmlnL1BhY2thZ2UueG1s\";location=AUX_Filter",
        "impersonationMode": "impersonateCurrentUser"
      },
      {
        "name": "c3a4813f-679e-4dfe-bad2-4ceb716a8177",
        "connectionString": "provider=Microsoft.PowerBI.OleDb;global pipe=0ce8b574-8012-4dbf-84a4-91b6acfab26f;mashup=\"UEsDBBQAAgAIAFh/0FAiESSVqgAAAPoAAAASABwAQ29uZmlnL1BhY2thZ2UueG1s\";location=Fact_SKU_Outlet_Sales",
        "impersonationMode": "impersonateCurrentUser"
      },
      {
        "name": "affc23e0-cd1f-4663-ae15-7b01be90c995",
        "connectionString": "provider=Microsoft.PowerBI.OleDb;global pipe=0ce8b574-8012-4dbf-84a4-91b6acfab26f;mashup=\"UEsDBBQAAgAIAFh/0FAiESSVqgAAAPoAAAASABwAQ29uZmlnL1BhY2thZ2UueG1s\";location=AUX_Previous_Period",
        "impersonationMode": "impersonateCurrentUser"
      },
      {
        "name": "6b59a040-c3ef-4d41-af90-8152566c4343",
        "connectionString": "provider=Microsoft.PowerBI.OleDb;global pipe=0ce8b574-8012-4dbf-84a4-91b6acfab26f;mashup=UEsDBBQAAgAIAFh/0FAiESSVqgAAAPoAAAASABwAQ29uZmlnL1BhY2thZ;location=Dim_Product_Client_Top_Analysis",
        "impersonationMode": "impersonateCurrentUser"
      },
      {
        "name": "25bbd7bf-ed18-4289-8b9d-f45d16ba1578",
        "connectionString": "provider=Microsoft.PowerBI.OleDb;global pipe=0ce8b574-8012-4dbf-84a4-91b6acfab26f;mashup=\"UEsDBBQAAgAIAFh/0FAiESSVqgAAAPoAAAASABwAQ29uZmlnL1BhY2thZ2UueG1s\";location=Fact_Sales_Metrics_Outlet",
        "impersonationMode": "impersonateCurrentUser"
      },
      {
        "name": "77a09189-637f-4f07-acd3-362e7b48e8ee",
        "connectionString": "provider=Microsoft.PowerBI.OleDb;global pipe=0ce8b574-8012-4dbf-84a4-91b6acfab26f;mashup=UEsDBBQAAgAIAFh/0FAiESSVqgAAAPoAAAASABwAQ29uZmlnL1BhY2thZ;location=Fact_Sales_Metrics_SKUOutlet",
        "impersonationMode": "impersonateCurrentUser"
      },
      {
        "name": "4910aa27-f028-4766-834b-bb0ca731d9a1",
        "connectionString": "provider=Microsoft.PowerBI.OleDb;global pipe=0ce8b574-8012-4dbf-84a4-91b6acfab26f;mashup=UEsDBBQAAgAIAFh/0FAiESSVqgAAAPoAAAASABwAQ29uZmlnL1BhY2thZ;location=Fact_Sales",
        "impersonationMode": "impersonateCurrentUser"
      },
      {
        "name": "dd39479b-a8d2-4895-aebe-359b228ec7d1",
        "connectionString": "provider=Microsoft.PowerBI.OleDb;global pipe=0ce8b574-8012-4dbf-84a4-91b6acfab26f;mashup=UEsDBBQAAgAIAFh/0FAiESSVqgAAAPoAAAASABwAQ29uZmlnL1BhY2thZ;location=Dim_Period_Alone",
        "impersonationMode": "impersonateCurrentUser"
      },
      {
        "name": "2d58a897-0f58-4fc7-8929-0ed3b2ddf5e3",
        "connectionString": "provider=Microsoft.PowerBI.OleDb;global pipe=0ce8b574-8012-4dbf-84a4-91b6acfab26f;mashup=\"UEsDBBQAAgAIAFh/0FAiESSVqgAAAPoAAAASABwAQ29uZmlnL1BhY2thZ2UueG1s\";location=Dim_Period_Type",
        "impersonationMode": "impersonateCurrentUser"
      },
      {
        "name": "20622d71-6ee0-443c-ba3c-913bd1aaa249",
        "connectionString": "provider=Microsoft.PowerBI.OleDb;global pipe=0ce8b574-8012-4dbf-84a4-91b6acfab26f;mashup=\"UEsDBBQAAgAIAFh/0FAiESSVqgAAAPoAAAASABwAQ29uZmlnL1BhY2thZ2UueG1s\";location=Dim_Geography_Store",
        "impersonationMode": "impersonateCurrentUser"
      }
    ],
    "tables": [
      {
        "name": "AUX_Text_Expression",
        "isHidden": true,
        "columns": [
          {
            "name": "Text_Name",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Text_Name",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Text_Name"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "AUX_Text_Expression-ce900067-7730-4e62-b5fc-0a113c03a0f3",
            "mode": "import",
            "source": {
              "type": "query",
              "query": "SELECT * FROM [AUX_Text_Expression]",
              "dataSource": "b6e349ca-e473-4ca8-b1fc-fe221d96b0a9"
            }
          }
        ],
        "measures": [
          {
            "name": "company_name",
            "expression": "\"DUMMmY\"",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "Head_Customer_Act",
            "expression": [
              "\"Test\"",
              ""
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "Hierarchy_Prod_L1_Name",
            "expression": [
              "",
              "var hname = values('Dim_Hierarchy_Name_Product'[hierarchy_name])",
              "return calculate(VALUES('Dim_Hierarchy_Level_Name_Product'[level_name]), 'Dim_Hierarchy_Level_Name_Product'[hierarchy_name] = hname, 'Dim_Hierarchy_Level_Name_Product'[level] = 1)"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "Hierarchy_Selected_Prod",
            "expression": "values('Dim_Hierarchy_Name_Product'[hierarchy_name])",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "Hierarchy_Prod_L2_Name",
            "expression": [
              "",
              "var hname = values('Dim_Hierarchy_Name_Product'[hierarchy_name])",
              "return calculate(VALUES('Dim_Hierarchy_Level_Name_Product'[level_name]), 'Dim_Hierarchy_Level_Name_Product'[hierarchy_name] = hname, 'Dim_Hierarchy_Level_Name_Product'[level] = 2)"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "Hierarchy_Prod_L3_Name",
            "expression": [
              "",
              "var hname = values('Dim_Hierarchy_Name_Product'[hierarchy_name])",
              "return calculate(VALUES('Dim_Hierarchy_Level_Name_Product'[level_name]), 'Dim_Hierarchy_Level_Name_Product'[hierarchy_name] = hname, 'Dim_Hierarchy_Level_Name_Product'[level] = 3)"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "Hierarchy_Prod_L4_Name",
            "expression": [
              "",
              "var hname = values('Dim_Hierarchy_Name_Product'[hierarchy_name])",
              "return calculate(VALUES('Dim_Hierarchy_Level_Name_Product'[level_name]), 'Dim_Hierarchy_Level_Name_Product'[hierarchy_name] = hname, 'Dim_Hierarchy_Level_Name_Product'[level] = 4)"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "Hierarchy_Prod_L5_Name",
            "expression": [
              "",
              "var hname = values('Dim_Hierarchy_Name_Product'[hierarchy_name])",
              "return calculate(VALUES('Dim_Hierarchy_Level_Name_Product'[level_name]), 'Dim_Hierarchy_Level_Name_Product'[hierarchy_name] = hname, 'Dim_Hierarchy_Level_Name_Product'[level] = 5)"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "Topbase_Text",
            "expression": [
              "",
              "if(hasonevalue('AUX_Top_Selection_Prod'[Top]),",
              "switch(TRUE(), ",
              "values('AUX_Top_Selection_Prod'[Top]) = \"All\", \"Not Applicable\",",
              "values('AUX_Top_Selection_Prod'[Top_Type]) = \"Top\", \"Top by\",",
              "values('AUX_Top_Selection_Prod'[Top_Type]) = \"TnB\", \"Top & Bottm by\",",
              "values('AUX_Top_Selection_Prod'[Top_Type]) = \"Bottom\", \"Bottom by\" ",
              "))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "Topbase_Color",
            "expression": [
              "",
              "if(hasonevalue('AUX_Top_Selection_Prod'[Top]),",
              "switch(TRUE(), ",
              "values('AUX_Top_Selection_Prod'[Top]) = \"All\", 0, 1",
              "))"
            ],
            "formatString": "0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "gauge_Title_CW_Sales",
            "expression": [
              "\"CWG Sales\" & ",
              "\" | \" & if(HASONEVALUE(Dim_Period[Period_Type]), values(Dim_Period[Period_Type])) &",
              "\" | \" & if(HASONEVALUE(Dim_Measure_Type[Measure]), values(Dim_Measure_Type[Display]), \"($)\")"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "gauge_Title_OTH_Sales",
            "expression": [
              "\"Ex. CWG Sales\" & ",
              "\" | \" & if(HASONEVALUE(Dim_Period[Period_Type]), values(Dim_Period[Period_Type])) &",
              "\" | \" & if(HASONEVALUE(Dim_Measure_Type[Measure]), values(Dim_Measure_Type[Display]), \"($)\")"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "gauge_Title_TOT_Sales",
            "expression": [
              "\"Total Sales\" & ",
              "\" | \" & if(HASONEVALUE(Dim_Period[Period_Type]), values(Dim_Period[Period_Type])) &",
              "\" | \" & if(HASONEVALUE(Dim_Measure_Type[Measure]), values(Dim_Measure_Type[Display]), \"($)\")\t"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "kpiCard_Title_CW_ms",
            "expression": [
              "\"CWG MS\" & ",
              "\" | \" & if(HASONEVALUE(Dim_Period[Period_Type]), values(Dim_Period[Period_Type])) &",
              "\" | \" & if(HASONEVALUE(Dim_Measure_Type[Measure]), values(Dim_Measure_Type[Display]), \"($)\")"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "kpiCard_Title_OTH_ms",
            "expression": [
              "\"Ex. CWG MS\" & ",
              "\" | \" & if(HASONEVALUE(Dim_Period[Period_Type]), values(Dim_Period[Period_Type])) &",
              "\" | \" & if(HASONEVALUE(Dim_Measure_Type[Measure]), values(Dim_Measure_Type[Display]), \"($)\")"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "kpiCard_Title_TOT_ms",
            "expression": [
              "\"Total MS\" & ",
              "\" | \" & if(HASONEVALUE(Dim_Period[Period_Type]), values(Dim_Period[Period_Type])) &",
              "\" | \" & if(HASONEVALUE(Dim_Measure_Type[Measure]), values(Dim_Measure_Type[Display]), \"($)\")"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "skuBubbleChart_Title",
            "expression": [
              "",
              "",
              "var drill_path = \"Drill path: \" & [Hierarchy_Prod_L1_Name] & \"  \" & [Hierarchy_Prod_L2_Name] & \"  \" & [Hierarchy_Prod_L3_Name]",
              "var current_selection = switch(TRUE(), ",
              "[Filter_Prod_L2],  \"Drill path: \" & [Hierarchy_Prod_L1_Name] & \"  \" & [Hierarchy_Prod_L2_Name]  & \"  \" & values(AUX_Top_Selection_Prod[Top]) & \" \" & [Hierarchy_Prod_L3_Name],",
              "[Filter_Prod_L1],  \"Drill path: \" & [Hierarchy_Prod_L1_Name] & \"  \" & values(AUX_Top_Selection_Prod[Top]) & \" \" & [Hierarchy_Prod_L2_Name],",
              "\"Drill path: \" & values(AUX_Top_Selection_Prod[Top]) & \" \" & [Hierarchy_Prod_L1_Name]",
              ")",
              "",
              "return current_selection"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "skuLineChart_Title",
            "expression": [
              "",
              "var state_name = if([Count_State] =  [Count_State_Total], \"All States\",",
              "\t\t\t\t\tif([Count_State] < 4, CONCATENATEX(values(Dim_State[State_Group]), Dim_State[State_Group], \"+\"),",
              "\t\t\t\t\t\"Selected States\"))",
              "",
              "return if(hasonevalue(AUX_LineChartMeasure[LineMeasure]),",
              "values(AUX_LineChartMeasure[LineMeasure_Display]) & \" Trend \" & ",
              "calculate(CONCATENATEX(values(Dim_Banner_Type[banner_type_display]), upper(Dim_Banner_Type[banner_type_display]), \" vs \"))) & \" for \" & [Title_Prod_Level] & \" | \" & state_name"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "skuPage_Title",
            "expression": [
              "",
              "var period_name = if(HASONEVALUE('Dim_Period'[Period_Type]), values(Dim_Period[Period_Type]), \"RQTR\") ",
              "var period_name_long = \"Current Period: \" & [Current_Period_long] & \", Gth to \" & if(HASONEVALUE(AUX_Previous_Period[display]), values(AUX_Previous_Period[display])) & \" \" & period_name",
              "var measure_name = if(HASONEVALUE(Dim_Measure_Type[Measure]), values(Dim_Measure_Type[Display]), \"($)\")",
              "var name_sku = if(hasonevalue(Dim_Product_Client_Hierarchy[pack_name]), values(Dim_Product_Client_Hierarchy[pack_name]), \"Selected SKUs\")",
              "var name_l5 = if(hasonevalue(Dim_Product_Client_Hierarchy[prod_level_5]), values(Dim_Product_Client_Hierarchy[prod_level_5]), \"Selected \" & [Hierarchy_Prod_L5_Name])",
              "var name_l4 = if(hasonevalue(Dim_Product_Client_Hierarchy[prod_level_4]), values(Dim_Product_Client_Hierarchy[prod_level_4]), \"Selected \" & [Hierarchy_Prod_L4_Name])",
              "var name_l3 = if(hasonevalue(Dim_Product_Client_Hierarchy[prod_level_3]), values(Dim_Product_Client_Hierarchy[prod_level_3]), ",
              "                    if([Count_L3] = [Count_L3_Total], \"All \" & [Hierarchy_Prod_L3_Name], ",
              "                        if([Count_L3] < 3, calculate(CONCATENATEX(values(Dim_Product_Client_Hierarchy[prod_level_3]), Dim_Product_Client_Hierarchy[prod_level_3], \"+\")),",
              "                        \"Selected \" & [Count_L3] & \" \" & [Hierarchy_Prod_L3_Name])))",
              "var name_l2 = if(hasonevalue(Dim_Product_Client_Hierarchy[prod_level_2]), values(Dim_Product_Client_Hierarchy[prod_level_2]), ",
              "                    if([Count_L2] = [Count_L2_Total], \"All \" & [Hierarchy_Prod_L2_Name], ",
              "                        if([Count_L2] < 3, calculate(CONCATENATEX(values(Dim_Product_Client_Hierarchy[prod_level_2]), Dim_Product_Client_Hierarchy[prod_level_2], \"+\")),",
              "                        \"Selected \" & [Count_L2] & \" \" & [Hierarchy_Prod_L2_Name])))",
              "var name_l1 = if(hasonevalue(Dim_Product_Client_Hierarchy[prod_level_1]), values(Dim_Product_Client_Hierarchy[prod_level_1]), ",
              "                    if([Count_L1] = [Count_L1_Total], \"All \" & [Hierarchy_Prod_L1_Name], ",
              "                        if([Count_L1] < 3, calculate(CONCATENATEX(values(Dim_Product_Client_Hierarchy[prod_level_1]), Dim_Product_Client_Hierarchy[prod_level_1], \"+\")),",
              "                        \"Selected \" & [Count_L1] & \" \" & [Hierarchy_Prod_L1_Name])))",
              "",
              "var name_oth = if([Count_L1] = [Count_L1_Total], \"All \" & [Hierarchy_Prod_L1_Name], \"All Selected Products\")",
              "",
              "var state_name = if(hasonevalue(Dim_Outlet[cw_cluster_name]), values(Dim_Outlet[cw_cluster_name]),",
              "                    if(hasonevalue(Dim_State[State_Group]), values(Dim_State[State_Group]), ",
              "                    if([Count_State] = [Count_State_Total], \"All States\", ",
              "                        if([Count_State] < 3, calculate(CONCATENATEX(values(Dim_State[State_Group]), Dim_State[State_Group], \"+\")),",
              "                        \"Selected \" & [Count_State] & \" States\")))",
              "                    )",
              "",
              "var banner_name = calculate(CONCATENATEX(values(Dim_Banner_Type[banner_type_display]), Dim_Banner_Type[banner_type_display], \"+\"))",
              "",
              "var market_name = if(hasonevalue(Dim_Market_Type[Market]), values(Dim_Market_Type[Market]) & \" Only\", \"\")",
              "",
              "var line_title =  if([Filter_SKUName],",
              "                    name_sku,",
              "                    if([Filter_Prod_L5],",
              "                            name_l5,",
              "                            if([Filter_Prod_L4],",
              "                                name_l4,",
              "                                if([Filter_Prod_L3],",
              "                                    name_l3,",
              "                                    if([Filter_Prod_L2],",
              "                                        name_l2,",
              "                                        if([Filter_Prod_L1],",
              "                                        name_l1, name_oth))))))",
              "                                        ",
              "return period_name_long & \" | \" & measure_name & \" | \" & line_title  & \" | \" & state_name & \" | \" & banner_name & \" | \" & market_name"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "Current_Period_long",
            "expression": [
              "",
              "var currentperiod = calculate(max('Dim_Period'[period_start]))",
              "return CALCULATE(values('Dim_Period'[Period_Long_Name]), 'Dim_Period'[period_start] = currentperiod)"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "Title_Prod_Level",
            "expression": [
              "",
              "var name_sku = if(hasonevalue(Dim_Product_Client_Hierarchy[pack_name]), values(Dim_Product_Client_Hierarchy[pack_name]), \"Selected SKUs\")",
              "var name_l5 = if(hasonevalue(Dim_Product_Client_Hierarchy[prod_level_5]), values(Dim_Product_Client_Hierarchy[prod_level_5]), \"Selected \" & [Hierarchy_Prod_L5_Name])",
              "var name_l4 = if(hasonevalue(Dim_Product_Client_Hierarchy[prod_level_4]), values(Dim_Product_Client_Hierarchy[prod_level_4]), \"Selected \" & [Hierarchy_Prod_L4_Name])",
              "var name_l3 = if(hasonevalue(Dim_Product_Client_Hierarchy[prod_level_3]), values(Dim_Product_Client_Hierarchy[prod_level_3]), \"Selected \" & [Hierarchy_Prod_L3_Name])",
              "var name_l2 = if(hasonevalue(Dim_Product_Client_Hierarchy[prod_level_2]), values(Dim_Product_Client_Hierarchy[prod_level_2]), \"Selected \" & [Hierarchy_Prod_L2_Name])",
              "var name_l1 = if(hasonevalue(Dim_Product_Client_Hierarchy[prod_level_1]), values(Dim_Product_Client_Hierarchy[prod_level_1]), \"Selected \" & [Hierarchy_Prod_L1_Name])",
              "var name_oth = \"All Selected Products\"",
              "",
              "var line_title =  if([Filter_SKUName],",
              "                    name_sku,",
              "                    if([Filter_Prod_L5],",
              "                            name_l5,",
              "                            if([Filter_Prod_L4],",
              "                                name_l4,",
              "                                if([Filter_Prod_L3],",
              "                                    name_l3,",
              "                                    if([Filter_Prod_L2],",
              "                                        name_l2,",
              "                                        if([Filter_Prod_L1],",
              "                                        name_l1, name_oth))))))",
              "",
              "return line_title"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "Button_Title_Prod_L1",
            "expression": "[Hierarchy_Prod_L1_Name] & \" View\"",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "Button_Title_Prod_L2",
            "expression": "[Hierarchy_Prod_L2_Name] & \" View\"",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "Button_Title_Prod_State",
            "expression": "\"State View\"",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "Home_kpi_Title",
            "expression": [
              "",
              "var banner_name = calculate(CONCATENATEX(values(Dim_Banner_Type[banner_type_display]), upper(Dim_Banner_Type[banner_type_display]), \"+\"))",
              "var period_type_base = if(HASONEVALUE(Dim_Period[period_type_base]), values(Dim_Period[period_type_base]))",
              "var period_type = if(HASONEVALUE(Dim_Period[Period_Type]), values(Dim_Period[Period_Type]))",
              "var measure_name = \tif(HASONEVALUE(Dim_Measure_Type[Measure]), values(Dim_Measure_Type[Display]), \"($)\")\t",
              "var category_name = if([Count_L1] =  [Count_L1_Total], \" | All Categories\",",
              "\t\t\t\t\tif([Count_L1] < 3, \" | \" & CONCATENATEX(values(Dim_Product_Client_Hierarchy[prod_level_1]), Dim_Product_Client_Hierarchy[prod_level_1], \"+\"),",
              "\t\t\t\t\t\" | Selected Categories\"))\t\t\t",
              "var state_name = if([Count_State] =  [Count_State_Total], \" | All States\",",
              "\t\t\t\t\tif([Count_State] < 3, \" | \" & CONCATENATEX(values(Dim_State[State_Group]), Dim_State[State_Group], \"+\"),",
              "\t\t\t\t\t\" | Selected States\"))",
              "var p_type = if(period_type_base = \"WTD\", \"WTD\", period_type)",
              "Var period_name_long = p_type & \", \" & [Current_Period_long] & \", Gth to \" & if(HASONEVALUE(AUX_Previous_Period[display]), values(AUX_Previous_Period[display])) ",
              "",
              "",
              "return \"Performance Glance: \" & period_name_long & \" | \" & banner_name & \" | \" & measure_name & category_name & state_name"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "Home_Waterfall_Title",
            "expression": "\"Product Growth by \" & [Hierarchy_Prod_L1_Name]",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "skuBubbleChart_Title_L2",
            "expression": "values(AUX_Top_Selection_Prod[Top]) & \" \" & [Hierarchy_Prod_L2_Name]",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "skuBubbleChart_Title_L3",
            "expression": "values(AUX_Top_Selection_Prod[Top]) & \" \" & [Hierarchy_Prod_L3_Name]",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "Button_Title_Prod_L3",
            "expression": "[Hierarchy_Prod_L3_Name] & \" View\"",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "skuBubbleChart_Title_State",
            "expression": [
              "",
              "var state_name = if([Count_State] =  [Count_State_Total], \"All States\",",
              "\t\t\t\t\tif([Count_State] < 4, CONCATENATEX(values(Dim_State[State_Group]), Dim_State[State_Group], \"+\"),",
              "\t\t\t\t\t\"Selected States\"))",
              "",
              "return state_name"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "TnB_Legend_Text",
            "expression": "if(values(AUX_Top_Select_Option[top_option]) = \"Value\", values(Dim_Measure_Type[display]) & \" Value\", values(Dim_Measure_Type[display]) & \" Growth\")",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "tnbPage_Title",
            "expression": [
              "",
              "var period_name = if(HASONEVALUE(Dim_Period[Period_Type]), values(Dim_Period[Period_Type]), \"RQTR\") ",
              "var period_name_long = \"Current Period: \" & [Current_Period_long] & \", Gth to \" & if(HASONEVALUE(AUX_Previous_Period[display]), values(AUX_Previous_Period[display])) & \" \" & period_name",
              "var measure_name = if(HASONEVALUE(Dim_Measure_Type[Measure]), values(Dim_Measure_Type[Display]), \"($)\")",
              "var name_sku = if(hasonevalue(Dim_Product_Client_Top_Analysis[top_items]), values(Dim_Product_Client_Top_Analysis[top_items]), \"Selected SKUs\")",
              "var name_segment = if(hasonevalue(Dim_Product_Client[Segment]), values(Dim_Product_Client[Segment]), \"Selected Segments\")",
              "var name_subseg = if(hasonevalue(Dim_Product_Client[Sub_segment]), values(Dim_Product_Client[Sub_segment]), \"Selected Sub Segments\")",
              "",
              "var name_category = if(hasonevalue(Dim_Category[Category]), values(Dim_Category[Category]), ",
              "                    if([Count_Category] = [Count_Category_Total], \"All Categories\", ",
              "                        if([Count_Category] < 3, calculate(CONCATENATEX(values(Dim_Category[Category]), Dim_Category[Category], \"+\")),",
              "                        \"Selected \" & [Count_Category] & \" Categories\")))\t\t\t\t\t\t",
              "\t\t\t\t\t\t",
              "",
              "var name_oth = if([Count_L1] = [Count_L1_Total], \"All \" & [Hierarchy_Prod_L1_Name], \"All Selected Products\")",
              "",
              "var state_name = if(hasonevalue(Dim_State[State_Group]), values(Dim_State[State_Group]), ",
              "                    if([Count_State] = [Count_State_Total], \"All States\", ",
              "                        if([Count_State] < 3, calculate(CONCATENATEX(values(Dim_State[State_Group]), Dim_State[State_Group], \"+\")),",
              "                        \"Selected \" & [Count_State] & \" States\")))",
              "",
              "var banner_name = calculate(CONCATENATEX(values(Dim_Banner_Type[banner_type_display]), Dim_Banner_Type[banner_type_display], \"+\"))",
              "",
              "var market_name = if(hasonevalue(Dim_Market_Type[Market]), \" | \" & values(Dim_Market_Type[Market]) & \" Only\", \"\")",
              "",
              "var rank_name = if(hasonevalue(Dim_Product_Client_Top_Analysis[top_base]), values(Dim_Product_Client_Top_Analysis[top_base]), \"\") & \" Ranked by \" & ",
              "\t\t\t\t\tif(hasonevalue(AUX_Top_Select_Option[top_option]), values(AUX_Top_Select_Option[top_option]), \"\")",
              "",
              "",
              "",
              "var line_title =  if([Filter_Subsegment],",
              "                    name_subseg,",
              "                    if([Filter_Segment],",
              "                            name_segment,",
              "                            name_category))",
              "                                        ",
              "return period_name_long & \" | \" & measure_name & \" | \" & line_title  & \" | \" & state_name & \" | \" & banner_name & market_name & \" | \" & rank_name"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "tnbPage_Chart_Title",
            "expression": [
              "",
              "var period_name = if(HASONEVALUE(Dim_Period[Period_Type]), values(Dim_Period[Period_Type]), \"RQTR\") ",
              "var period_name_long = \"Current Period: \" & [Current_Period_long] & \", Gth to \" & if(HASONEVALUE(AUX_Previous_Period[name]), values(AUX_Previous_Period[name])) & \" \" & period_name",
              "var measure_name = if(HASONEVALUE(Dim_Measure_Type[Measure]), values(Dim_Measure_Type[Display]), \"($)\")",
              "var name_sku = if(hasonevalue(Dim_Product_Client_Top_Analysis[top_items]), values(Dim_Product_Client_Top_Analysis[top_items]), \"Selected SKUs\")",
              "var name_segment = if(hasonevalue(Dim_Product_Client[Segment]), values(Dim_Product_Client[Segment]), \"Selected Segments\")",
              "var name_subseg = if(hasonevalue(Dim_Product_Client[Sub_segment]), values(Dim_Product_Client[Sub_segment]), \"Selected Sub Segments\")",
              "",
              "var name_category = if(hasonevalue(Dim_Category[Category]), values(Dim_Category[Category]), ",
              "                    if([Count_Category] = [Count_Category_Total], \"All Categories\", ",
              "                        if([Count_Category] < 3, calculate(CONCATENATEX(values(Dim_Category[Category]), Dim_Category[Category], \"+\")),",
              "                        \"Selected \" & [Count_Category] & \" Categories\")))\t\t\t\t\t\t",
              "\t\t\t\t\t\t",
              "",
              "var name_oth = \"All Selected Products\"",
              "",
              "var state_name = if(hasonevalue(Dim_State[State_Group]), values(Dim_State[State_Group]), ",
              "                    if([Count_State] = [Count_State_Total], \"All States\", ",
              "                        if([Count_State] < 3, calculate(CONCATENATEX(values(Dim_State[State_Group]), Dim_State[State_Group], \"+\")),",
              "                        \"Selected \" & [Count_State] & \" States\")))",
              "",
              "var banner_name = calculate(CONCATENATEX(values(Dim_Banner_Type[banner_type]), upper(Dim_Banner_Type[banner_type]), \"+\"))",
              "",
              "var market_name = if(hasonevalue(Dim_Market_Type[Market]), \" | \" & values(Dim_Market_Type[Market]) & \" Only\", \"\")",
              "",
              "var top_name = if(hasonevalue(AUX_Top_Selection_Prod[Top]), values(AUX_Top_Selection_Prod[Top]) & \" \", \"\")",
              "",
              "var rank_name_SKU = if(hasonevalue(Dim_Product_Client_Top_Analysis[top_base]), values(Dim_Product_Client_Top_Analysis[top_base]), \"\") & \" Ranked by \" & ",
              "\t\t\t\t\tif(hasonevalue(AUX_Top_Select_Option[top_option]), values(AUX_Top_Select_Option[top_option]), \"\")",
              "",
              "var rank_name_Oulet = if(hasonevalue(Dim_Geography_Type[Geography_Type]), values(Dim_Geography_Type[Geography_Type]), \"\") & \" Ranked by \" & ",
              "\t\t\t\t\tif(hasonevalue(AUX_Top_Select_Option[top_option]), values(AUX_Top_Select_Option[top_option]), \"\")",
              "",
              " var rank_name = if(hasonevalue(AUX_ReportTemplate[metric_base]), switch(TRUE(),  values(AUX_ReportTemplate[metric_base]) = \"Outlet\", rank_name_Oulet, rank_name_sku), rank_name_sku)                 ",
              "",
              "var line_title =  if([Filter_Subsegment],",
              "                    name_subseg,",
              "                    if([Filter_Segment],",
              "                            name_segment,",
              "                            name_category))",
              "                                        ",
              "return  top_name & rank_name & \" | \" & measure_name & \" | \" & line_title  & \" | \" & state_name & \" | \" & banner_name & market_name"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "Title_TnB_Popup",
            "expression": [
              "",
              "var tnb_prod = if(hasonevalue(Dim_Product_Client_Top_Analysis[top_items]), values(Dim_Product_Client_Top_Analysis[top_items]), \"Selected Items\")",
              "var tnb_geo = if(hasonevalue(Dim_Geography[Geography_Name]), values(Dim_Geography[Geography_Name]), \"Selected Geographies\")",
              "",
              "return if(hasonevalue(AUX_ReportTemplate[metric_base]), ",
              "switch(TRUE(), values(AUX_ReportTemplate[metric_base]) = \"Outlet\", tnb_geo, tnb_prod), tnb_prod)"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "Button_Title_Tab_Prod_State",
            "expression": "\"Product by State\"",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "Button_Title_Tab_Prod_Period",
            "expression": "\"Product by Period\"",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "Button_Title_Tab_Geo_Category",
            "expression": "\"Geography by Category\"",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "Button_Title_Tab_Geo_Period",
            "expression": "\"Geography by Period\"",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "tab_Page_Title_Prod_State",
            "expression": "\"Tabular Reporting & Data Exporting: Product Hierarchy by State\"",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "tab_Page_Title_Prod_Period",
            "expression": "\"Tabular Reporting & Data Exporting: Product Hierarchy by Period\"",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "tab_Page_Title_Geo_Period",
            "expression": "\"Tabular Reporting & Data Exporting: Geography by Period\"",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "tab_Page_Title_Geo_Category",
            "expression": "\"Tabular Reporting & Data Exporting: Geography by Category\"",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "tab_Table_Title_Period",
            "expression": [
              "",
              "var period_name = if(HASONEVALUE(Dim_Period[Period_Type]), values(Dim_Period[Period_Type]), \"Selected Periods\") ",
              "var period_name_long = \"Growth to \" & if(HASONEVALUE(AUX_Previous_Period[name]), values(AUX_Previous_Period[name])) & \" \" & period_name",
              "var measure_name = if(HASONEVALUE(Dim_Measure_Type[Measure]), values(Dim_Measure_Type[Display]), \"($)\")",
              "var name_sku = if(hasonevalue(Dim_Product_Client_Hierarchy[pack_name]), values(Dim_Product_Client_Hierarchy[pack_name]), \"Selected SKUs\")",
              "var name_l5 = if(hasonevalue(Dim_Product_Client_Hierarchy[prod_level_5]), values(Dim_Product_Client_Hierarchy[prod_level_5]), \"Selected \" & [Hierarchy_Prod_L5_Name])",
              "var name_l4 = if(hasonevalue(Dim_Product_Client_Hierarchy[prod_level_4]), values(Dim_Product_Client_Hierarchy[prod_level_4]), \"Selected \" & [Hierarchy_Prod_L4_Name])",
              "var name_l3 = if(hasonevalue(Dim_Product_Client_Hierarchy[prod_level_3]), values(Dim_Product_Client_Hierarchy[prod_level_3]), ",
              "                    if([Count_L3] = [Count_L3_Total], \"All \" & [Hierarchy_Prod_L3_Name], ",
              "                        if([Count_L3] < 3, calculate(CONCATENATEX(values(Dim_Product_Client_Hierarchy[prod_level_3]), Dim_Product_Client_Hierarchy[prod_level_3], \"+\")),",
              "                        \"Selected \" & [Count_L3] & \" \" & [Hierarchy_Prod_L3_Name])))",
              "var name_l2 = if(hasonevalue(Dim_Product_Client_Hierarchy[prod_level_2]), values(Dim_Product_Client_Hierarchy[prod_level_2]), ",
              "                    if([Count_L2] = [Count_L2_Total], \"All \" & [Hierarchy_Prod_L2_Name], ",
              "                        if([Count_L2] < 3, calculate(CONCATENATEX(values(Dim_Product_Client_Hierarchy[prod_level_2]), Dim_Product_Client_Hierarchy[prod_level_2], \"+\")),",
              "                        \"Selected \" & [Count_L2] & \" \" & [Hierarchy_Prod_L2_Name])))",
              "var name_l1 = if(hasonevalue(Dim_Product_Client_Hierarchy[prod_level_1]), values(Dim_Product_Client_Hierarchy[prod_level_1]), ",
              "                    if([Count_L1] = [Count_L1_Total], \"All \" & [Hierarchy_Prod_L1_Name], ",
              "                        if([Count_L1] < 3, calculate(CONCATENATEX(values(Dim_Product_Client_Hierarchy[prod_level_1]), Dim_Product_Client_Hierarchy[prod_level_1], \"+\")),",
              "                        \"Selected \" & [Count_L1] & \" \" & [Hierarchy_Prod_L1_Name])))",
              "",
              "var line_title_cat = if(hasonevalue(Dim_Category[Category]), values(Dim_Category[Category]), ",
              "                    if([Count_Category] = [Count_Category_Total], \"All Categories\", ",
              "                        if([Count_Category] < 3, calculate(CONCATENATEX(values(Dim_Category[Category]), Dim_Category[Category], \"+\")),",
              "                        \"Selected \" & [Count_Category] & \" Categories\")))",
              "",
              "var name_oth = \"All Selected Products\"",
              "",
              "var state_name = if(hasonevalue(Dim_State[State_Group]), values(Dim_State[State_Group]), ",
              "                    if([Count_State] = [Count_State_Total], \"All States\", ",
              "                        if([Count_State] < 3, calculate(CONCATENATEX(values(Dim_State[State_Group]), Dim_State[State_Group], \"+\")),",
              "                        \"Selected \" & [Count_State] & \" States\")))",
              "",
              "var banner_name = calculate(CONCATENATEX(values(Dim_Banner_Type[banner_type]), upper(Dim_Banner_Type[banner_type]), \"+\"))",
              "",
              "var market_name = if(hasonevalue(Dim_Market_Type[Market]), values(Dim_Market_Type[Market]) & \" Only\", \"\")",
              "",
              "var line_title =  if([Filter_SKUName],",
              "                    name_sku,",
              "                    if([Filter_Prod_L5],",
              "                            name_l5,",
              "                            if([Filter_Prod_L4],",
              "                                name_l4,",
              "                                if([Filter_Prod_L3],",
              "                                    name_l3,",
              "                                    if([Filter_Prod_L2],",
              "                                        name_l2,",
              "                                        if([Filter_Prod_L1],",
              "                                        name_l1, name_oth))))))",
              "                                        ",
              "return period_name_long & \" | \" & measure_name & \" | \" & line_title_cat  & \" | \" & state_name & \" | \" & banner_name & \" | \" & market_name"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "gauge_Title_Map_Sales",
            "expression": [
              "",
              "var p_type_base = SELECTEDVALUE('AUX_Previous_Period'[name], \"LY\")",
              "var p_type = if([period_TypeBase] in  {\"WTD\", \"DAY\"} && p_type_base = \"LY\", \"LW\", p_type_base)",
              "",
              "return \"Sales vs \" & p_type & \" Sales & Market\" &",
              "\" | \" & if(HASONEVALUE(Dim_Period[Period_Type]), values(Dim_Period[Period_Type])) &",
              "\" | \" & if(HASONEVALUE(Dim_Measure_Type[Measure]), values(Dim_Measure_Type[Display]), \"($)\")"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "mapPage_Title",
            "expression": [
              "",
              "var period_name = if(HASONEVALUE(Dim_Period[Period_Type]), values(Dim_Period[Period_Type]), \"RQTR\") ",
              "var period_name_long = \"Current Period: \" & [Current_Period_long] & \", Gth to \" & if(HASONEVALUE(AUX_Previous_Period[display]), values(AUX_Previous_Period[display])) & \" \" & period_name",
              "var measure_name = if(HASONEVALUE(Dim_Measure_Type[Measure]), values(Dim_Measure_Type[Display]), \"($)\")",
              "var name_sku = if(hasonevalue(Dim_Product_Client_Top_Analysis[top_items]), values(Dim_Product_Client_Top_Analysis[top_items]), \"Selected SKUs\")",
              "var name_segment = if(hasonevalue(Dim_Product_Client[Segment]), values(Dim_Product_Client[Segment]), \"Selected Segments\")",
              "var name_subseg = if(hasonevalue(Dim_Product_Client[Sub_segment]), values(Dim_Product_Client[Sub_segment]), \"Selected Sub Segments\")",
              "",
              "var name_category = if(hasonevalue(Dim_Category[Category]), values(Dim_Category[Category]), ",
              "                    if([Count_Category] = [Count_Category_Total], \"All Categories\", ",
              "                        if([Count_Category] < 3, calculate(CONCATENATEX(values(Dim_Category[Category]), Dim_Category[Category], \"+\")),",
              "                        \"Selected \" & [Count_Category] & \" Categories\")))\t\t\t\t\t\t",
              "\t\t\t\t\t\t",
              "",
              "var name_oth = if([Count_L1] = [Count_L1_Total], \"All \" & [Hierarchy_Prod_L1_Name], \"All Selected Products\")",
              "",
              "var state_name = if(hasonevalue(Dim_Geography[State]), values(Dim_Geography[State]), ",
              "                    if([Count_GeoState] = [Count_GeoState_Total], \"All States\", ",
              "                        if([Count_GeoState] < 3, calculate(CONCATENATEX(values(Dim_Geography[State]), Dim_Geography[State], \"+\")),",
              "                        \"Selected \" & [Count_GeoState] & \" States\")))",
              "var geo_name = if(hasonevalue(Dim_Geography[Geography_Name]), values(Dim_Geography[Geography_Name]), \"Selected Areas\")",
              "",
              "var geo_title = if([Filter_GeographyName], geo_name, state_name)",
              "",
              "var banner_name = calculate(CONCATENATEX(values(Dim_Banner_Type[banner_type_display]), Dim_Banner_Type[banner_type_display], \"+\"))",
              "",
              "var market_name = if(hasonevalue(Dim_Market_Type[Market]), \" | \" & values(Dim_Market_Type[Market]) & \" Only\", \"\")",
              "",
              "var rank_name = if(hasonevalue(Dim_Product_Client_Top_Analysis[top_base]), values(Dim_Product_Client_Top_Analysis[top_base]), \"\") & \" Ranked by \" & ",
              "\t\t\t\t\tif(hasonevalue(AUX_Top_Select_Option[top_option]), values(AUX_Top_Select_Option[top_option]), \"\")",
              "",
              "var geo_type = selectedvalue(Dim_Geography_Type[Geography_Type], \"State\")",
              "",
              "var line_title =  if([Filter_Subsegment],",
              "                    name_subseg,",
              "                    if([Filter_Segment],",
              "                            name_segment,",
              "                            name_category))",
              "                                        ",
              " var rp_title =  geo_type & \"  | \" & period_name_long & \" | \" & measure_name & \" | \" & line_title  & \" | \" & geo_title & \" | \" & banner_name & \" Sales\" & market_name            ",
              " var rp_Error = \"!! Click the Choropleth Map Sea Area to Clear Area Filter !!\"",
              "",
              " var no_market = ISBLANK([Sales_Market])                         ",
              "return if(no_market, rp_Error, rp_title)"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "measure_Selected",
            "expression": "SELECTEDVALUE('AUX_LineChartMeasure'[LineMeasure_Display], \"Product Sales\")",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "mapLineChart_Title",
            "expression": [
              "",
              "var state_name = if(hasonevalue(Dim_Geography[State]), values(Dim_Geography[State]), ",
              "                    if([Count_GeoState] = [Count_GeoState_Total], \"All States\", ",
              "                        if([Count_GeoState] < 4, calculate(CONCATENATEX(values(Dim_Geography[State]), Dim_Geography[State], \"+\")),",
              "                        \"Selected \" & [Count_GeoState] & \" States\")))",
              "",
              "var name_category = if(hasonevalue(Dim_Category[Category]), values(Dim_Category[Category]), ",
              "                    if([Count_Category] = [Count_Category_Total], \"All Categories\", ",
              "                        if([Count_Category] < 3, calculate(CONCATENATEX(values(Dim_Category[Category]), Dim_Category[Category], \"+\")),",
              "                        \"Selected \" & [Count_Category] & \" Categories\")))\t",
              "\t\t\t\t\t\t",
              "return if(hasonevalue(AUX_LineChartMeasure[LineMeasure]),",
              "values(AUX_LineChartMeasure[LineMeasure_Display]) & \" Trend \" & \" for \" & name_category & \" | \" & state_name)"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "Calendar_MonthName_1",
            "expression": "[Calendar_MonthName] & \" Daily: \" & [measure_Selected]",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "Calendar_MonthName_2",
            "expression": "[Calendar_MonthName] & \" Week to Date: \" & [measure_Selected]",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "Calendar_MonthName",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start_day]), filter(all('Dim_Period'), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[Month_Order] = 1))",
              "var m_name = SELECTEDVALUE('Dim_Period'[Period_Month_Name], format(currentperiod, \"MMM yyyy\"))",
              "",
              "return m_name"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "Current_Period_long_daily",
            "expression": [
              "",
              "var currentperiod = calculate(max('Dim_Period'[period_start_day]))",
              "return format(currentperiod, \"ddd yyyy-MM-dd\")"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "dailyPage_Title",
            "expression": [
              "",
              "var period_name = \"Daily\"",
              "var period_name_long = \"Current Period: \" & [Current_Period_long_daily] & \", Gth to \" & if(HASONEVALUE(AUX_Previous_Period[display]), values(AUX_Previous_Period[display])) & \" \" & period_name",
              "var measure_name = if(HASONEVALUE(Dim_Measure_Type[Measure]), values(Dim_Measure_Type[Display]), \"($)\")",
              "var name_sku = if(hasonevalue(Dim_Product_Client_Hierarchy[pack_name]), values(Dim_Product_Client_Hierarchy[pack_name]), \"Selected SKUs\")",
              "var name_l5 = if(hasonevalue(Dim_Product_Client_Hierarchy[prod_level_5]), values(Dim_Product_Client_Hierarchy[prod_level_5]), \"Selected \" & [Hierarchy_Prod_L5_Name])",
              "var name_l4 = if(hasonevalue(Dim_Product_Client_Hierarchy[prod_level_4]), values(Dim_Product_Client_Hierarchy[prod_level_4]), \"Selected \" & [Hierarchy_Prod_L4_Name])",
              "var name_l3 = if(hasonevalue(Dim_Product_Client_Hierarchy[prod_level_3]), values(Dim_Product_Client_Hierarchy[prod_level_3]), ",
              "                    if([Count_L3] = [Count_L3_Total], \"All \" & [Hierarchy_Prod_L3_Name], ",
              "                        if([Count_L3] < 3, calculate(CONCATENATEX(values(Dim_Product_Client_Hierarchy[prod_level_3]), Dim_Product_Client_Hierarchy[prod_level_3], \"+\")),",
              "                        \"Selected \" & [Count_L3] & \" \" & [Hierarchy_Prod_L3_Name])))",
              "var name_l2 = if(hasonevalue(Dim_Product_Client_Hierarchy[prod_level_2]), values(Dim_Product_Client_Hierarchy[prod_level_2]), ",
              "                    if([Count_L2] = [Count_L2_Total], \"All \" & [Hierarchy_Prod_L2_Name], ",
              "                        if([Count_L2] < 3, calculate(CONCATENATEX(values(Dim_Product_Client_Hierarchy[prod_level_2]), Dim_Product_Client_Hierarchy[prod_level_2], \"+\")),",
              "                        \"Selected \" & [Count_L2] & \" \" & [Hierarchy_Prod_L2_Name])))",
              "var name_l1 = if(hasonevalue(Dim_Product_Client_Hierarchy[prod_level_1]), values(Dim_Product_Client_Hierarchy[prod_level_1]), ",
              "                    if([Count_L1] = [Count_L1_Total], \"All \" & [Hierarchy_Prod_L1_Name], ",
              "                        if([Count_L1] < 3, calculate(CONCATENATEX(values(Dim_Product_Client_Hierarchy[prod_level_1]), Dim_Product_Client_Hierarchy[prod_level_1], \"+\")),",
              "                        \"Selected \" & [Count_L1] & \" \" & [Hierarchy_Prod_L1_Name])))",
              "",
              "var name_oth = if([Count_L1] = [Count_L1_Total], \"All \" & [Hierarchy_Prod_L1_Name], \"All Selected Products\")",
              "",
              "var state_name = if(hasonevalue(Dim_State[State_Group]), values(Dim_State[State_Group]), ",
              "                    if([Count_State] = [Count_State_Total], \"All States\", ",
              "                        if([Count_State] < 3, calculate(CONCATENATEX(values(Dim_State[State_Group]), Dim_State[State_Group], \"+\")),",
              "                        \"Selected \" & [Count_State] & \" States\")))",
              "",
              "var banner_name = calculate(CONCATENATEX(values(Dim_Banner_Type[banner_type_display]), Dim_Banner_Type[banner_type_display], \"+\"))",
              "",
              "var market_name = if(hasonevalue(Dim_Market_Type[Market]), values(Dim_Market_Type[Market]) & \" Only\", \"\")",
              "",
              "var line_title =  if([Filter_SKUName],",
              "                    name_sku,",
              "                    if([Filter_Prod_L5],",
              "                            name_l5,",
              "                            if([Filter_Prod_L4],",
              "                                name_l4,",
              "                                if([Filter_Prod_L3],",
              "                                    name_l3,",
              "                                    if([Filter_Prod_L2],",
              "                                        name_l2,",
              "                                        if([Filter_Prod_L1],",
              "                                        name_l1, name_oth))))))",
              "                                        ",
              "return period_name_long & \" | \" & measure_name & \" | \" & line_title  & \" | \" & state_name & \" | \" & banner_name & \" | \" & market_name "
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "period_TypeBase",
            "expression": "SELECTEDVALUE('Dim_Period'[period_type_base], \"MTH\")",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "weekstart_Name",
            "expression": "\"Week Start: \" & SELECTEDVALUE('Dim_Period'[weekdaystart] , \"Sun --> Sat\")",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "tab_GeoMatrix_Title",
            "expression": [
              "",
              "var period_name = if(HASONEVALUE('Dim_Period'[Period_Type]), values(Dim_Period[Period_Type]), \"RQTR\") ",
              "var period_name_long = \"Current Period: \" & [Current_Period_long] & \", Gth to \" & if(HASONEVALUE(AUX_Previous_Period[display]), values(AUX_Previous_Period[display])) & \" \" & period_name",
              "var measure_name = if(HASONEVALUE(Dim_Measure_Type[Measure]), values(Dim_Measure_Type[Display]), \"($)\")",
              "var name_sku = if(hasonevalue(Dim_Product_Client_Hierarchy[pack_name]), values(Dim_Product_Client_Hierarchy[pack_name]), \"Selected SKUs\")",
              "var name_l5 = if(hasonevalue(Dim_Product_Client_Hierarchy[prod_level_5]), values(Dim_Product_Client_Hierarchy[prod_level_5]), \"Selected \" & [Hierarchy_Prod_L5_Name])",
              "var name_l4 = if(hasonevalue(Dim_Product_Client_Hierarchy[prod_level_4]), values(Dim_Product_Client_Hierarchy[prod_level_4]), \"Selected \" & [Hierarchy_Prod_L4_Name])",
              "var name_l3 = if(hasonevalue(Dim_Product_Client_Hierarchy[prod_level_3]), values(Dim_Product_Client_Hierarchy[prod_level_3]), ",
              "                    if([Count_L3] = [Count_L3_Total], \"All \" & [Hierarchy_Prod_L3_Name], ",
              "                        if([Count_L3] < 3, calculate(CONCATENATEX(values(Dim_Product_Client_Hierarchy[prod_level_3]), Dim_Product_Client_Hierarchy[prod_level_3], \"+\")),",
              "                        \"Selected \" & [Count_L3] & \" \" & [Hierarchy_Prod_L3_Name])))",
              "var name_l2 = if(hasonevalue(Dim_Product_Client_Hierarchy[prod_level_2]), values(Dim_Product_Client_Hierarchy[prod_level_2]), ",
              "                    if([Count_L2] = [Count_L2_Total], \"All \" & [Hierarchy_Prod_L2_Name], ",
              "                        if([Count_L2] < 3, calculate(CONCATENATEX(values(Dim_Product_Client_Hierarchy[prod_level_2]), Dim_Product_Client_Hierarchy[prod_level_2], \"+\")),",
              "                        \"Selected \" & [Count_L2] & \" \" & [Hierarchy_Prod_L2_Name])))",
              "var name_l1 = if(hasonevalue(Dim_Product_Client_Hierarchy[prod_level_1]), values(Dim_Product_Client_Hierarchy[prod_level_1]), ",
              "                    if([Count_L1] = [Count_L1_Total], \"All \" & [Hierarchy_Prod_L1_Name], ",
              "                        if([Count_L1] < 3, calculate(CONCATENATEX(values(Dim_Product_Client_Hierarchy[prod_level_1]), Dim_Product_Client_Hierarchy[prod_level_1], \"+\")),",
              "                        \"Selected \" & [Count_L1] & \" \" & [Hierarchy_Prod_L1_Name])))",
              "var line_title_cat = if(hasonevalue(Dim_Category[Category]), values(Dim_Category[Category]), ",
              "                    if([Count_Category] = [Count_Category_Total], \"All Categories\", ",
              "                        if([Count_Category] < 3, calculate(CONCATENATEX(values(Dim_Category[Category]), Dim_Category[Category], \"+\")),",
              "                        \"Selected \" & [Count_Category] & \" Categories\")))",
              "",
              "",
              "var name_oth = if([Count_Category] = [Count_Category_Total], \"All Categories\")",
              "",
              "var state_name = if(hasonevalue(Dim_State[State_Group]), values(Dim_State[State_Group]), ",
              "                    if([Count_State] = [Count_State_Total], \"All States\", ",
              "                        if([Count_State] < 3, calculate(CONCATENATEX(values(Dim_State[State_Group]), Dim_State[State_Group], \"+\")),",
              "                        \"Selected \" & [Count_State] & \" States\")))",
              "",
              "var banner_name = calculate(CONCATENATEX(values(Dim_Banner_Type[banner_type_display]), Dim_Banner_Type[banner_type_display], \"+\"))",
              "",
              "var market_name = if(hasonevalue(Dim_Market_Type[Market]), values(Dim_Market_Type[Market]) & \" Only\", \"\")",
              "",
              "var line_title =  if([Filter_SKUName],",
              "                    name_sku,",
              "                    if([Filter_Prod_L5],",
              "                            name_l5,",
              "                            if([Filter_Prod_L4],",
              "                                name_l4,",
              "                                if([Filter_Prod_L3],",
              "                                    name_l3,",
              "                                    if([Filter_Prod_L2],",
              "                                        name_l2,",
              "                                        if([Filter_Prod_L1],",
              "                                        name_l1, name_oth))))))",
              "",
              "                                        ",
              "return period_name_long & \" | \" & measure_name & \" | \" & line_title_cat  & \" | \" & state_name & \" | \" & banner_name & \" | \" & market_name"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "Current_Period_short",
            "expression": [
              "",
              "var currentperiod = calculate(max('Dim_Period'[period_start]))",
              "return CALCULATE(values('Dim_Period'[Period_Name]), 'Dim_Period'[period_start] = currentperiod) "
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "mapChoropleth_Title",
            "expression": [
              "",
              "var period_name = if(HASONEVALUE(Dim_Period[Period_Type]), values(Dim_Period[Period_Type]), \"RQTR\") ",
              "var period_name_long = \"Current Period: \" & [Current_Period_long] & \", Gth to \" & if(HASONEVALUE(AUX_Previous_Period[display]), values(AUX_Previous_Period[display])) & \" \" & period_name",
              "var measure_name = if(HASONEVALUE(Dim_Measure_Type[Measure]), values(Dim_Measure_Type[Display]), \"($)\")",
              "var name_sku = if(hasonevalue(Dim_Product_Client_Top_Analysis[top_items]), values(Dim_Product_Client_Top_Analysis[top_items]), \"Selected SKUs\")",
              "var name_segment = if(hasonevalue(Dim_Product_Client[Segment]), values(Dim_Product_Client[Segment]), \"Selected Segments\")",
              "var name_subseg = if(hasonevalue(Dim_Product_Client[Sub_segment]), values(Dim_Product_Client[Sub_segment]), \"Selected Sub Segments\")",
              "",
              "var name_category = if(hasonevalue(Dim_Category[Category]), values(Dim_Category[Category]), ",
              "                    if([Count_Category] = [Count_Category_Total], \"All Categories\", ",
              "                        if([Count_Category] < 3, calculate(CONCATENATEX(values(Dim_Category[Category]), Dim_Category[Category], \"+\")),",
              "                        \"Selected \" & [Count_Category] & \" Categories\")))\t\t\t\t\t\t",
              "\t\t\t\t\t\t",
              "",
              "var name_oth = if([Count_L1] = [Count_L1_Total], \"All \" & [Hierarchy_Prod_L1_Name], \"All Selected Products\")",
              "",
              "var state_name = if(hasonevalue(Dim_Geography[State]), values(Dim_Geography[State]), ",
              "                    if([Count_GeoState] = [Count_GeoState_Total], \"All States\", ",
              "                        if([Count_GeoState] < 3, calculate(CONCATENATEX(values(Dim_Geography[State]), Dim_Geography[State], \"+\")),",
              "                        \"Selected \" & [Count_GeoState] & \" States\")))",
              "var geo_name = if(hasonevalue(Dim_Geography[Geography_Name]), values(Dim_Geography[Geography_Name]), \"Selected Areas\")",
              "",
              "var geo_title = if([Filter_GeographyName], geo_name, state_name)",
              "",
              "var banner_name = calculate(CONCATENATEX(values(Dim_Banner_Type[banner_type_display]), Dim_Banner_Type[banner_type_display], \"+\"))",
              "",
              "var market_name = if(hasonevalue(Dim_Market_Type[Market]), \" | \" & values(Dim_Market_Type[Market]) & \" Only\", \"\")",
              "",
              "var rank_name = if(hasonevalue(Dim_Product_Client_Top_Analysis[top_base]), values(Dim_Product_Client_Top_Analysis[top_base]), \"\") & \" Ranked by \" & ",
              "\t\t\t\t\tif(hasonevalue(AUX_Top_Select_Option[top_option]), values(AUX_Top_Select_Option[top_option]), \"\")",
              "",
              "var geo_type = selectedvalue(Dim_Geography_Type[Geography_Type], \"State\")",
              "",
              "var line_title =  if([Filter_Subsegment],",
              "                    name_subseg,",
              "                    if([Filter_Segment],",
              "                            name_segment,",
              "                            name_category))",
              "                                        ",
              "var rp_title =  \"\" & geo_type & \" | \" & [Current_Period_short] & \" | \" & measure_name & \" | \" & line_title  & \" | \" & geo_title & \" | \" & banner_name & \" Sales\" & market_name ",
              "var measure_used = \"Area Color Measure: \" & selectedvalue(AUX_LineChartMeasure[LineMeasure_Display], \"Product Sales\") & \" | \" & \"Elevation Measure: \" & selectedvalue(AUX_LineChartMeasure_2[LineMeasure_Display], \"NA\")",
              "var rp_Error = \"!! Click the Choropleth Map Sea Area to Clear Area Filter !!\"",
              "",
              "var no_market = ISBLANK([Sales_Market])                         ",
              "return rp_title & \" | \" & measure_used"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "skuPopup_Period_Title",
            "expression": "[Current_Period_long] & \" Top 10 SKUs: $|U|P\"",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "skuBarChart_Title",
            "expression": [
              "",
              "var period_name = if(HASONEVALUE('Dim_Period'[Period_Type]), values(Dim_Period[Period_Type]), \"RQTR\") ",
              "var period_name_long = \"Current Period: \" & [Current_Period_long] & \", Gth to \" & if(HASONEVALUE(AUX_Previous_Period[display]), values(AUX_Previous_Period[display])) & \" \" & period_name",
              "var measure_name = if(HASONEVALUE(Dim_Measure_Type[Measure]), values(Dim_Measure_Type[Display]), \"($)\")",
              "var name_sku = if(hasonevalue(Dim_Product_Client_Hierarchy[pack_name]), values(Dim_Product_Client_Hierarchy[pack_name]), \"Selected SKUs\")",
              "var name_l5 = if(hasonevalue(Dim_Product_Client_Hierarchy[prod_level_5]), values(Dim_Product_Client_Hierarchy[prod_level_5]), \"Selected \" & [Hierarchy_Prod_L5_Name])",
              "var name_l4 = if(hasonevalue(Dim_Product_Client_Hierarchy[prod_level_4]), values(Dim_Product_Client_Hierarchy[prod_level_4]), \"Selected \" & [Hierarchy_Prod_L4_Name])",
              "var name_l3 = if(hasonevalue(Dim_Product_Client_Hierarchy[prod_level_3]), values(Dim_Product_Client_Hierarchy[prod_level_3]), ",
              "                    if([Count_L3] = [Count_L3_Total], \"All \" & [Hierarchy_Prod_L3_Name], ",
              "                        if([Count_L3] < 3, calculate(CONCATENATEX(values(Dim_Product_Client_Hierarchy[prod_level_3]), Dim_Product_Client_Hierarchy[prod_level_3], \"+\")),",
              "                        \"Selected \" & [Count_L3] & \" \" & [Hierarchy_Prod_L3_Name])))",
              "var name_l2 = if(hasonevalue(Dim_Product_Client_Hierarchy[prod_level_2]), values(Dim_Product_Client_Hierarchy[prod_level_2]), ",
              "                    if([Count_L2] = [Count_L2_Total], \"All \" & [Hierarchy_Prod_L2_Name], ",
              "                        if([Count_L2] < 3, calculate(CONCATENATEX(values(Dim_Product_Client_Hierarchy[prod_level_2]), Dim_Product_Client_Hierarchy[prod_level_2], \"+\")),",
              "                        \"Selected \" & [Count_L2] & \" \" & [Hierarchy_Prod_L2_Name])))",
              "var name_l1 = if(hasonevalue(Dim_Product_Client_Hierarchy[prod_level_1]), values(Dim_Product_Client_Hierarchy[prod_level_1]), ",
              "                    if([Count_L1] = [Count_L1_Total], \"All \" & [Hierarchy_Prod_L1_Name], ",
              "                        if([Count_L1] < 3, calculate(CONCATENATEX(values(Dim_Product_Client_Hierarchy[prod_level_1]), Dim_Product_Client_Hierarchy[prod_level_1], \"+\")),",
              "                        \"Selected \" & [Count_L1] & \" \" & [Hierarchy_Prod_L1_Name])))",
              "",
              "var name_oth = if([Count_L1] = [Count_L1_Total], \"All \" & [Hierarchy_Prod_L1_Name], \"All Selected Products\")",
              "",
              "var state_name = if(hasonevalue(Dim_Outlet[cw_cluster_name]), values(Dim_Outlet[cw_cluster_name]),",
              "                    if(hasonevalue(Dim_State[State_Group]), values(Dim_State[State_Group]), ",
              "                    if([Count_State] = [Count_State_Total], \"All States\", ",
              "                        if([Count_State] < 3, calculate(CONCATENATEX(values(Dim_State[State_Group]), Dim_State[State_Group], \"+\")),",
              "                        \"Selected \" & [Count_State] & \" States\")))",
              "                    )",
              "",
              "var banner_name = calculate(CONCATENATEX(values(Dim_Banner_Type[banner_type_display]), Dim_Banner_Type[banner_type_display], \"+\"))",
              "",
              "var market_name = if(hasonevalue(Dim_Market_Type[Market]), values(Dim_Market_Type[Market]) & \" Only\", \"\")",
              "",
              "var cat_title =  if([Filter_Prod_L5],",
              "                            [Hierarchy_Prod_L5_Name],",
              "                            if([Filter_Prod_L4],",
              "                                [Hierarchy_Prod_L4_Name],",
              "                                if([Filter_Prod_L3],",
              "                                    [Hierarchy_Prod_L3_Name],",
              "                                    if([Filter_Prod_L2],",
              "                                        [Hierarchy_Prod_L2_Name],",
              "                                        if([Filter_Prod_L1],",
              "                                        [Hierarchy_Prod_L1_Name])))))",
              "",
              "var line_title =  if([Filter_SKUName],",
              "                    name_sku,",
              "                    if([Filter_Prod_L5],",
              "                            name_l5,",
              "                            if([Filter_Prod_L4],",
              "                                name_l4,",
              "                                if([Filter_Prod_L3],",
              "                                    name_l3,",
              "                                    if([Filter_Prod_L2],",
              "                                        name_l2,",
              "                                        if([Filter_Prod_L1],",
              "                                        name_l1, name_oth))))))",
              "                                        ",
              "return \"Value and Price by Period for \" & cat_title & \": \" & line_title & \" | \" & measure_name & \" | \" & \" | \" & state_name & \" | \" & banner_name & \" | \" & market_name"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "gauge_Title_Dist",
            "expression": [
              "\"Dist  #\" & ",
              "\" | \" & if(HASONEVALUE(Dim_Period[Period_Type]), values(Dim_Period[Period_Type]))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "gauge_Title_Dist_%",
            "expression": [
              "\"Dist %\" & ",
              "\" | \" & if(HASONEVALUE(Dim_Period[Period_Type]), values(Dim_Period[Period_Type]))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "gauge_Title_Dist_%_wtd",
            "expression": [
              "\"Wtd Dist %\" & ",
              "\" | \" & if(HASONEVALUE(Dim_Period[Period_Type]), values(Dim_Period[Period_Type]))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "kpiCard_Title_Dist_Chg",
            "expression": [
              "\"Dist  Change\" & ",
              "\" | \" & if(HASONEVALUE(Dim_Period[Period_Type]), values(Dim_Period[Period_Type]))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "kpiCard_Title_Dist_Tot",
            "expression": [
              "\"Total \" & ",
              "\" | \" & if(HASONEVALUE(Dim_Period[Period_Type]), values(Dim_Period[Period_Type]))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "kpiCard_Title_Dist_%_Chg",
            "expression": [
              "\"Dist % Change\" & ",
              "\" | \" & if(HASONEVALUE(Dim_Period[Period_Type]), values(Dim_Period[Period_Type]))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "Button_Title_Dist_Prod",
            "expression": "\"Prod View\"",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "Button_Title_Dist_Geo",
            "expression": "\"Geo View\"",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "skuLineChart_Title_Dist",
            "expression": [
              "",
              "var state_name = if([Count_State] =  [Count_State_Total], \"All States\",",
              "\t\t\t\t\tif([Count_State] < 4, CONCATENATEX(values(Dim_State[State_Group]), Dim_State[State_Group], \"+\"),",
              "\t\t\t\t\t\"Selected States\"))",
              "",
              "return \"Distribution Trend for \" & [Title_Prod_Level] & \" | \" & state_name"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "9a883657-3b18-49ae-98a2-ca61a7072346"
          },
          {
            "name": "LinkedQueryName",
            "value": "AUX_Text_Expression"
          },
          {
            "name": "PBI_QueryRelationships",
            "value": "{\"columnCount\":1,\"keyColumnNames\":[],\"queryRelationships\":[],\"columnIdentities\":[\"Section1/AUX_Text_Expression/Changed Type.{Text_Name,0}\"],\"ColumnCount\":1,\"KeyColumnNames\":[],\"ColumnIdentities\":[\"Section1/AUX_Text_Expression/Changed Type.{Text_Name,0}\"],\"RelationshipInfo\":[]}"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "AUX_Segment",
        "isHidden": true,
        "columns": [
          {
            "name": "Segment",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Segment",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Segment"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Type",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Type",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Type"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Order",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Order",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Order"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Display",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Display",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Display"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "X_Static_Min",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "X_Static_Min",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "X_Static_Min"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "X_Static_Max",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "X_Static_Max",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "X_Static_Max"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Y_Static_Min",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Y_Static_Min",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Y_Static_Min"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Y_Static_Max",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Y_Static_Max",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Y_Static_Max"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "AUX_Segment-c459929c-a6ad-4fa5-88cf-06c64b4d8f7c",
            "mode": "import",
            "source": {
              "type": "query",
              "query": "SELECT * FROM [AUX_Segment]",
              "dataSource": "9bad31b5-83d3-45fa-84b3-92285a6ec522"
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "bf21ae06-97aa-4ff9-b4b8-8a045274a698"
          },
          {
            "name": "LinkedQueryName",
            "value": "AUX_Segment"
          },
          {
            "name": "PBI_QueryRelationships",
            "value": "{\"columnCount\":8,\"keyColumnNames\":[],\"queryRelationships\":[],\"columnIdentities\":[\"Section1/AUX_Segment/Source.{Segment,0}\",\"Section1/AUX_Segment/Source.{Type,1}\",\"Section1/AUX_Segment/Source.{X_Static_Min,2}\",\"Section1/AUX_Segment/Source.{X_Static_Max,3}\",\"Section1/AUX_Segment/Source.{Y_Static_Min,4}\",\"Section1/AUX_Segment/Source.{Y_Static_Max,5}\",\"Section1/AUX_Segment/Source.{Order,6}\",\"Section1/AUX_Segment/Source.{Display,7}\"],\"ColumnCount\":8,\"KeyColumnNames\":[],\"ColumnIdentities\":[\"Section1/AUX_Segment/Source.{Segment,0}\",\"Section1/AUX_Segment/Source.{Type,1}\",\"Section1/AUX_Segment/Source.{X_Static_Min,2}\",\"Section1/AUX_Segment/Source.{X_Static_Max,3}\",\"Section1/AUX_Segment/Source.{Y_Static_Min,4}\",\"Section1/AUX_Segment/Source.{Y_Static_Max,5}\",\"Section1/AUX_Segment/Source.{Order,6}\",\"Section1/AUX_Segment/Source.{Display,7}\"],\"RelationshipInfo\":[]}"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "AUX_Top_Selection_Geo",
        "isHidden": true,
        "columns": [
          {
            "name": "Top",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Top",
            "sortByColumn": "Top_Value",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Top"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Top_Value",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Top_Value",
            "formatString": "0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Top_Value"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "AUX_Top_Selection_Geo-7b38dc3c-55cc-4cec-93c9-ac3ecfeb8d69",
            "mode": "import",
            "source": {
              "type": "query",
              "query": "SELECT * FROM [AUX_Top_Selection_Geo]",
              "dataSource": "6c452806-c5b7-464a-8b10-31238986b448"
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "666db002-ab45-432c-af3f-beb46ed19078"
          },
          {
            "name": "LinkedQueryName",
            "value": "AUX_Top_Selection_Geo"
          },
          {
            "name": "PBI_QueryRelationships",
            "value": "{\"columnCount\":2,\"keyColumnNames\":[],\"queryRelationships\":[],\"columnIdentities\":[\"Section1/AUX_Top_Selection_Geo/Source.{Top,0}\",\"Section1/AUX_Top_Selection_Geo/Changed Type.{Top_Value,1}\"],\"ColumnCount\":2,\"KeyColumnNames\":[],\"ColumnIdentities\":[\"Section1/AUX_Top_Selection_Geo/Source.{Top,0}\",\"Section1/AUX_Top_Selection_Geo/Changed Type.{Top_Value,1}\"],\"RelationshipInfo\":[]}"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "AUX_Top_Selection_Prod",
        "isHidden": true,
        "columns": [
          {
            "name": "Top",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Top",
            "sortByColumn": "Order",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Top"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Top_Value",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Top_Value",
            "formatString": "0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Top_Value"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Top_Type",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Top_Type",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Top_Type"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Order",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Order",
            "formatString": "0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Order"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "AUX_Top_Selection_Prod-e5c37fa8-8118-4ef0-a281-2b234c4dc9c4",
            "mode": "import",
            "source": {
              "type": "query",
              "query": "SELECT * FROM [AUX_Top_Selection_Prod]",
              "dataSource": "23f63ec5-51ef-4e6a-bc65-a7ddf500242b"
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "d322cbb8-62b2-495a-834f-53b13c3e1882"
          },
          {
            "name": "LinkedQueryName",
            "value": "AUX_Top_Selection_Prod"
          },
          {
            "name": "PBI_QueryRelationships",
            "value": "{\"columnCount\":4,\"keyColumnNames\":[],\"queryRelationships\":[],\"columnIdentities\":[\"Section1/AUX_Top_Selection_Prod/Source.{Top,0}\",\"Section1/AUX_Top_Selection_Prod/Changed Type.{Top_Value,1}\",\"Section1/AUX_Top_Selection_Prod/Source.{Top_Type,2}\",\"Section1/AUX_Top_Selection_Prod/Source.{Order,3}\"],\"ColumnCount\":4,\"KeyColumnNames\":[],\"ColumnIdentities\":[\"Section1/AUX_Top_Selection_Prod/Source.{Top,0}\",\"Section1/AUX_Top_Selection_Prod/Changed Type.{Top_Value,1}\",\"Section1/AUX_Top_Selection_Prod/Source.{Top_Type,2}\",\"Section1/AUX_Top_Selection_Prod/Source.{Order,3}\"],\"RelationshipInfo\":[]}"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Dim_Banner_Type",
        "columns": [
          {
            "name": "banner_id",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "banner_id",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "banner_id"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "banner_type",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "banner_type",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "banner_type"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Banner",
            "dataType": "string",
            "sourceColumn": "Banner",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Banner"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "banner_type_display",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "banner_type_display",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "banner_type_display"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Dim_Banner_Type-eff9600a-9b39-4e27-88a1-314e65f688c6",
            "mode": "import",
            "source": {
              "type": "query",
              "query": "SELECT * FROM [Dim_Banner_Type]",
              "dataSource": "04622af5-18a6-445d-ba0e-d2325f9932ca"
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "6b15659e-5380-4548-9c24-5a216b962c08"
          },
          {
            "name": "LinkedQueryName",
            "value": "Dim_Banner_Type"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_QueryRelationships",
            "value": "{\"columnCount\":4,\"keyColumnNames\":[],\"queryRelationships\":[],\"columnIdentities\":[\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Banner_Type.{banner_id,0}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Banner_Type.{banner_type,1}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Banner_Type.{Banner,2}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Banner_Type.{banner_type_display,3}\"],\"ColumnCount\":4,\"KeyColumnNames\":[],\"ColumnIdentities\":[\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Banner_Type.{banner_id,0}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Banner_Type.{banner_type,1}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Banner_Type.{Banner,2}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Banner_Type.{banner_type_display,3}\"],\"RelationshipInfo\":[]}"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Client",
        "isHidden": true,
        "columns": [
          {
            "name": "client_number",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "client_number",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "client_number"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "client_name",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "client_name",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "client_name"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "client_name_display",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "client_name_display",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "client_name_display"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "client_short_name",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "client_short_name",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "client_short_name"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "outlet_restriction",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "outlet_restriction",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "outlet_restriction"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "client_logo",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "client_logo",
            "dataCategory": "ImageUrl",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "client_logo"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "app_icon",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "app_icon",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "app_icon"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "daily_app_icon",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "daily_app_icon",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "daily_app_icon"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Client-13d98329-7c6f-4a03-adde-664c57b473f4",
            "mode": "import",
            "source": {
              "type": "query",
              "query": "SELECT * FROM [Client]",
              "dataSource": "14a284e2-459f-4fcb-8d9d-51aaf37fdb0c"
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "55e8cd6f-5749-47a4-9cda-a59a18c518ff"
          },
          {
            "name": "LinkedQueryName",
            "value": "Client"
          },
          {
            "name": "PBI_QueryRelationships",
            "value": "{\"columnCount\":8,\"keyColumnNames\":[],\"queryRelationships\":[],\"columnIdentities\":[\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Client_Demo.{client_number,0}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Client_Demo.{client_name,1}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Client_Demo.{name_display,2}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Client_Demo.{client_short_name,3}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Client_Demo.{outlet_restriction,4}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Client_Demo.{client_logo,5}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Client_Demo.{app_icon,6}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Client_Demo.{app_icon_daily,7}\"],\"ColumnCount\":8,\"KeyColumnNames\":[],\"ColumnIdentities\":[\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Client_Demo.{client_number,0}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Client_Demo.{client_name,1}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Client_Demo.{name_display,2}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Client_Demo.{client_short_name,3}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Client_Demo.{outlet_restriction,4}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Client_Demo.{client_logo,5}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Client_Demo.{app_icon,6}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Client_Demo.{app_icon_daily,7}\"],\"RelationshipInfo\":[]}"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Dim_Period",
        "columns": [
          {
            "name": "period_key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "period_key",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "period_key"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Period_Type",
            "dataType": "string",
            "sourceColumn": "Period_Type",
            "sortByColumn": "period_type_order",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Period_Type"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Period_Name",
            "dataType": "string",
            "sourceColumn": "Period_Name",
            "sortByColumn": "date_code",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Period_Name"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Period_Long_Name",
            "dataType": "string",
            "sourceColumn": "Period_Long_Name",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Period_Long_Name"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Period_Year",
            "dataType": "int64",
            "sourceColumn": "Period_Year",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Period_Year"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "period_code",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "period_code",
            "formatString": "0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "period_code"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "period_code_name",
            "dataType": "string",
            "sourceColumn": "period_code_name",
            "sortByColumn": "period_code",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "period_code_name"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "date_code",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "date_code",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "date_code"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "period_start",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "period_start",
            "formatString": "General Date",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"3081\" Group=\"GeneralDateTimeLong\" FormatString=\"G\" /></DateTimes></Format>"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "DateTime#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "period_start"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "period_end",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "period_end",
            "formatString": "General Date",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"3081\" Group=\"GeneralDateTimeLong\" FormatString=\"G\" /></DateTimes></Format>"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "DateTime#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "period_end"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "MAT_year",
            "dataType": "int64",
            "sourceColumn": "MAT_year",
            "formatString": "0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "MAT_year"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "period_type_order",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "period_type_order",
            "formatString": "0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "period_type_order"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "period_type_base",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "period_type_base",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "period_type_base"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "period_seq",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "period_seq",
            "formatString": "0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "period_seq"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "period_num",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "period_num",
            "formatString": "0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "period_num"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "year_display",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "year_display",
            "formatString": "0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "year_display"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "weekdatename",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "weekdatename",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "weekdatename"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "weekdaystart",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "weekdaystart",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "weekdaystart"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "weekdaystartid",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "weekdaystartid",
            "formatString": "0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "weekdaystartid"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "weekdatenumber",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "weekdatenumber",
            "formatString": "0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "weekdatenumber"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "currentweekday",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "currentweekday",
            "formatString": "0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "currentweekday"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Month_Order",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Month_Order",
            "formatString": "0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Month_Order"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "period_start_day",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "period_start_day",
            "formatString": "General Date",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"3081\" Group=\"GeneralDateTimeLong\" FormatString=\"G\" /></DateTimes></Format>"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "DateTime#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "period_start_day"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Period_Month_Name",
            "dataType": "string",
            "sourceColumn": "Period_Month_Name",
            "sortByColumn": "Period_Month_Name_Order",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Period_Month_Name"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Period_Month_Name_Order",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Period_Month_Name_Order",
            "formatString": "0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Period_Month_Name_Order"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Period_Name_Display",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "if('Dim_Period'[Period_Month_Name_Order] = 1, \"Current Month\", 'Dim_Period'[Period_Month_Name])",
            "sortByColumn": "Period_Month_Name_Order",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Dim_Period-380fc085-5f3f-451d-8a2b-7b54752e290c",
            "mode": "import",
            "source": {
              "type": "query",
              "query": "SELECT * FROM [Dim_Period]",
              "dataSource": "32ab8cd3-e577-442b-9f0f-a18c0cb0505a"
            }
          }
        ],
        "measures": [
          {
            "name": "Home_Date_Period_1",
            "expression": [
              "",
              "",
              "var month_start = calculate(min('Dim_Period'[period_start]), filter(All(Dim_Period), 'Dim_Period'[Period_Type] = \"MTH\"))",
              "var month_end = calculate(max('Dim_Period'[period_start]), filter(All(Dim_Period), 'Dim_Period'[Period_Type] = \"MTH\"))",
              "var week_start = calculate(min('Dim_Period'[period_start]), 'Dim_Period'[Period_Type] = \"WEEK\")",
              "var week_end = calculate(max('Dim_Period'[period_start]), 'Dim_Period'[Period_Type] = \"WEEK\")",
              "var day_start = calculate(min('Dim_Period'[period_start]), 'Dim_Period'[Period_Type] = \"DAY\")",
              "var day_end = calculate(max('Dim_Period'[period_start]), 'Dim_Period'[Period_Type] = \"DAY\")",
              "",
              "",
              "var month_1 = calculate(min('Dim_Period'[Period_Name]), 'Dim_Period'[Period_Type] = \"MTH\", 'Dim_Period'[period_start] = month_start)",
              "var month_2 = calculate(min('Dim_Period'[Period_Name]), 'Dim_Period'[Period_Type] = \"MTH\", 'Dim_Period'[period_start] = month_end)",
              "var week_1 = calculate(min('Dim_Period'[Period_Name]), 'Dim_Period'[Period_Type] = \"WEEK\", 'Dim_Period'[period_start] = week_start)",
              "var week_2 = calculate(min('Dim_Period'[Period_Name]), 'Dim_Period'[Period_Type] = \"WEEK\", 'Dim_Period'[period_start] = week_end)",
              "var day_1 = calculate(min('Dim_Period'[Period_Name]), 'Dim_Period'[Period_Type] = \"DAY\", 'Dim_Period'[period_start] = day_start)",
              "var day_2 = calculate(min('Dim_Period'[Period_Name]), 'Dim_Period'[Period_Type] = \"DAY\", 'Dim_Period'[period_start] = day_end)",
              "",
              "var home_t_mw = \"Date Period: Monthly = \" & month_1 & \"  \" & month_2 & \" | \" & \"Weekly = \" & week_1 & \"  \" & week_2",
              "var home_t_d = \"Date Period: \" & day_1 & \"-\" & year(day_start) & \"  \" & day_2 & \"-\" & year(day_end)",
              "",
              "return if(values('Dim_Period'[period_type_base]) = \"DAY\" || values('Dim_Period'[period_type_base]) = \"WTD\", home_t_d, home_t_mw)"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "Filter_PeriodDisplay_Original",
            "expression": [
              "",
              "var type_selected = values('Dim_Period_Type'[Period_Type])",
              "",
              "return if(values(Dim_Period[Period_Type]) in type_selected, 1, 0)"
            ],
            "formatString": "0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "period_to_display",
            "expression": [
              "if(values('Dim_Period'[period_type_base]) = \"WTD\", if(values('Dim_Period'[period_num]) < 12, 1, 0),  if(values('Dim_Period'[period_num]) < 25, 1, 0))",
              ""
            ],
            "formatString": "0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "f7951ae8-dc84-4496-98ea-4d16723e6db6"
          },
          {
            "name": "LinkedQueryName",
            "value": "Dim_Period"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_QueryRelationships",
            "value": "{\"columnCount\":25,\"keyColumnNames\":[],\"queryRelationships\":[],\"columnIdentities\":[\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_MthWk.{period_key,0}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_MthWk.{period_type,1}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_MthWk.{period_type_order,2}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_MthWk.{period_name,3}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_MthWk.{period_long_name,4}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_MthWk.{period_year,5}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_MthWk.{period_code,6}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_MthWk.{period_code_name,7}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_MthWk.{date_code,8}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_MthWk.{period_start,9}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_MthWk.{period_end,10}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_MthWk.{MAT_year,11}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_MthWk.{period_type_base,12}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_MthWk.{period_seq,13}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_MthWk.{period_num,14}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_MthWk.{year_display,15}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_MthWk.{weekdatename,16}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_MthWk.{weekdaystart,17}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_MthWk.{weekdaystartid,18}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_MthWk.{weekdatenumber,19}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_MthWk.{currentweekday,20}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_MthWk.{Month_Order,21}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_MthWk.{period_start_day,22}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_MthWk.{Period_Month_Name,23}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_MthWk.{Period_Month_Name_Order,24}\"],\"ColumnCount\":25,\"KeyColumnNames\":[],\"ColumnIdentities\":[\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_MthWk.{period_key,0}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_MthWk.{period_type,1}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_MthWk.{period_type_order,2}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_MthWk.{period_name,3}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_MthWk.{period_long_name,4}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_MthWk.{period_year,5}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_MthWk.{period_code,6}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_MthWk.{period_code_name,7}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_MthWk.{date_code,8}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_MthWk.{period_start,9}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_MthWk.{period_end,10}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_MthWk.{MAT_year,11}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_MthWk.{period_type_base,12}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_MthWk.{period_seq,13}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_MthWk.{period_num,14}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_MthWk.{year_display,15}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_MthWk.{weekdatename,16}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_MthWk.{weekdaystart,17}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_MthWk.{weekdaystartid,18}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_MthWk.{weekdatenumber,19}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_MthWk.{currentweekday,20}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_MthWk.{Month_Order,21}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_MthWk.{period_start_day,22}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_MthWk.{Period_Month_Name,23}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_MthWk.{Period_Month_Name_Order,24}\"],\"RelationshipInfo\":[]}"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Dim_Period_Base",
        "isHidden": true,
        "columns": [
          {
            "name": "period_key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "period_key",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "period_key"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "period_type",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "period_type",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "period_type"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "period_start",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "period_start",
            "formatString": "General Date",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"3081\" Group=\"GeneralDateTimeLong\" FormatString=\"G\" /></DateTimes></Format>"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "DateTime#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "period_start"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "period_number",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "period_number",
            "formatString": "0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "period_number"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Dim_Period_Base-baf4c2ca-bb0e-4e6e-8031-f45a99a95605",
            "mode": "import",
            "source": {
              "type": "query",
              "query": "SELECT * FROM [Dim_Period_Base]",
              "dataSource": "384c05f1-f56f-4e84-8299-5341c1a2fb5a"
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "414a8853-cae6-403d-ab01-68cd256dbaf6"
          },
          {
            "name": "LinkedQueryName",
            "value": "Dim_Period_Base"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_QueryRelationships",
            "value": "{\"columnCount\":4,\"keyColumnNames\":[],\"queryRelationships\":[],\"columnIdentities\":[\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_Base_MthWk.{period_key,0}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_Base_MthWk.{period_type,1}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_Base_MthWk.{period_start,2}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_Base_MthWk.{period_number,3}\"],\"ColumnCount\":4,\"KeyColumnNames\":[],\"ColumnIdentities\":[\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_Base_MthWk.{period_key,0}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_Base_MthWk.{period_type,1}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_Base_MthWk.{period_start,2}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_Base_MthWk.{period_number,3}\"],\"RelationshipInfo\":[]}"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Dim_Product_General",
        "isHidden": true,
        "columns": [
          {
            "name": "cw_pack_key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "cw_pack_key",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "cw_pack_key"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "pack_key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "pack_key",
            "formatString": "0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "pack_key"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "pack_code",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "pack_code",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "pack_code"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "generic_flag_code",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "generic_flag_code",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "generic_flag_code"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "generic_flag_name",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "generic_flag_name",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "generic_flag_name"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "cw_pack_short_name",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "cw_pack_short_name",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "cw_pack_short_name"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "iqvia_pack_name",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "iqvia_pack_name",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "iqvia_pack_name"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "cw_manufacturer",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "cw_manufacturer",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "cw_manufacturer"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "manufacturer",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "manufacturer",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "manufacturer"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "private_label_yn",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "private_label_yn",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "private_label_yn"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "private_label_name",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "private_label_name",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "private_label_name"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Dim_Product_General-36258dc2-3c95-47a3-860f-983128922dba",
            "mode": "import",
            "source": {
              "type": "query",
              "query": "SELECT * FROM [Dim_Product_General]",
              "dataSource": "2c89ead8-0a1c-4420-9c2e-55166db2dba6"
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "5ee54331-cb68-4305-ba72-86944fd46f97"
          },
          {
            "name": "LinkedQueryName",
            "value": "Dim_Product_General"
          },
          {
            "name": "PBI_QueryRelationships",
            "value": "{\"columnCount\":11,\"keyColumnNames\":[],\"queryRelationships\":[],\"columnIdentities\":[\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Product.{cw_pack_key,0}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Product.{pack_key,1}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Product.{pack_code,2}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Product.{cw_pack_short_name,3}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Product.{iqvia_pack_name,4}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Product.{cw_manufacturer,5}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Product.{manufacturer,6}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Product.{private_label_yn,7}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Product.{private_label_name,8}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Product.{generic_flag_code,9}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Product.{generic_flag_name,10}\"],\"ColumnCount\":11,\"KeyColumnNames\":[],\"ColumnIdentities\":[\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Product.{cw_pack_key,0}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Product.{pack_key,1}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Product.{pack_code,2}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Product.{cw_pack_short_name,3}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Product.{iqvia_pack_name,4}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Product.{cw_manufacturer,5}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Product.{manufacturer,6}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Product.{private_label_yn,7}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Product.{private_label_name,8}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Product.{generic_flag_code,9}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Product.{generic_flag_name,10}\"],\"RelationshipInfo\":[]}"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Fact_Outlet_Category_Sales",
        "isHidden": true,
        "columns": [
          {
            "name": "period_key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "period_key",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "period_key"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "cw_outlet_key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "cw_outlet_key",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "cw_outlet_key"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "client_category_id",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "client_category_id",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "client_category_id"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "product_ownership_id",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "product_ownership_id",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "product_ownership_id"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "market_id",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "market_id",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "market_id"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "measure_id",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "measure_id",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "measure_id"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "sales",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "sales",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "sales"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Fact_Outlet_Category_Sales-cc3a2102-c5a9-4890-ac51-13ec3ece5e56",
            "mode": "import",
            "source": {
              "type": "query",
              "query": "SELECT * FROM [Fact_Outlet_Category_Sales]",
              "dataSource": "f5bd4fb7-feb9-45cd-b2f4-8aa6dc5dca3c"
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "abaa1ebb-31cc-40b2-8544-989f0c7e61dd"
          },
          {
            "name": "LinkedQueryName",
            "value": "Fact_Outlet_Category_Sales"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_QueryRelationships",
            "value": "{\"columnCount\":7,\"keyColumnNames\":[],\"queryRelationships\":[],\"columnIdentities\":[\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Fact_Outlet_Category_Sales_MthWk.{period_key,0}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Fact_Outlet_Category_Sales_MthWk.{cw_outlet_key,1}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Fact_Outlet_Category_Sales_MthWk.{client_category_id,2}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Fact_Outlet_Category_Sales_MthWk.{product_ownership_id,3}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Fact_Outlet_Category_Sales_MthWk.{market_id,4}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Fact_Outlet_Category_Sales_MthWk.{measure_id,5}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Fact_Outlet_Category_Sales_MthWk.{sales,6}\"],\"ColumnCount\":7,\"KeyColumnNames\":[],\"ColumnIdentities\":[\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Fact_Outlet_Category_Sales_MthWk.{period_key,0}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Fact_Outlet_Category_Sales_MthWk.{cw_outlet_key,1}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Fact_Outlet_Category_Sales_MthWk.{client_category_id,2}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Fact_Outlet_Category_Sales_MthWk.{product_ownership_id,3}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Fact_Outlet_Category_Sales_MthWk.{market_id,4}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Fact_Outlet_Category_Sales_MthWk.{measure_id,5}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Fact_Outlet_Category_Sales_MthWk.{sales,6}\"],\"RelationshipInfo\":[]}"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Fact_SKU_State_Sales",
        "isHidden": true,
        "columns": [
          {
            "name": "period_key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "period_key",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "period_key"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "cw_pack_key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "cw_pack_key",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "cw_pack_key"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "state_key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "state_key",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "state_key"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "measure_id",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "measure_id",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "measure_id"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "market_id",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "market_id",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "market_id"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "banner_id",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "banner_id",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "banner_id"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "sales",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "sales",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "sales"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Fact_SKU_State_Sales-6d69a035-5bde-4c0f-9ecb-347492422e29",
            "mode": "import",
            "source": {
              "type": "query",
              "query": "SELECT * FROM [Fact_SKU_State_Sales]",
              "dataSource": "25dc2cb6-00b3-43ba-b06e-a63fab08d48a"
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "d4083ff1-b85a-4d3b-bb23-24ed810d41d4"
          },
          {
            "name": "LinkedQueryName",
            "value": "Fact_SKU_State_Sales"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_QueryRelationships",
            "value": "{\"columnCount\":7,\"keyColumnNames\":[],\"queryRelationships\":[],\"columnIdentities\":[\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Fact_SKU_State_Sales_MthWk.{period_key,0}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Fact_SKU_State_Sales_MthWk.{cw_pack_key,1}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Fact_SKU_State_Sales_MthWk.{state_key,2}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Fact_SKU_State_Sales_MthWk.{measure_id,3}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Fact_SKU_State_Sales_MthWk.{market_id,4}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Fact_SKU_State_Sales_MthWk.{banner_id,5}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Fact_SKU_State_Sales_MthWk.{sales,6}\"],\"ColumnCount\":7,\"KeyColumnNames\":[],\"ColumnIdentities\":[\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Fact_SKU_State_Sales_MthWk.{period_key,0}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Fact_SKU_State_Sales_MthWk.{cw_pack_key,1}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Fact_SKU_State_Sales_MthWk.{state_key,2}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Fact_SKU_State_Sales_MthWk.{measure_id,3}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Fact_SKU_State_Sales_MthWk.{market_id,4}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Fact_SKU_State_Sales_MthWk.{banner_id,5}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Fact_SKU_State_Sales_MthWk.{sales,6}\"],\"RelationshipInfo\":[]}"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Dim_Market_Type",
        "columns": [
          {
            "name": "market_id",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "market_id",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "market_id"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "market_type",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "market_type",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "market_type"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Market",
            "dataType": "string",
            "sourceColumn": "Market",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Market"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Dim_Market_Type-f4be8491-e6be-4134-8fc0-7a765dc67a76",
            "mode": "import",
            "source": {
              "type": "query",
              "query": "SELECT * FROM [Dim_Market_Type]",
              "dataSource": "a7ebfbe3-89fd-41a9-b8e2-50eafb23e8db"
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "972071d5-4d3c-41d3-8055-40fe6b07dcc9"
          },
          {
            "name": "LinkedQueryName",
            "value": "Dim_Market_Type"
          },
          {
            "name": "PBI_QueryRelationships",
            "value": "{\"columnCount\":3,\"keyColumnNames\":[],\"queryRelationships\":[],\"columnIdentities\":[\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Market_Type.{market_id,0}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Market_Type.{market_type,1}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Market_Type.{Market,2}\"],\"ColumnCount\":3,\"KeyColumnNames\":[],\"ColumnIdentities\":[\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Market_Type.{market_id,0}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Market_Type.{market_type,1}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Market_Type.{Market,2}\"],\"RelationshipInfo\":[]}"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Dim_Measure_Type",
        "columns": [
          {
            "name": "measure_id",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "measure_id",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "measure_id"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "measure_type",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "measure_type",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "measure_type"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Measure",
            "dataType": "string",
            "sourceColumn": "Measure",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Measure"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "display",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "display",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "display"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Dim_Measure_Type-5f81f720-11a6-4723-a570-5272e7f739fb",
            "mode": "import",
            "source": {
              "type": "query",
              "query": "SELECT * FROM [Dim_Measure_Type]",
              "dataSource": "eecee072-1a97-49ff-b70a-3bb40031337e"
            }
          }
        ],
        "measures": [
          {
            "name": "SelectedMeasure_1",
            "expression": "if(HASONEVALUE('Dim_Measure_Type'[Measure]),VALUES('Dim_Measure_Type'[Measure]),\"Amount\")",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "727adfd2-d55a-4db9-ab53-8815cbacf443"
          },
          {
            "name": "LinkedQueryName",
            "value": "Dim_Measure_Type"
          },
          {
            "name": "PBI_QueryRelationships",
            "value": "{\"columnCount\":4,\"keyColumnNames\":[],\"queryRelationships\":[],\"columnIdentities\":[\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Measure_Type.{measure_id,0}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Measure_Type.{measure_type,1}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Measure_Type.{Measure,2}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Measure_Type.{Display,3}\"],\"ColumnCount\":4,\"KeyColumnNames\":[],\"ColumnIdentities\":[\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Measure_Type.{measure_id,0}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Measure_Type.{measure_type,1}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Measure_Type.{Measure,2}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Measure_Type.{Display,3}\"],\"RelationshipInfo\":[]}"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Dim_Outlet",
        "isHidden": true,
        "columns": [
          {
            "name": "cw_outlet_key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "cw_outlet_key",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "cw_outlet_key"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "cw_outlet_code",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "cw_outlet_code",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "cw_outlet_code"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "cw_outlet_name",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "cw_outlet_name",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "cw_outlet_name"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "iqvia_outlet_name",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "iqvia_outlet_name",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "iqvia_outlet_name"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "cw_cluster_code",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "cw_cluster_code",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "cw_cluster_code"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "cw_cluster_name",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "cw_cluster_name",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "cw_cluster_name"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "outlet_address",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "outlet_address",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "outlet_address"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "outlet_suburb",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "outlet_suburb",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "outlet_suburb"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "outlet_postcode",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "outlet_postcode",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "outlet_postcode"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "outlet_state",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "outlet_state",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "outlet_state"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "outlet_phone",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "outlet_phone",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "outlet_phone"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Banner_Name",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Banner_Name",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Banner_Name"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "brick_code",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "brick_code",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "brick_code"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "brick_name",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "brick_name",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "brick_name"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "latitude",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "latitude",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Double#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "latitude"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "longitude",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "longitude",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Double#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "longitude"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "outlet_key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "outlet_key",
            "formatString": "0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "outlet_key"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "eid",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "eid",
            "formatString": "0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "eid"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Remoteness",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Remoteness",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Remoteness"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Remoteness_Class",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Remoteness_Class",
            "formatString": "0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Remoteness_Class"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "SUA_NAME",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "SUA_NAME",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "SUA_NAME"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "GCCSA_CODE",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "GCCSA_CODE",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "GCCSA_CODE"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "GCCSA_NAME",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "GCCSA_NAME",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "GCCSA_NAME"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "state_key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "state_key",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "state_key"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "lga_name",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "lga_name",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "lga_name"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "State_Name",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "State_Name",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "State_Name"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "date_store_open",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "date_store_open",
            "formatString": "General Date",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"3081\" Group=\"GeneralDateTimeLong\" FormatString=\"G\" /></DateTimes></Format>"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "DateTime#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "date_store_open"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "date_store_close",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "date_store_close",
            "formatString": "General Date",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"3081\" Group=\"GeneralDateTimeLong\" FormatString=\"G\" /></DateTimes></Format>"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "DateTime#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "date_store_close"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Dim_Outlet-f43f44b5-c774-40e0-979f-4fba98e8ecc1",
            "mode": "import",
            "source": {
              "type": "query",
              "query": "SELECT * FROM [Dim_Outlet]",
              "dataSource": "f01f39a5-af11-4eae-8334-04f2359b1600"
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "eab30a05-7954-4978-833f-92f30b93c8b8"
          },
          {
            "name": "LinkedQueryName",
            "value": "Dim_Outlet"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_QueryRelationships",
            "value": "{\"columnCount\":28,\"keyColumnNames\":[],\"queryRelationships\":[],\"columnIdentities\":[\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Outlet.{cw_outlet_key,0}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Outlet.{cw_outlet_code,1}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Outlet.{cw_outlet_name,2}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Outlet.{iqvia_outlet_name,3}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Outlet.{cw_cluster_code,4}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Outlet.{cw_cluster_name,5}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Outlet.{outlet_address,6}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Outlet.{outlet_suburb,7}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Outlet.{outlet_postcode,8}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Outlet.{outlet_state,9}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Outlet.{outlet_phone,10}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Outlet.{banner_group_name,11}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Outlet.{brick_code,12}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Outlet.{brick_name,13}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Outlet.{latitude,14}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Outlet.{longitude,15}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Outlet.{outlet_key,16}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Outlet.{eid,17}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Outlet.{Remoteness,18}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Outlet.{Remoteness_Class,19}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Outlet.{lga_name,20}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Outlet.{SUA_NAME,21}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Outlet.{GCCSA_CODE,22}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Outlet.{GCCSA_NAME,23}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Outlet.{State_Name,24}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Outlet.{date_store_open,25}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Outlet.{date_store_close,26}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Outlet.{state_key,27}\"],\"ColumnCount\":28,\"KeyColumnNames\":[],\"ColumnIdentities\":[\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Outlet.{cw_outlet_key,0}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Outlet.{cw_outlet_code,1}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Outlet.{cw_outlet_name,2}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Outlet.{iqvia_outlet_name,3}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Outlet.{cw_cluster_code,4}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Outlet.{cw_cluster_name,5}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Outlet.{outlet_address,6}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Outlet.{outlet_suburb,7}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Outlet.{outlet_postcode,8}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Outlet.{outlet_state,9}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Outlet.{outlet_phone,10}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Outlet.{banner_group_name,11}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Outlet.{brick_code,12}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Outlet.{brick_name,13}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Outlet.{latitude,14}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Outlet.{longitude,15}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Outlet.{outlet_key,16}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Outlet.{eid,17}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Outlet.{Remoteness,18}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Outlet.{Remoteness_Class,19}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Outlet.{lga_name,20}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Outlet.{SUA_NAME,21}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Outlet.{GCCSA_CODE,22}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Outlet.{GCCSA_NAME,23}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Outlet.{State_Name,24}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Outlet.{date_store_open,25}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Outlet.{date_store_close,26}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Outlet.{state_key,27}\"],\"RelationshipInfo\":[]}"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Dim_Product_Ownership",
        "columns": [
          {
            "name": "product_ownership_id",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "product_ownership_id",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "product_ownership_id"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Product_Ownership",
            "dataType": "string",
            "sourceColumn": "Product_Ownership",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Product_Ownership"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Dim_Product_Ownership-a4fb681a-ef8f-4aa2-982f-159b566a33c1",
            "mode": "import",
            "source": {
              "type": "query",
              "query": "SELECT * FROM [Dim_Product_Ownership]",
              "dataSource": "d3384ea3-0a95-4841-8d87-adfe6d53cffd"
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "b4bd2666-d11e-4168-a66f-6b67fe94b054"
          },
          {
            "name": "LinkedQueryName",
            "value": "Dim_Product_Ownership"
          },
          {
            "name": "PBI_QueryRelationships",
            "value": "{\"columnCount\":2,\"keyColumnNames\":[],\"queryRelationships\":[],\"columnIdentities\":[\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Product_Ownership.{product_ownership_id,0}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Product_Ownership.{product_ownership,1}\"],\"ColumnCount\":2,\"KeyColumnNames\":[],\"ColumnIdentities\":[\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Product_Ownership.{product_ownership_id,0}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Product_Ownership.{product_ownership,1}\"],\"RelationshipInfo\":[]}"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Dim_State",
        "columns": [
          {
            "name": "state_key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "state_key",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "state_key"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "State_Group",
            "dataType": "string",
            "sourceColumn": "State_Group",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "State_Group"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "state_group_name",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "state_group_name",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "state_group_name"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "state_total",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "state_total",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "state_total"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Dim_State-1fbddbaa-3b2a-46c8-b9de-d2b37f0d5630",
            "mode": "import",
            "source": {
              "type": "query",
              "query": "SELECT * FROM [Dim_State]",
              "dataSource": "57ce0950-4485-4e53-8bdd-071427329adb"
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "1d5a5bbe-33e5-41ad-abe1-ce33d3b60097"
          },
          {
            "name": "LinkedQueryName",
            "value": "Dim_State"
          },
          {
            "name": "PBI_QueryRelationships",
            "value": "{\"columnCount\":4,\"keyColumnNames\":[],\"queryRelationships\":[],\"columnIdentities\":[\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_State.{state_key,0}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_State.{state_code,1}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_State.{state_name,2}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_State.{state_total,3}\"],\"ColumnCount\":4,\"KeyColumnNames\":[],\"ColumnIdentities\":[\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_State.{state_key,0}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_State.{state_code,1}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_State.{state_name,2}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_State.{state_total,3}\"],\"RelationshipInfo\":[]}"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Fact_Sales_Metrics_SKU",
        "isHidden": true,
        "columns": [
          {
            "name": "Metrics",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Metrics",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Metrics"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Fact_Sales_Metrics_SKU-e74dd556-098f-4695-a2cd-2ba2a473190d",
            "mode": "import",
            "source": {
              "type": "query",
              "query": "SELECT * FROM [Fact_Sales_Metrics_SKU]",
              "dataSource": "9a00f900-5de8-4eb8-9cfb-2d9907ecac10"
            }
          }
        ],
        "measures": [
          {
            "name": "Sales_SKU_Base",
            "expression": "if(countrows('Fact_SKU_State_Sales') > 0, calculate(sum('Fact_SKU_State_Sales'[sales]) / 100))",
            "formatString": "0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Sales_SKU_Period",
            "expression": [
              "",
              "var period_base_type = SELECTEDVALUE('Dim_Period'[period_type_base], \"MTH\")",
              "",
              "return if(period_base_type = \"WTD\", [Sales_SKU_Period_CTD], [Sales_SKU_Period_Base])"
            ],
            "formatString": "#,0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" ThousandSeparator=\"True\" />"
              }
            ]
          },
          {
            "name": "Sales_SKU_Product_Own",
            "expression": "calculate([Sales_SKU_Period], 'Dim_Product_Ownership'[Product_Ownership] = \"Own Product\")",
            "formatString": "#,0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" ThousandSeparator=\"True\" />"
              }
            ]
          },
          {
            "name": "MS_SKU_Product",
            "expression": "DIVIDE([Sales_SKU_Product], [Sales_SKU_Market])",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Percentage\" Accuracy=\"2\" />"
              }
            ]
          },
          {
            "name": "Sales_SKU_Competitor",
            "expression": "if([Sales_SKU_Product_Own] > 0,  calculate([Sales_SKU_Period], 'Dim_Product_Ownership'[Product_Ownership] = \"Competitor\"))",
            "formatString": "#,0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" ThousandSeparator=\"True\" />"
              }
            ]
          },
          {
            "name": "Sales_SKU_Market_Parent",
            "expression": [
              "",
              "var market_l5 = if(countrows('Fact_SKU_State_Sales') > 0, calculate([Sales_SKU_Period], All('Dim_Product_Client_Hierarchy'[prod_level_5])))",
              "var market_l4 = if(countrows('Fact_SKU_State_Sales') > 0, calculate([Sales_SKU_Period], All('Dim_Product_Client_Hierarchy'[prod_level_4])))",
              "var market_l3 = if(countrows('Fact_SKU_State_Sales') > 0, calculate([Sales_SKU_Period], All('Dim_Product_Client_Hierarchy'[prod_level_3])))",
              "var market_l2 = if(countrows('Fact_SKU_State_Sales') > 0, calculate([Sales_SKU_Period], All('Dim_Product_Client_Hierarchy'[prod_level_2])))",
              "var market_l1 = if(countrows('Fact_SKU_State_Sales') > 0, calculate([Sales_SKU_Period], All('Dim_Product_Client_Hierarchy'[prod_level_1])))",
              "var market_oth = if(countrows('Fact_SKU_State_Sales') > 0, calculate([Sales_SKU_Period], ALLSELECTED('Dim_Product_Client_Hierarchy')))",
              "",
              "var market =  if([Filter_SKUName],",
              "                    [Sales_SKU_Market_Pack],",
              "                    if([Filter_Prod_L5],",
              "                            market_l5,",
              "                            if([Filter_Prod_L4],",
              "                                market_l4,",
              "                                if([Filter_Prod_L3],",
              "                                    market_l3,",
              "                                    if([Filter_Prod_L2],",
              "                                        market_l2,",
              "                                        if([Filter_Prod_L1],",
              "                                        market_l1, market_oth))))))",
              "                                        ",
              "return market",
              ""
            ],
            "formatString": "#,0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" ThousandSeparator=\"True\" />"
              }
            ]
          },
          {
            "name": "MS_SKU_Parent",
            "expression": "DIVIDE([Sales_SKU_Product], [Sales_SKU_Market_Parent])",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Percentage\" Accuracy=\"2\" />"
              }
            ]
          },
          {
            "name": "Sales_SKU_Product",
            "expression": [
              "if([Filter_SKUName],",
              "\t\t\t[Sales_SKU_Period],",
              "\t\t\tif(and(or([Filter_Prod_L2], [Filter_Prod_L3]), or([Hierarchy_Prod_L2_Name] in {\"Manufacturer\", \"Ingredient\", \"Brand\", \"Subbrand\"}, [Hierarchy_Prod_L3_Name] in {\"Manufacturer\", \"Ingredient\", \"Brand\", \"Subbrand\"})),",
              "\t\t\t[Sales_SKU_Period],",
              "\t\t\t[Sales_SKU_Product_Own]))"
            ],
            "formatString": "#,0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" ThousandSeparator=\"True\" />"
              }
            ]
          },
          {
            "name": "Sales_SKU_Market_Category",
            "expression": [
              "",
              "var hier_id = Calculate(values(Dim_Hierarchy_Name_Product[hierarchy_id]), Dim_Hierarchy_Name_Product[hierarchy_name] = values(Dim_Hierarchy_Name_Product[hierarchy_name]))",
              "var prod_l1_selected = values('Dim_Product_Client_Hierarchy'[prod_level_1])",
              "",
              "return calculate([Sales_SKU_Period], filter(all('Dim_Product_Client_Hierarchy'), 'Dim_Product_Client_Hierarchy'[prod_level_1] in prod_l1_selected && 'Dim_Product_Client_Hierarchy'[hierarchy_id] = hier_id))"
            ],
            "formatString": "#,0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" ThousandSeparator=\"True\" />"
              }
            ]
          },
          {
            "name": "MS_SKU_Category",
            "expression": "DIVIDE([Sales_SKU_Product], [Sales_SKU_Market_Category])",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Percentage\" Accuracy=\"2\" />"
              }
            ]
          },
          {
            "name": "Sales_SKU_Market",
            "expression": [
              "",
              "var market_sku = if([Filter_SKUName], [Sales_SKU_Market_Pack],",
              "                        if(and(or([Filter_Prod_L2], [Filter_Prod_L3]), or([Hierarchy_Prod_L2_Name] in {\"Manufacturer\", \"Ingredient\", \"Brand\", \"Subbrand\"}, [Hierarchy_Prod_L3_Name] in {\"Manufacturer\", \"Ingredient\", \"Brand\", \"Subbrand\"})),",
              "                        [Sales_SKU_Market_Parent],",
              "                        [Sales_SKU_Period]))",
              "\t\t\t\t\t\t",
              "return market_sku"
            ],
            "formatString": "#,0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" ThousandSeparator=\"True\" />"
              }
            ]
          },
          {
            "name": "LY_Sales_SKU_Product",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var last_year = calculate(values('Dim_Period'[MAT_year]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) - 1",
              "var seq = calculate(values('Dim_Period'[period_seq]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod))",
              "",
              "return calculate([Sales_SKU_Product], filter(all('Dim_Period'), Dim_Period[MAT_year] = last_year && 'Dim_Period'[period_seq] = seq && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "formatString": "#,0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" ThousandSeparator=\"True\" />"
              }
            ]
          },
          {
            "name": "LY_Sales_SKU_Competitor",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var last_year = calculate(values('Dim_Period'[MAT_year]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) - 1",
              "var seq = calculate(values('Dim_Period'[period_seq]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod))",
              "",
              "return calculate([Sales_SKU_Competitor], filter(all('Dim_Period'), Dim_Period[MAT_year] = last_year && 'Dim_Period'[period_seq] = seq && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "formatString": "#,0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" ThousandSeparator=\"True\" />"
              }
            ]
          },
          {
            "name": "LY_Sales_SKU_Market",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var last_year = calculate(values('Dim_Period'[MAT_year]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) - 1",
              "var seq = calculate(values('Dim_Period'[period_seq]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod))",
              "",
              "return calculate([Sales_SKU_Market], filter(all('Dim_Period'), Dim_Period[MAT_year] = last_year && 'Dim_Period'[period_seq] = seq && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "formatString": "#,0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" ThousandSeparator=\"True\" />"
              }
            ]
          },
          {
            "name": "LY_Sales_SKU_Market_Category",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var last_year = calculate(values('Dim_Period'[MAT_year]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) - 1",
              "var seq = calculate(values('Dim_Period'[period_seq]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod))",
              "",
              "return calculate([Sales_SKU_Market_Category], filter(all('Dim_Period'), Dim_Period[MAT_year] = last_year && 'Dim_Period'[period_seq] = seq && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "formatString": "#,0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" ThousandSeparator=\"True\" />"
              }
            ]
          },
          {
            "name": "LY_Sales_SKU_Market_Parent",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var last_year = calculate(values('Dim_Period'[MAT_year]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) - 1",
              "var seq = calculate(values('Dim_Period'[period_seq]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod))",
              "",
              "return calculate([Sales_SKU_Market_Parent], filter(all('Dim_Period'), Dim_Period[MAT_year] = last_year && 'Dim_Period'[period_seq] = seq && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "formatString": "#,0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" ThousandSeparator=\"True\" />"
              }
            ]
          },
          {
            "name": "LY_Sales_SKU_Product_Own",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var last_year = calculate(values('Dim_Period'[MAT_year]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) - 1",
              "var seq = calculate(values('Dim_Period'[period_seq]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod))",
              "",
              "return calculate([Sales_SKU_Product_Own], filter(all('Dim_Period'), Dim_Period[MAT_year] = last_year && 'Dim_Period'[period_seq] = seq && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "formatString": "#,0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" ThousandSeparator=\"True\" />"
              }
            ]
          },
          {
            "name": "LY_MS_SKU_Category",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var last_year = calculate(values('Dim_Period'[MAT_year]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) - 1",
              "var seq = calculate(values('Dim_Period'[period_seq]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod))",
              "",
              "return calculate([MS_SKU_Category], filter(all('Dim_Period'), Dim_Period[MAT_year] = last_year && 'Dim_Period'[period_seq] = seq && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Percentage\" Accuracy=\"2\" />"
              }
            ]
          },
          {
            "name": "LY_MS_SKU_Parent",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var last_year = calculate(values('Dim_Period'[MAT_year]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) - 1",
              "var seq = calculate(values('Dim_Period'[period_seq]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod))",
              "",
              "return calculate([MS_SKU_Parent], filter(all('Dim_Period'), Dim_Period[MAT_year] = last_year && 'Dim_Period'[period_seq] = seq && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Percentage\" Accuracy=\"2\" />"
              }
            ]
          },
          {
            "name": "LY_MS_SKU_Product",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var last_year = calculate(values('Dim_Period'[MAT_year]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) - 1",
              "var seq = calculate(values('Dim_Period'[period_seq]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod))",
              "",
              "return calculate([MS_SKU_Product], filter(all('Dim_Period'), Dim_Period[MAT_year] = last_year && 'Dim_Period'[period_seq] = seq && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Percentage\" Accuracy=\"2\" />"
              }
            ]
          },
          {
            "name": "MS_SKU_Product_CW",
            "expression": "calculate([MS_SKU_Product], Filter(All('Dim_Banner_Type'), 'Dim_Banner_Type'[banner_type] = \"cw\"))",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Percentage\" Accuracy=\"2\" />"
              }
            ]
          },
          {
            "name": "MS_SKU_Product_OTH",
            "expression": "calculate([MS_SKU_Product], Filter(All('Dim_Banner_Type'), 'Dim_Banner_Type'[banner_type] = \"noncw\"))",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Percentage\" Accuracy=\"2\" />"
              }
            ]
          },
          {
            "name": "LY_MS_SKU_Product_CW",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var last_year = calculate(values('Dim_Period'[MAT_year]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) - 1",
              "var seq = calculate(values('Dim_Period'[period_seq]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod))",
              "",
              "return calculate([MS_SKU_Product_CW], filter(all('Dim_Period'), Dim_Period[MAT_year] = last_year && 'Dim_Period'[period_seq] = seq && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Percentage\" Accuracy=\"2\" />"
              }
            ]
          },
          {
            "name": "LY_MS_SKU_Product_OTH",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var last_year = calculate(values('Dim_Period'[MAT_year]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) - 1",
              "var seq = calculate(values('Dim_Period'[period_seq]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod))",
              "",
              "return calculate([MS_SKU_Product_OTH], filter(all('Dim_Period'), Dim_Period[MAT_year] = last_year && 'Dim_Period'[period_seq] = seq && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Percentage\" Accuracy=\"2\" />"
              }
            ]
          },
          {
            "name": "YOY_Gth_SKU_Market",
            "expression": "[Sales_SKU_Market] - [LY_Sales_SKU_Market]",
            "formatString": "#,0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" ThousandSeparator=\"True\" />"
              }
            ]
          },
          {
            "name": "YOY_Gth_SKU_Product",
            "expression": "[Sales_SKU_Product] - [LY_Sales_SKU_Product]",
            "formatString": "#,0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" ThousandSeparator=\"True\" />"
              }
            ]
          },
          {
            "name": "YOY_Gth_%_SKU_Product",
            "expression": "divide([YOY_Gth_SKU_Product] , [LY_Sales_SKU_Product])",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Percentage\" Accuracy=\"2\" />"
              }
            ]
          },
          {
            "name": "YOY_Gth_SKU_Product_CW",
            "expression": "calculate([YOY_Gth_SKU_Product], Filter(All('Dim_Banner_Type'), 'Dim_Banner_Type'[banner_type] = \"cw\"))",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "YOY_Gth_SKU_Product_OTH",
            "expression": "calculate([YOY_Gth_SKU_Product], Filter(All('Dim_Banner_Type'), 'Dim_Banner_Type'[banner_type] = \"noncw\"))",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "LY_Gth_SKU_Product_CW",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var last_year = calculate(values('Dim_Period'[MAT_year]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) - 1",
              "var seq = calculate(values('Dim_Period'[period_seq]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod))",
              "",
              "return calculate([YOY_Gth_SKU_Product_CW], filter(all('Dim_Period'), Dim_Period[MAT_year] = last_year && 'Dim_Period'[period_seq] = seq && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "LY_Gth_SKU_Product_OTH",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var last_year = calculate(values('Dim_Period'[MAT_year]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) - 1",
              "var seq = calculate(values('Dim_Period'[period_seq]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod))",
              "",
              "return calculate([YOY_Gth_SKU_Product_OTH], filter(all('Dim_Period'), Dim_Period[MAT_year] = last_year && 'Dim_Period'[period_seq] = seq && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "YOY_Gth_%_SKU_Product_CW",
            "expression": "calculate([YOY_Gth_%_SKU_Product], Filter(All('Dim_Banner_Type'), 'Dim_Banner_Type'[banner_type] = \"cw\"))",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Percentage\" Accuracy=\"2\" />"
              }
            ]
          },
          {
            "name": "YOY_Gth_%_SKU_Product_OTH",
            "expression": "calculate([YOY_Gth_%_SKU_Product], Filter(All('Dim_Banner_Type'), 'Dim_Banner_Type'[banner_type] = \"noncw\"))",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Percentage\" Accuracy=\"2\" />"
              }
            ]
          },
          {
            "name": "LY_Gth_%_SKU_Product_CW",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var last_year = calculate(values('Dim_Period'[MAT_year]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) - 1",
              "var seq = calculate(values('Dim_Period'[period_seq]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod))",
              "",
              "return calculate([YOY_Gth_%_SKU_Product_CW], filter(all('Dim_Period'), Dim_Period[MAT_year] = last_year && 'Dim_Period'[period_seq] = seq && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Percentage\" Accuracy=\"2\" />"
              }
            ]
          },
          {
            "name": "LY_Gth_%_SKU_Product_OTH",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var last_year = calculate(values('Dim_Period'[MAT_year]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) - 1",
              "var seq = calculate(values('Dim_Period'[period_seq]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod))",
              "",
              "return calculate([YOY_Gth_%_SKU_Product_OTH], filter(all('Dim_Period'), Dim_Period[MAT_year] = last_year && 'Dim_Period'[period_seq] = seq && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Percentage\" Accuracy=\"2\" />"
              }
            ]
          },
          {
            "name": "Rank_SKU_Product",
            "expression": [
              "",
              "",
              "var Rank_SKU_Product_L1 = calculate(rankx(ALL('Dim_Product_Client_Hierarchy'[prod_level_1]), ",
              "if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKU_Product],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKU_Product],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKU_Product]",
              "                    ), [Sales_SKU_Product])))",
              "var Rank_SKU_Product_L2 = calculate(rankx(ALL('Dim_Product_Client_Hierarchy'[prod_level_2]), ",
              "if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKU_Product],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKU_Product],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKU_Product]",
              "                    ), [Sales_SKU_Product])))",
              "var Rank_SKU_Product_L3 = calculate(rankx(ALL('Dim_Product_Client_Hierarchy'[prod_level_3]), ",
              "if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKU_Product],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKU_Product],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKU_Product]",
              "                    ), [Sales_SKU_Product])))",
              "var Rank_SKU_Product_L4 = calculate(rankx(ALL('Dim_Product_Client_Hierarchy'[prod_level_4]), ",
              "if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKU_Product],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKU_Product],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKU_Product]",
              "                    ), [Sales_SKU_Product])))",
              "var Rank_SKU_Product_L5 = calculate(rankx(ALL('Dim_Product_Client_Hierarchy'[prod_level_5]), ",
              "if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKU_Product],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKU_Product],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKU_Product]",
              "                    ), [Sales_SKU_Product])))",
              "",
              "return if([Sales_SKU_Product] <> 0, Switch(True(),",
              "[Filter_SKUName],[Rank_SKU_Product_Pack],",
              "[Filter_Prod_L5], Rank_SKU_Product_L5,",
              "[Filter_Prod_L4], Rank_SKU_Product_L4,",
              "[Filter_Prod_L3], Rank_SKU_Product_L3,",
              "[Filter_Prod_L2], Rank_SKU_Product_L2,",
              "[Filter_Prod_L1], Rank_SKU_Product_L1,",
              "Blank()), blank())",
              "",
              ""
            ],
            "formatString": "0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Rank_SKU_Market",
            "expression": [
              "",
              "var Rank_SKU_Market_L1 = calculate(rankx(ALL('Dim_Product_Client_Hierarchy'[prod_level_1]), ",
              "if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKU_Period]",
              "                    ), [Sales_SKU_Period])))",
              "var Rank_SKU_Market_L2 = calculate(rankx(ALL('Dim_Product_Client_Hierarchy'[prod_level_2]), ",
              "if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKU_Period]",
              "                    ), [Sales_SKU_Period])))",
              "var Rank_SKU_Market_L3 = calculate(rankx(ALL('Dim_Product_Client_Hierarchy'[prod_level_3]), ",
              "if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKU_Period]",
              "                    ), [Sales_SKU_Period])))",
              "var Rank_SKU_Market_L4 = calculate(rankx(ALL('Dim_Product_Client_Hierarchy'[prod_level_4]), ",
              "if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKU_Period]",
              "                    ), [Sales_SKU_Period])))",
              "var Rank_SKU_Market_L5 = calculate(rankx(ALL('Dim_Product_Client_Hierarchy'[prod_level_5]), ",
              "if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKU_Period]",
              "                    ), [Sales_SKU_Period])))",
              "",
              "return if(countrows('Fact_SKU_State_Sales') > 0, Switch(True(),",
              "[Filter_SKUName], blank(),",
              "[Filter_Prod_L5], Rank_SKU_Market_L5,",
              "[Filter_Prod_L4], Rank_SKU_Market_L4,",
              "[Filter_Prod_L3], if([Hierarchy_Prod_L3_Name] =\"Subbrand\", blank(), Rank_SKU_Market_L3),",
              "[Filter_Prod_L2], if([Hierarchy_Prod_L2_Name] = \"Brand\", blank(), Rank_SKU_Market_L2),",
              "[Filter_Prod_L1], Rank_SKU_Market_L1,",
              "Blank()))",
              ""
            ],
            "formatString": "0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "YOY_EI_SKU",
            "expression": "DIVIDE([MS_SKU_Product],[LY_MS_SKU_Product],BLANK())*100",
            "formatString": "0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "LY_Gth_%_SKU_Product",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var last_year = calculate(values('Dim_Period'[MAT_year]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) - 1",
              "var seq = calculate(values('Dim_Period'[period_seq]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod))",
              "",
              "return calculate([YOY_Gth_%_SKU_Product], filter(all('Dim_Period'), Dim_Period[MAT_year] = last_year && 'Dim_Period'[period_seq] = seq && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Percentage\" Accuracy=\"2\" />"
              }
            ]
          },
          {
            "name": "YOY_MS_Change_SKU",
            "expression": "[MS_SKU_Product] - [LY_MS_SKU_Product]",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Percentage\" Accuracy=\"2\" />"
              }
            ]
          },
          {
            "name": "YTD_MS_SKU_Product",
            "expression": "calculate([MS_SKU_Product], filter(ALL(Dim_Period), 'Dim_Period'[Period_Type] = \"YTD\"))",
            "formatString": "#,0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" ThousandSeparator=\"True\" />"
              }
            ]
          },
          {
            "name": "YTD_Sales_SKU_Product",
            "expression": "calculate([Sales_SKU_Product], filter(ALL(Dim_Period), 'Dim_Period'[Period_Type] = \"YTD\"))",
            "formatString": "0%;-0%;0%",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Percentage\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "YTD_Sales_SKU_Market",
            "expression": "calculate([Sales_SKU_Market], filter(ALL(Dim_Period), 'Dim_Period'[Period_Type] = \"YTD\"))",
            "formatString": "0%;-0%;0%",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Percentage\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "YTD_MS_Change_SKU",
            "expression": "calculate([YOY_MS_Change_SKU], filter(ALL(Dim_Period), 'Dim_Period'[Period_Type] = \"YTD\"))",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Percentage\" Accuracy=\"2\" />"
              }
            ]
          },
          {
            "name": "YTD_Gth_%_SKU_Product",
            "expression": "calculate([YOY_Gth_%_SKU_Product], filter(ALL(Dim_Period), 'Dim_Period'[Period_Type] = \"YTD\"))",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Percentage\" Accuracy=\"2\" />"
              }
            ]
          },
          {
            "name": "MAT_MS_SKU_Product",
            "expression": "calculate([MS_SKU_Product], filter(ALL(Dim_Period), 'Dim_Period'[Period_Type] = \"MAT\"))",
            "formatString": "#,0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" ThousandSeparator=\"True\" />"
              }
            ]
          },
          {
            "name": "MAT_Sales_SKU_Product",
            "expression": "calculate([Sales_SKU_Product], filter(ALL(Dim_Period), 'Dim_Period'[Period_Type] = \"MAT\"))",
            "formatString": "#,0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" ThousandSeparator=\"True\" />"
              }
            ]
          },
          {
            "name": "MAT_Sales_SKU_Market",
            "expression": "calculate([Sales_SKU_Market], filter(ALL(Dim_Period), 'Dim_Period'[Period_Type] = \"MAT\"))",
            "formatString": "#,0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" ThousandSeparator=\"True\" />"
              }
            ]
          },
          {
            "name": "MAT_MS_Change_SKU",
            "expression": "calculate([YOY_MS_Change_SKU], filter(ALL(Dim_Period), 'Dim_Period'[Period_Type] = \"MAT\"))",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Percentage\" Accuracy=\"2\" />"
              }
            ]
          },
          {
            "name": "MAT_Gth_%_SKU_Product",
            "expression": "calculate([YOY_Gth_%_SKU_Product], filter(ALL(Dim_Period), 'Dim_Period'[Period_Type] = \"MAT\"))",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Percentage\" Accuracy=\"2\" />"
              }
            ]
          },
          {
            "name": "Sales_SKU_Product_CW",
            "expression": [
              "",
              "var sales_cw = calculate([Sales_SKU_Product], Filter(All('Dim_Banner_Type'), 'Dim_Banner_Type'[banner_type] = \"cw\"))",
              "return if(isblank(sales_cw), 0, sales_cw)"
            ],
            "formatString": "#,0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" ThousandSeparator=\"True\" />"
              }
            ]
          },
          {
            "name": "Sales_SKU_Product_OTH",
            "expression": "calculate([Sales_SKU_Product], Filter(All('Dim_Banner_Type'), 'Dim_Banner_Type'[banner_type] = \"noncw\"))",
            "formatString": "#,0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" ThousandSeparator=\"True\" />"
              }
            ]
          },
          {
            "name": "Sales_SKU_Product_TOT",
            "expression": "calculate([Sales_SKU_Product], All('Dim_Banner_Type'))",
            "formatString": "#,0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" ThousandSeparator=\"True\" />"
              }
            ]
          },
          {
            "name": "LY_Sales_SKU_Product_CW",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var last_year = calculate(values('Dim_Period'[MAT_year]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) - 1",
              "var seq = calculate(values('Dim_Period'[period_seq]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod))",
              "",
              "return calculate([Sales_SKU_Product_CW], filter(all('Dim_Period'), Dim_Period[MAT_year] = last_year && 'Dim_Period'[period_seq] = seq && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "formatString": "#,0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" ThousandSeparator=\"True\" />"
              }
            ]
          },
          {
            "name": "LY_Sales_SKU_Product_OTH",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var last_year = calculate(values('Dim_Period'[MAT_year]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) - 1",
              "var seq = calculate(values('Dim_Period'[period_seq]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod))",
              "",
              "return calculate([Sales_SKU_Product_OTH], filter(all('Dim_Period'), Dim_Period[MAT_year] = last_year && 'Dim_Period'[period_seq] = seq && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "formatString": "#,0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" ThousandSeparator=\"True\" />"
              }
            ]
          },
          {
            "name": "LY_Sales_SKU_Product_TOT",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var last_year = calculate(values('Dim_Period'[MAT_year]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) - 1",
              "var seq = calculate(values('Dim_Period'[period_seq]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod))",
              "",
              "return calculate([Sales_SKU_Product_TOT], filter(all('Dim_Period'), Dim_Period[MAT_year] = last_year && 'Dim_Period'[period_seq] = seq && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "formatString": "#,0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" ThousandSeparator=\"True\" />"
              }
            ]
          },
          {
            "name": "Sales_SKU_Market_CW",
            "expression": "calculate([Sales_SKU_Market], Filter(All('Dim_Banner_Type'), 'Dim_Banner_Type'[banner_type] = \"cw\"))",
            "formatString": "#,0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" ThousandSeparator=\"True\" />"
              }
            ]
          },
          {
            "name": "Sales_SKU_Market_OTH",
            "expression": "calculate([Sales_SKU_Market], Filter(All('Dim_Banner_Type'), 'Dim_Banner_Type'[banner_type] = \"noncw\"))",
            "formatString": "0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Sales_SKU_Market_TOT",
            "expression": "calculate([Sales_SKU_Market], All('Dim_Banner_Type'))",
            "formatString": "#,0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" ThousandSeparator=\"True\" />"
              }
            ]
          },
          {
            "name": "LY_Sales_SKU_Market_CW",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var last_year = calculate(values('Dim_Period'[MAT_year]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) - 1",
              "var seq = calculate(values('Dim_Period'[period_seq]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod))",
              "",
              "return calculate([Sales_SKU_Market_CW], filter(all('Dim_Period'), Dim_Period[MAT_year] = last_year && 'Dim_Period'[period_seq] = seq && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "formatString": "#,0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" ThousandSeparator=\"True\" />"
              }
            ]
          },
          {
            "name": "LY_Sales_SKU_Market_OTH",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var last_year = calculate(values('Dim_Period'[MAT_year]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) - 1",
              "var seq = calculate(values('Dim_Period'[period_seq]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod))",
              "",
              "return calculate([Sales_SKU_Market_OTH], filter(all('Dim_Period'), Dim_Period[MAT_year] = last_year && 'Dim_Period'[period_seq] = seq && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "formatString": "#,0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" ThousandSeparator=\"True\" />"
              }
            ]
          },
          {
            "name": "LY_Sales_SKU_Market_TOT",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var last_year = calculate(values('Dim_Period'[MAT_year]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) - 1",
              "var seq = calculate(values('Dim_Period'[period_seq]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod))",
              "",
              "return calculate([Sales_SKU_Market_TOT], filter(all('Dim_Period'), Dim_Period[MAT_year] = last_year && 'Dim_Period'[period_seq] = seq && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "formatString": "#,0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" ThousandSeparator=\"True\" />"
              }
            ]
          },
          {
            "name": "LP_Sales_SKU_Product",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var num = calculate(values('Dim_Period'[period_num]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) + 1",
              "",
              "return calculate([Sales_SKU_Product], filter(all('Dim_Period'), 'Dim_Period'[period_num] = num && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "LP_MS_SKU_Category",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var num = calculate(values('Dim_Period'[period_num]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) + 1",
              "",
              "return calculate([MS_SKU_Category], filter(all('Dim_Period'), 'Dim_Period'[period_num] = num && 'Dim_Period'[Period_Type] = p_type)) "
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "LP_MS_SKU_Parent",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var num = calculate(values('Dim_Period'[period_num]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) + 1",
              "",
              "return calculate([MS_SKU_Parent], filter(all('Dim_Period'), 'Dim_Period'[period_num] = num && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "LP_MS_SKU_Product",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var num = calculate(values('Dim_Period'[period_num]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) + 1",
              "",
              "return calculate([MS_SKU_Product], filter(all('Dim_Period'), 'Dim_Period'[period_num] = num && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "LP_MS_SKU_Product_CW",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var num = calculate(values('Dim_Period'[period_num]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) + 1",
              "",
              "return calculate([MS_SKU_Product_CW], filter(all('Dim_Period'), 'Dim_Period'[period_num] = num && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "LP_MS_SKU_Product_OTH",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var num = calculate(values('Dim_Period'[period_num]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) + 1",
              "",
              "return calculate([MS_SKU_Product_OTH], filter(all('Dim_Period'), 'Dim_Period'[period_num] = num && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "LP_Sales_SKU_Competitor",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var num = calculate(values('Dim_Period'[period_num]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) + 1",
              "",
              "return calculate([Sales_SKU_Competitor], filter(all('Dim_Period'), 'Dim_Period'[period_num] = num && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "LP_Sales_SKU_Market",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var num = calculate(values('Dim_Period'[period_num]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) + 1",
              "",
              "return calculate([Sales_SKU_Market], filter(all('Dim_Period'), 'Dim_Period'[period_num] = num && 'Dim_Period'[Period_Type] = p_type))",
              ""
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "LP_Sales_SKU_Market_Category",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var num = calculate(values('Dim_Period'[period_num]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) + 1",
              "",
              "return calculate([Sales_SKU_Market_Category], filter(all('Dim_Period'), 'Dim_Period'[period_num] = num && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "LP_Sales_SKU_Market_CW",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var num = calculate(values('Dim_Period'[period_num]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) + 1",
              "",
              "return calculate([Sales_SKU_Market_CW], filter(all('Dim_Period'), 'Dim_Period'[period_num] = num && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "LP_Sales_SKU_Market_OTH",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var num = calculate(values('Dim_Period'[period_num]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) + 1",
              "",
              "return calculate([Sales_SKU_Market_OTH], filter(all('Dim_Period'), 'Dim_Period'[period_num] = num && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "LP_Sales_SKU_Market_Parent",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var num = calculate(values('Dim_Period'[period_num]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) + 1",
              "",
              "return calculate([Sales_SKU_Market_Parent], filter(all('Dim_Period'), 'Dim_Period'[period_num] = num && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "LP_Sales_SKU_Market_TOT",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var num = calculate(values('Dim_Period'[period_num]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) + 1",
              "",
              "return calculate([Sales_SKU_Market_TOT], filter(all('Dim_Period'), 'Dim_Period'[period_num] = num && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "LP_Sales_SKU_Product_CW",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var num = calculate(values('Dim_Period'[period_num]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) + 1",
              "",
              "return calculate([Sales_SKU_Product_CW], filter(all('Dim_Period'), 'Dim_Period'[period_num] = num && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "LP_Sales_SKU_Product_OTH",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var num = calculate(values('Dim_Period'[period_num]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) + 1",
              "",
              "return calculate([Sales_SKU_Product_OTH], filter(all('Dim_Period'), 'Dim_Period'[period_num] = num && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "LP_Sales_SKU_Product_Own",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var num = calculate(values('Dim_Period'[period_num]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) + 1",
              "",
              "return calculate([Sales_SKU_Product_Own], filter(all('Dim_Period'), 'Dim_Period'[period_num] = num && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "LP_Sales_SKU_Product_TOT",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var num = calculate(values('Dim_Period'[period_num]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) + 1",
              "",
              "return calculate([Sales_SKU_Product_TOT], filter(all('Dim_Period'), 'Dim_Period'[period_num] = num && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "POP_Gth_SKU_Market",
            "expression": "[Sales_SKU_Market] - [LP_Sales_SKU_Market]",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "POP_Gth_SKU_Product",
            "expression": "[Sales_SKU_Product] - [LP_Sales_SKU_Product]",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "POP_MS_Change_SKU",
            "expression": "[MS_SKU_Product] - [LP_MS_SKU_Product]",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "POP_Gth_%_SKU_Product",
            "expression": "divide([POP_Gth_SKU_Product] , [LP_Sales_SKU_Product])",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "POP_Gth_%_SKU_Product_CW",
            "expression": "calculate([POP_Gth_%_SKU_Product], Filter(All('Dim_Banner_Type'), 'Dim_Banner_Type'[banner_type] = \"cw\"))",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "POP_Gth_%_SKU_Product_OTH",
            "expression": "calculate([POP_Gth_%_SKU_Product], Filter(All('Dim_Banner_Type'), 'Dim_Banner_Type'[banner_type] = \"noncw\"))",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "POP_Gth_SKU_Product_CW",
            "expression": "calculate([POP_Gth_SKU_Product], Filter(All('Dim_Banner_Type'), 'Dim_Banner_Type'[banner_type] = \"cw\"))",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "POP_Gth_SKU_Product_OTH",
            "expression": "calculate([POP_Gth_SKU_Product], Filter(All('Dim_Banner_Type'), 'Dim_Banner_Type'[banner_type] = \"noncw\"))",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "POP_EI_SKU",
            "expression": "DIVIDE([MS_SKU_Product],[LP_MS_SKU_Product],BLANK())*100",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "PP_Sales_SKU_Product_TOT",
            "expression": "if(HASONEVALUE(AUX_Previous_Period[name]), SWITCH(TRUE(), values(AUX_Previous_Period[name]) = \"LY\", [LY_Sales_SKU_Product_TOT], [LP_Sales_SKU_Product_TOT]), [LY_Sales_SKU_Product_TOT])",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "PP_MS_SKU_Category",
            "expression": "if(HASONEVALUE(AUX_Previous_Period[name]), SWITCH(TRUE(), values(AUX_Previous_Period[name]) = \"LY\", [LY_MS_SKU_Category], [LP_MS_SKU_Category]), [LY_MS_SKU_Category])",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Percentage\" Accuracy=\"2\" />"
              }
            ]
          },
          {
            "name": "PP_MS_SKU_Parent",
            "expression": "if(HASONEVALUE(AUX_Previous_Period[name]), SWITCH(TRUE(), values(AUX_Previous_Period[name]) = \"LY\", [LY_MS_SKU_Parent], [LP_MS_SKU_Parent]), [LY_MS_SKU_Parent])",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Percentage\" Accuracy=\"2\" />"
              }
            ]
          },
          {
            "name": "PP_MS_SKU_Product",
            "expression": "if(HASONEVALUE(AUX_Previous_Period[name]), SWITCH(TRUE(), values(AUX_Previous_Period[name]) = \"LY\", [LY_MS_SKU_Product], [LP_MS_SKU_Product]), [LY_MS_SKU_Product])",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "PP_MS_SKU_Product_CW",
            "expression": "if(HASONEVALUE(AUX_Previous_Period[name]), SWITCH(TRUE(), values(AUX_Previous_Period[name]) = \"LY\", [LY_MS_SKU_Product_CW], [LP_MS_SKU_Product_CW]), [LY_MS_SKU_Product_CW])",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "PP_MS_SKU_Product_OTH",
            "expression": "if(HASONEVALUE(AUX_Previous_Period[name]), SWITCH(TRUE(), values(AUX_Previous_Period[name]) = \"LY\", [LY_MS_SKU_Product_OTH], [LP_MS_SKU_Product_OTH]), [LY_MS_SKU_Product_OTH])",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "PP_Sales_SKU_Competitor",
            "expression": "if(HASONEVALUE(AUX_Previous_Period[name]), SWITCH(TRUE(), values(AUX_Previous_Period[name]) = \"LY\", [LY_Sales_SKU_Competitor], [LP_Sales_SKU_Competitor]), [LY_Sales_SKU_Competitor])",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "PP_Sales_SKU_Market",
            "expression": "if(HASONEVALUE(AUX_Previous_Period[name]), SWITCH(TRUE(), values(AUX_Previous_Period[name]) = \"LY\", [LY_Sales_SKU_Market], [LP_Sales_SKU_Market]), [LY_Sales_SKU_Market]) ",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "PP_Sales_SKU_Market_Category",
            "expression": "if(HASONEVALUE(AUX_Previous_Period[name]), SWITCH(TRUE(), values(AUX_Previous_Period[name]) = \"LY\", [LY_Sales_SKU_Market_Category], [LP_Sales_SKU_Market_Category]), [LY_Sales_SKU_Market_Category])",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "PP_Sales_SKU_Market_CW",
            "expression": "if(HASONEVALUE(AUX_Previous_Period[name]), SWITCH(TRUE(), values(AUX_Previous_Period[name]) = \"LY\", [LY_Sales_SKU_Market_CW], [LP_Sales_SKU_Market_CW]), [LY_Sales_SKU_Market_CW])",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "PP_Sales_SKU_Market_OTH",
            "expression": "if(HASONEVALUE(AUX_Previous_Period[name]), SWITCH(TRUE(), values(AUX_Previous_Period[name]) = \"LY\", [LY_Sales_SKU_Market_OTH], [LP_Sales_SKU_Market_OTH]), [LY_Sales_SKU_Market_OTH])",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "PP_Sales_SKU_Market_Parent",
            "expression": "if(HASONEVALUE(AUX_Previous_Period[name]), SWITCH(TRUE(), values(AUX_Previous_Period[name]) = \"LY\", [LY_Sales_SKU_Market_Parent], [LP_Sales_SKU_Market_Parent]), [LY_Sales_SKU_Market_Parent])",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "PP_Sales_SKU_Market_TOT",
            "expression": "if(HASONEVALUE(AUX_Previous_Period[name]), SWITCH(TRUE(), values(AUX_Previous_Period[name]) = \"LY\", [LY_Sales_SKU_Market_TOT], [LP_Sales_SKU_Market_TOT]), [LY_Sales_SKU_Market_TOT])",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "PP_Sales_SKU_Product",
            "expression": "if(HASONEVALUE(AUX_Previous_Period[name]), SWITCH(TRUE(), values(AUX_Previous_Period[name]) = \"LY\", [LY_Sales_SKU_Product], [LP_Sales_SKU_Product]), [LY_Sales_SKU_Product])",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "PP_Sales_SKU_Product_CW",
            "expression": "if(HASONEVALUE(AUX_Previous_Period[name]), SWITCH(TRUE(), values(AUX_Previous_Period[name]) = \"LY\", [LY_Sales_SKU_Product_CW], [LP_Sales_SKU_Product_CW]), [LY_Sales_SKU_Product_CW])",
            "formatString": "#,0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" ThousandSeparator=\"True\" />"
              }
            ]
          },
          {
            "name": "PP_Sales_SKU_Product_OTH",
            "expression": "if(HASONEVALUE(AUX_Previous_Period[name]), SWITCH(TRUE(), values(AUX_Previous_Period[name]) = \"LY\", [LY_Sales_SKU_Product_OTH], [LP_Sales_SKU_Product_OTH]), [LY_Sales_SKU_Product_OTH])",
            "formatString": "#,0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" ThousandSeparator=\"True\" />"
              }
            ]
          },
          {
            "name": "PP_Sales_SKU_Product_Own",
            "expression": "if(HASONEVALUE(AUX_Previous_Period[name]), SWITCH(TRUE(), values(AUX_Previous_Period[name]) = \"LY\", [LY_Sales_SKU_Product_Own], [LP_Sales_SKU_Product_Own]), [LY_Sales_SKU_Product_Own])",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Gth_SKU_Market",
            "expression": "if(isblank([PP_Sales_SKU_Market]), blank(), [Sales_SKU_Market] - [PP_Sales_SKU_Market])",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Gth_SKU_Product",
            "expression": "if(isblank([PP_Sales_SKU_Product]), blank(), [Sales_SKU_Product] - [PP_Sales_SKU_Product])",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "MS_Change_SKU",
            "expression": "[MS_SKU_Product] - [PP_MS_SKU_Product]",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Percentage\" Accuracy=\"2\" />"
              }
            ]
          },
          {
            "name": "Gth_%_SKU_Product",
            "expression": "divide([Gth_SKU_Product] , [PP_Sales_SKU_Product])",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Gth_%_SKU_Product_CW",
            "expression": "calculate([Gth_%_SKU_Product], Filter(All('Dim_Banner_Type'), 'Dim_Banner_Type'[banner_type] = \"cw\"))",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Percentage\" Accuracy=\"2\" />"
              }
            ]
          },
          {
            "name": "Gth_%_SKU_Product_OTH",
            "expression": "calculate([Gth_%_SKU_Product], Filter(All('Dim_Banner_Type'), 'Dim_Banner_Type'[banner_type] = \"noncw\"))",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Percentage\" Accuracy=\"2\" />"
              }
            ]
          },
          {
            "name": "Gth_SKU_Product_CW",
            "expression": "calculate([Gth_SKU_Product], Filter(All('Dim_Banner_Type'), 'Dim_Banner_Type'[banner_type] = \"cw\"))",
            "formatString": "#,0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" ThousandSeparator=\"True\" />"
              }
            ]
          },
          {
            "name": "Gth_SKU_Product_OTH",
            "expression": "calculate([Gth_SKU_Product], Filter(All('Dim_Banner_Type'), 'Dim_Banner_Type'[banner_type] = \"noncw\"))",
            "formatString": "#,0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" ThousandSeparator=\"True\" />"
              }
            ]
          },
          {
            "name": "Sales_SKU_Market_Pack",
            "expression": [
              "",
              "var hier_id = Calculate(values(Dim_Hierarchy_Name_Product[hierarchy_id]), Dim_Hierarchy_Name_Product[hierarchy_name] = values(Dim_Hierarchy_Name_Product[hierarchy_name]))",
              "var prod_l1_selected = values('Dim_Product_Client_Hierarchy'[prod_level_1])",
              "var prod_l2_selected = values('Dim_Product_Client_Hierarchy'[prod_level_2])",
              "var prod_l3_selected = values('Dim_Product_Client_Hierarchy'[prod_level_3])",
              "var prod_l4_selected = values('Dim_Product_Client_Hierarchy'[prod_level_4])",
              "var prod_l5_selected = values('Dim_Product_Client_Hierarchy'[prod_level_5])",
              "",
              "",
              "var market_l5 = calculate([Sales_SKU_Period], filter(all('Dim_Product_Client_Hierarchy'), 'Dim_Product_Client_Hierarchy'[prod_level_5] in prod_l5_selected && 'Dim_Product_Client_Hierarchy'[hierarchy_id] = hier_id))",
              "var market_l4 = calculate([Sales_SKU_Period], filter(all('Dim_Product_Client_Hierarchy'), 'Dim_Product_Client_Hierarchy'[prod_level_4] in prod_l4_selected && 'Dim_Product_Client_Hierarchy'[hierarchy_id] = hier_id))",
              "var market_l3 = calculate([Sales_SKU_Period], filter(all('Dim_Product_Client_Hierarchy'), 'Dim_Product_Client_Hierarchy'[prod_level_3] in prod_l3_selected && 'Dim_Product_Client_Hierarchy'[hierarchy_id] = hier_id))",
              "var market_l2 = calculate([Sales_SKU_Period], filter(all('Dim_Product_Client_Hierarchy'), 'Dim_Product_Client_Hierarchy'[prod_level_2] in prod_l2_selected && 'Dim_Product_Client_Hierarchy'[hierarchy_id] = hier_id))",
              "var market_l1 = calculate([Sales_SKU_Period], filter(all('Dim_Product_Client_Hierarchy'), 'Dim_Product_Client_Hierarchy'[prod_level_1] in prod_l1_selected && 'Dim_Product_Client_Hierarchy'[hierarchy_id] = hier_id))",
              "var market_oth = calculate([Sales_SKU_Period], ALLSELECTED('Dim_Product_Client_Hierarchy'))",
              "",
              "var market =  switch(True(), [Filter_SKUName] && [Filter_Prod_L5], market_l5,",
              "                      [Filter_SKUName] && [Filter_Prod_L4], market_l4,",
              "                      [Filter_SKUName] && [Filter_Prod_L3], market_l3,",
              "                      [Filter_SKUName] && [Filter_Prod_L2], market_l2,",
              "                      [Filter_SKUName] && [Filter_Prod_L1], market_l1,",
              "                      [Filter_SKUName] , market_l1, market_oth)",
              "                            ",
              "return if(countrows('Fact_SKU_State_Sales') > 0, market)",
              ""
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Gth_SKU_Product_TOT",
            "expression": "calculate([Gth_SKU_Product], All('Dim_Banner_Type'))",
            "formatString": "#,0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" ThousandSeparator=\"True\" />"
              }
            ]
          },
          {
            "name": "MS_SKU_Product_TOT",
            "expression": "calculate([MS_SKU_Product], All('Dim_Banner_Type'))",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Percentage\" Accuracy=\"2\" />"
              }
            ]
          },
          {
            "name": "LP_MS_SKU_Product_TOT",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var num = calculate(values('Dim_Period'[period_num]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) + 1",
              "",
              "return calculate([MS_SKU_Product_TOT], filter(all('Dim_Period'), 'Dim_Period'[period_num] = num && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "LY_MS_SKU_Product_TOT",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var last_year = calculate(values('Dim_Period'[MAT_year]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) - 1",
              "var seq = calculate(values('Dim_Period'[period_seq]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod))",
              "",
              "return calculate([MS_SKU_Product_TOT], filter(all('Dim_Period'), Dim_Period[MAT_year] = last_year && 'Dim_Period'[period_seq] = seq && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "PP_MS_SKU_Product_TOT",
            "expression": "if(HASONEVALUE(AUX_Previous_Period[name]), SWITCH(TRUE(), values(AUX_Previous_Period[name]) = \"LY\", [LY_MS_SKU_Product_TOT], [LP_MS_SKU_Product_TOT]), [LY_MS_SKU_Product_TOT])",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Gth_%_SKU_Product_TOT",
            "expression": "calculate([Gth_%_SKU_Product], All('Dim_Banner_Type'))",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Percentage\" Accuracy=\"2\" />"
              }
            ]
          },
          {
            "name": "Rank_SKU_Product_Pack",
            "expression": [
              "",
              "var hier_id = Calculate(values(Dim_Hierarchy_Name_Product[hierarchy_id]), Dim_Hierarchy_Name_Product[hierarchy_name] = values(Dim_Hierarchy_Name_Product[hierarchy_name]))",
              "var rank_oth = calculate(rankx(ALL('Dim_Product_Client_Hierarchy'[pack_name]), ",
              "if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKU_Period]",
              "                    ), [Sales_SKU_Period])), ",
              "'Dim_Product_Client_Hierarchy'[hierarchy_id] = hier_id)",
              "                                        ",
              "return if(countrows('Fact_SKU_State_Sales') > 0 && [Filter_SKUName], rank_oth) "
            ],
            "formatString": "0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "TnB_Filter_SKU_Brand",
            "expression": [
              "",
              "var top_brand = calculatetable(",
              "    TOPN(values('AUX_Top_Selection_Prod'[Top_Value]),",
              "    CALCULATETABLE(VALUES('Dim_Product_Client'[Brand]), FILTER('Dim_Product_Client', [Sales_SKU_Period] <> 0 )),",
              "    if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKU_Period]",
              "                    ), [Sales_SKU_Period]), 0",
              "    )",
              "    , ALLSELECTED()",
              ")",
              "",
              "var bot_brand = calculatetable(",
              "    TOPN(values('AUX_Top_Selection_Prod'[Top_Value]),",
              "    CALCULATETABLE(VALUES('Dim_Product_Client'[Brand]), FILTER('Dim_Product_Client', [Sales_SKU_Period] <> 0 )),",
              "    if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKU_Period]",
              "                    ), [Sales_SKU_Period]), 1",
              "    )",
              "    , ALLSELECTED()",
              ")",
              "",
              "var tnb_union = UNION(top_brand,bot_brand)",
              "",
              "var top_only = CALCULATE(",
              "    1 * (NOT ISEMPTY('Dim_Product_Client')),",
              "    KEEPFILTERS(top_brand)",
              ")",
              "",
              "var bot_only = CALCULATE(",
              "    1 * (NOT ISEMPTY('Dim_Product_Client')),",
              "    KEEPFILTERS(bot_brand)",
              ")",
              "",
              "var tnb_both = CALCULATE(",
              "    1 * (NOT ISEMPTY('Dim_Product_Client')),",
              "    KEEPFILTERS(tnb_union)",
              ")",
              "",
              "return if([Sales_SKU_Period] <> 0 && HASONEVALUE(AUX_Top_Selection_Prod[Top_Type]), switch(TRUE(),",
              "                                    values(AUX_Top_Selection_Prod[Top_Type]) = \"Top\", top_only,",
              "                                    values(AUX_Top_Selection_Prod[Top_Type]) = \"Bottom\", bot_only,",
              "                                    values(AUX_Top_Selection_Prod[Top_Type]) = \"TnB\", tnb_both,",
              "                                    top_only",
              "                                    ),",
              "                                    top_only)",
              ""
            ],
            "formatString": "0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "TnB_Filter_SKU_Label_Brand",
            "expression": [
              "",
              "var top_brand = calculatetable(",
              "    TOPN(values('AUX_Top_Selection_Prod'[Top_Value]),",
              "    CALCULATETABLE(VALUES('Dim_Product_Client'[Brand]), FILTER('Dim_Product_Client', [Sales_SKU_Period] <> 0 )),",
              "    if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKU_Period]",
              "                    ), [Sales_SKU_Period]), 0",
              "    )",
              "    , ALLSELECTED()",
              ")",
              "",
              "var bot_brand = calculatetable(",
              "    TOPN(values('AUX_Top_Selection_Prod'[Top_Value]),",
              "    CALCULATETABLE(VALUES('Dim_Product_Client'[Brand]), FILTER('Dim_Product_Client', [Sales_SKU_Period] <> 0 )),",
              "    if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKU_Period]",
              "                    ), [Sales_SKU_Period]), 1",
              "    )",
              "    , ALLSELECTED()",
              ")",
              "",
              "var top_only = CALCULATE(",
              "    1 * (NOT ISEMPTY('Dim_Product_Client')),",
              "    KEEPFILTERS(top_brand)",
              ")",
              "",
              "var bot_only = CALCULATE(",
              "    1 * (NOT ISEMPTY('Dim_Product_Client')),",
              "    KEEPFILTERS(bot_brand)",
              ")",
              "",
              "return if([Sales_SKU_Period] <> 0 && HASONEVALUE(AUX_Top_Selection_Prod[Top_Type]), switch(TRUE(),",
              "                                    top_only = 1, \"Top\",",
              "                                    bot_only = 1, \"Bottom\"",
              "                                    ))",
              ""
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "TnB_Filter_SKU_Value_Brand",
            "expression": [
              "",
              "var top_brand = calculatetable(",
              "    TOPN(values('AUX_Top_Selection_Prod'[Top_Value]),",
              "    CALCULATETABLE(VALUES('Dim_Product_Client'[Brand]), FILTER('Dim_Product_Client', [Sales_SKU_Period] <> 0 )),",
              "    if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKU_Period]",
              "                    ), [Sales_SKU_Period]), 0",
              "    )",
              "    , ALLSELECTED()",
              ")",
              "",
              "var bot_brand = calculatetable(",
              "    TOPN(values('AUX_Top_Selection_Prod'[Top_Value]),",
              "    CALCULATETABLE(VALUES('Dim_Product_Client'[Brand]), FILTER('Dim_Product_Client', [Sales_SKU_Period] <> 0 )),",
              "    if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKU_Period]",
              "                    ), [Sales_SKU_Period]), 1",
              "    )",
              "    , ALLSELECTED()",
              ")",
              "",
              "var top_only = CALCULATE(",
              "    1 * (NOT ISEMPTY('Dim_Product_Client')),",
              "    KEEPFILTERS(top_brand)",
              ")",
              "",
              "var bot_only = CALCULATE(",
              "    1 * (NOT ISEMPTY('Dim_Product_Client')),",
              "    KEEPFILTERS(bot_brand)",
              ")",
              "",
              "return if([Sales_SKU_Period] <> 0 && HASONEVALUE(AUX_Top_Selection_Prod[Top_Type]), switch(TRUE(),",
              "                                    top_only = 1, 1,",
              "                                    bot_only = 1, -1",
              "                                    ))"
            ],
            "formatString": "0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Gth_%_SKU_Market",
            "expression": "divide([Gth_SKU_Market] , [PP_Sales_SKU_Market])",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "TnB_Filter_SKU_Manu",
            "expression": [
              "",
              "var top_manufacturer = calculatetable(",
              "    TOPN(values('AUX_Top_Selection_Prod'[Top_Value]),",
              "    CALCULATETABLE(VALUES('Dim_Product_Client'[Manufacturer]), FILTER('Dim_Product_Client', [Sales_SKU_Period] <> 0 )),",
              "    if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKU_Period]",
              "                    ), [Sales_SKU_Period]), 0",
              "    )",
              "    , ALLSELECTED()",
              ")",
              "",
              "var bot_manufacturer = calculatetable(",
              "    TOPN(values('AUX_Top_Selection_Prod'[Top_Value]),",
              "    CALCULATETABLE(VALUES('Dim_Product_Client'[Manufacturer]), FILTER('Dim_Product_Client', [Sales_SKU_Period] <> 0 )),",
              "    if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKU_Period]",
              "                    ), [Sales_SKU_Period]), 1",
              "    )",
              "    , ALLSELECTED()",
              ")",
              "",
              "var tnb_union = UNION(top_manufacturer,bot_manufacturer)",
              "",
              "var top_only = CALCULATE(",
              "    1 * (NOT ISEMPTY('Dim_Product_Client')),",
              "    KEEPFILTERS(top_manufacturer)",
              ")",
              "",
              "var bot_only = CALCULATE(",
              "    1 * (NOT ISEMPTY('Dim_Product_Client')),",
              "    KEEPFILTERS(bot_manufacturer)",
              ")",
              "",
              "var tnb_both = CALCULATE(",
              "    1 * (NOT ISEMPTY('Dim_Product_Client')),",
              "    KEEPFILTERS(tnb_union)",
              ")",
              "",
              "return if([Sales_SKU_Period] <> 0 && HASONEVALUE(AUX_Top_Selection_Prod[Top_Type]), switch(TRUE(),",
              "                                    values(AUX_Top_Selection_Prod[Top_Type]) = \"Top\", top_only,",
              "                                    values(AUX_Top_Selection_Prod[Top_Type]) = \"Bottom\", bot_only,",
              "                                    values(AUX_Top_Selection_Prod[Top_Type]) = \"TnB\", tnb_both,",
              "                                    top_only",
              "                                    ),",
              "                                    top_only)"
            ],
            "formatString": "0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "TnB_Filter_SKU_Label_Manu",
            "expression": [
              "",
              "var top_manufacturer = calculatetable(",
              "    TOPN(values('AUX_Top_Selection_Prod'[Top_Value]),",
              "    CALCULATETABLE(VALUES('Dim_Product_Client'[Manufacturer]), FILTER('Dim_Product_Client', [Sales_SKU_Period] <> 0 )),",
              "    if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKU_Period]",
              "                    ), [Sales_SKU_Period]), 0",
              "    )",
              "    , ALLSELECTED()",
              ")",
              "",
              "var bot_manufacturer = calculatetable(",
              "    TOPN(values('AUX_Top_Selection_Prod'[Top_Value]),",
              "    CALCULATETABLE(VALUES('Dim_Product_Client'[Manufacturer]), FILTER('Dim_Product_Client', [Sales_SKU_Period] <> 0 )),",
              "    if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKU_Period]",
              "                    ), [Sales_SKU_Period]), 1",
              "    )",
              "    , ALLSELECTED()",
              ")",
              "",
              "var top_only = CALCULATE(",
              "    1 * (NOT ISEMPTY('Dim_Product_Client')),",
              "    KEEPFILTERS(top_manufacturer)",
              ")",
              "",
              "var bot_only = CALCULATE(",
              "    1 * (NOT ISEMPTY('Dim_Product_Client')),",
              "    KEEPFILTERS(bot_manufacturer)",
              ")",
              "",
              "return if([Sales_SKU_Period] <> 0 && HASONEVALUE(AUX_Top_Selection_Prod[Top_Type]), switch(TRUE(),",
              "                                    top_only = 1, \"Top\",",
              "                                    bot_only = 1, \"Bottom\"",
              "                                    ))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "TnB_Filter_SKU_Value_Manu",
            "expression": [
              "",
              "var top_manufacturer = calculatetable(",
              "    TOPN(values('AUX_Top_Selection_Prod'[Top_Value]),",
              "    CALCULATETABLE(VALUES('Dim_Product_Client'[Manufacturer]), FILTER('Dim_Product_Client', [Sales_SKU_Period] <> 0 )),",
              "    if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKU_Period]",
              "                    ), [Sales_SKU_Period]), 0",
              "    )",
              "    , ALLSELECTED()",
              ")",
              "",
              "var bot_manufacturer = calculatetable(",
              "    TOPN(values('AUX_Top_Selection_Prod'[Top_Value]),",
              "    CALCULATETABLE(VALUES('Dim_Product_Client'[Manufacturer]), FILTER('Dim_Product_Client', [Sales_SKU_Period] <> 0 )),",
              "    if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKU_Period]",
              "                    ), [Sales_SKU_Period]), 1",
              "    )",
              "    , ALLSELECTED()",
              ")",
              "",
              "var top_only = CALCULATE(",
              "    1 * (NOT ISEMPTY('Dim_Product_Client')),",
              "    KEEPFILTERS(top_manufacturer)",
              ")",
              "",
              "var bot_only = CALCULATE(",
              "    1 * (NOT ISEMPTY('Dim_Product_Client')),",
              "    KEEPFILTERS(bot_manufacturer)",
              ")",
              "",
              "return if([Sales_SKU_Period] <> 0 && HASONEVALUE(AUX_Top_Selection_Prod[Top_Type]), switch(TRUE(),",
              "                                    top_only = 1, 1,",
              "                                    bot_only = 1, -1",
              "                                    ))"
            ],
            "formatString": "0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "TnB_Filter_SKU_Pack",
            "expression": [
              "",
              "var top_pack = calculatetable(",
              "    TOPN(values('AUX_Top_Selection_Prod'[Top_Value]),",
              "    CALCULATETABLE(VALUES('Dim_Product_Client'[Pack]), FILTER('Dim_Product_Client', [Sales_SKU_Period] <> 0 )),",
              "    if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKU_Period]",
              "                    ), [Sales_SKU_Period]), 0",
              "    )",
              "    , ALLSELECTED()",
              ")",
              "",
              "var bot_pack = calculatetable(",
              "    TOPN(values('AUX_Top_Selection_Prod'[Top_Value]),",
              "    CALCULATETABLE(VALUES('Dim_Product_Client'[Pack]), FILTER('Dim_Product_Client', [Sales_SKU_Period] <> 0 )),",
              "    if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKU_Period]",
              "                    ), [Sales_SKU_Period]), 1",
              "    )",
              "    , ALLSELECTED()",
              ")",
              "",
              "var tnb_union = UNION(top_pack, bot_pack)",
              "",
              "var top_only = CALCULATE(",
              "    1 * (NOT ISEMPTY('Dim_Product_Client')),",
              "    KEEPFILTERS(top_pack)",
              ")",
              "",
              "var bot_only = CALCULATE(",
              "    1 * (NOT ISEMPTY('Dim_Product_Client')),",
              "    KEEPFILTERS(bot_pack)",
              ")",
              "",
              "var tnb_both = CALCULATE(",
              "    1 * (NOT ISEMPTY('Dim_Product_Client')),",
              "    KEEPFILTERS(tnb_union)",
              ")",
              "",
              "return if([Sales_SKU_Period] <> 0 && HASONEVALUE(AUX_Top_Selection_Prod[Top_Type]), switch(TRUE(),",
              "                                    values(AUX_Top_Selection_Prod[Top_Type]) = \"Top\", top_only,",
              "                                    values(AUX_Top_Selection_Prod[Top_Type]) = \"Bottom\", bot_only,",
              "                                    values(AUX_Top_Selection_Prod[Top_Type]) = \"TnB\", tnb_both,",
              "                                    top_only",
              "                                    ),",
              "                                    top_only)"
            ],
            "formatString": "0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "LY_Sales_SKU_Period",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var last_year = calculate(values('Dim_Period'[MAT_year]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) - 1",
              "var seq = calculate(values('Dim_Period'[period_seq]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod))",
              "",
              "return calculate([Sales_SKU_Period], filter(all('Dim_Period'), Dim_Period[MAT_year] = last_year && 'Dim_Period'[period_seq] = seq && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "LP_Sales_SKU_Period",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var num = calculate(values('Dim_Period'[period_num]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) + 1",
              "",
              "return calculate([Sales_SKU_Period], filter(all('Dim_Period'), 'Dim_Period'[period_num] = num && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "PP_Sales_SKU_Period",
            "expression": "if(HASONEVALUE(AUX_Previous_Period[name]), SWITCH(TRUE(), values(AUX_Previous_Period[name]) = \"LY\", [LY_Sales_SKU_Period], [LP_Sales_SKU_Period]), [LY_Sales_SKU_Period])",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Gth_SKU_Period",
            "expression": "if(isblank([PP_Sales_SKU_Period]), blank(), [Sales_SKU_Period] - [PP_Sales_SKU_Period])",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Gth_%_SKU_Period",
            "expression": "divide([Gth_SKU_Period] , [PP_Sales_SKU_Period])",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "TnB_Filter_SKU_Value_Pack",
            "expression": [
              "",
              "var top_pack = calculatetable(",
              "    TOPN(values('AUX_Top_Selection_Prod'[Top_Value]),",
              "    CALCULATETABLE(VALUES('Dim_Product_Client'[Pack]), FILTER('Dim_Product_Client', [Sales_SKU_Period] <> 0 )),",
              "    if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKU_Period]",
              "                    ), [Sales_SKU_Period]), 0",
              "    )",
              "    , ALLSELECTED()",
              ")",
              "",
              "var bot_pack = calculatetable(",
              "    TOPN(values('AUX_Top_Selection_Prod'[Top_Value]),",
              "    CALCULATETABLE(VALUES('Dim_Product_Client'[Pack]), FILTER('Dim_Product_Client', [Sales_SKU_Period] <> 0 )),",
              "    if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKU_Period]",
              "                    ), [Sales_SKU_Period]), 1",
              "    )",
              "    , ALLSELECTED()",
              ")",
              "",
              "var top_only = CALCULATE(",
              "    1 * (NOT ISEMPTY('Dim_Product_Client')),",
              "    KEEPFILTERS(top_pack)",
              ")",
              "",
              "var bot_only = CALCULATE(",
              "    1 * (NOT ISEMPTY('Dim_Product_Client')),",
              "    KEEPFILTERS(bot_pack)",
              ")",
              "",
              "return if([Sales_SKU_Period] <> 0 && HASONEVALUE(AUX_Top_Selection_Prod[Top_Type]), switch(TRUE(),",
              "                                    top_only = 1, 1,",
              "                                    bot_only = 1, -1",
              "                                    ))\t"
            ],
            "formatString": "0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "TnB_Filter_SKU_Label_Pack",
            "expression": [
              "",
              "var top_pack = calculatetable(",
              "    TOPN(values('AUX_Top_Selection_Prod'[Top_Value]),",
              "    CALCULATETABLE(VALUES('Dim_Product_Client'[Pack]), FILTER('Dim_Product_Client', [Sales_SKU_Period] <> 0 )),",
              "    if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKU_Period]",
              "                    ), [Sales_SKU_Period]), 0",
              "    )",
              "    , ALLSELECTED()",
              ")",
              "",
              "var bot_pack = calculatetable(",
              "    TOPN(values('AUX_Top_Selection_Prod'[Top_Value]),",
              "    CALCULATETABLE(VALUES('Dim_Product_Client'[Pack]), FILTER('Dim_Product_Client', [Sales_SKU_Period] <> 0 )),",
              "    if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKU_Period]",
              "                    ), [Sales_SKU_Period]), 1",
              "    )",
              "    , ALLSELECTED()",
              ")",
              "",
              "var top_only = CALCULATE(",
              "    1 * (NOT ISEMPTY('Dim_Product_Client')),",
              "    KEEPFILTERS(top_pack)",
              ")",
              "",
              "var bot_only = CALCULATE(",
              "    1 * (NOT ISEMPTY('Dim_Product_Client')),",
              "    KEEPFILTERS(bot_pack)",
              ")",
              "",
              "return if([Sales_SKU_Period] <> 0 && HASONEVALUE(AUX_Top_Selection_Prod[Top_Type]), switch(TRUE(),",
              "                                    top_only = 1, \"Top\",",
              "                                    bot_only = 1, \"Bottom\"",
              "                                    ))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "TnB_Filter_SKU",
            "expression": [
              "",
              "var top_brand = calculatetable(",
              "    TOPN(values('AUX_Top_Selection_Prod'[Top_Value]),",
              "    CALCULATETABLE(VALUES('Dim_Product_Client_Top_Analysis'[top_items]), FILTER('Dim_Product_Client_Top_Analysis', [Sales_SKU_Period] <> 0 )),",
              "    if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKU_Period]",
              "                    ), [Sales_SKU_Period]), 0",
              "    )",
              "    , ALLSELECTED()",
              ")",
              "",
              "var bot_brand = calculatetable(",
              "    TOPN(values('AUX_Top_Selection_Prod'[Top_Value]),",
              "    CALCULATETABLE(VALUES('Dim_Product_Client_Top_Analysis'[top_items]), FILTER('Dim_Product_Client_Top_Analysis', [Sales_SKU_Period] <> 0 )),",
              "    if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKU_Period]",
              "                    ), [Sales_SKU_Period]), 1",
              "    )",
              "    , ALLSELECTED()",
              ")",
              "",
              "var tnb_union = UNION(top_brand,bot_brand)",
              "",
              "var top_only = CALCULATE(",
              "    1 * (NOT ISEMPTY('Dim_Product_Client_Top_Analysis')),",
              "    KEEPFILTERS(top_brand)",
              ")",
              "",
              "var bot_only = CALCULATE(",
              "    1 * (NOT ISEMPTY('Dim_Product_Client_Top_Analysis')),",
              "    KEEPFILTERS(bot_brand)",
              ")",
              "",
              "var tnb_both = CALCULATE(",
              "    1 * (NOT ISEMPTY('Dim_Product_Client_Top_Analysis')),",
              "    KEEPFILTERS(tnb_union)",
              ")",
              "",
              "return if([Sales_Outlet_Period] <> 0 && HASONEVALUE(AUX_Top_Selection_Prod[Top_Type]), switch(TRUE(),",
              "                                    values(AUX_Top_Selection_Prod[Top_Type]) = \"Top\", top_only,",
              "                                    values(AUX_Top_Selection_Prod[Top_Type]) = \"Bottom\", bot_only,",
              "                                    values(AUX_Top_Selection_Prod[Top_Type]) = \"TnB\", tnb_both,",
              "                                    top_only",
              "                                    ),",
              "                                    top_only)",
              ""
            ],
            "formatString": "0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "TnB_Filter_SKU_Label",
            "expression": [
              "",
              "var top_brand = calculatetable(",
              "    TOPN(values('AUX_Top_Selection_Prod'[Top_Value]),",
              "    CALCULATETABLE(VALUES('Dim_Product_Client_Top_Analysis'[top_items]), FILTER('Dim_Product_Client_Top_Analysis', [Sales_SKU_Period] <> 0 )),",
              "    if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKU_Period]",
              "                    ), [Sales_SKU_Period]), 0",
              "    )",
              "    , ALLSELECTED()",
              ")",
              "",
              "var bot_brand = calculatetable(",
              "    TOPN(values('AUX_Top_Selection_Prod'[Top_Value]),",
              "    CALCULATETABLE(VALUES('Dim_Product_Client_Top_Analysis'[top_items]), FILTER('Dim_Product_Client_Top_Analysis', [Sales_SKU_Period] <> 0 )),",
              "    if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKU_Period]",
              "                    ), [Sales_SKU_Period]), 1",
              "    )",
              "    , ALLSELECTED()",
              ")",
              "",
              "var top_only = CALCULATE(",
              "    1 * (NOT ISEMPTY('Dim_Product_Client_Top_Analysis')),",
              "    KEEPFILTERS(top_brand)",
              ")",
              "",
              "var bot_only = CALCULATE(",
              "    1 * (NOT ISEMPTY('Dim_Product_Client_Top_Analysis')),",
              "    KEEPFILTERS(bot_brand)",
              ")",
              "",
              "return if([Sales_SKU_Period] <> 0 && HASONEVALUE(AUX_Top_Selection_Prod[Top_Type]), switch(TRUE(),",
              "                                    top_only = 1, \"Top\",",
              "                                    bot_only = 1, \"Bottom\"",
              "                                    ))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "TnB_Filter_SKU_Value",
            "expression": [
              "",
              "var top_brand = calculatetable(",
              "    TOPN(values('AUX_Top_Selection_Prod'[Top_Value]),",
              "    CALCULATETABLE(VALUES('Dim_Product_Client_Top_Analysis'[top_items]), FILTER('Dim_Product_Client_Top_Analysis', [Sales_SKU_Period] <> 0 )),",
              "    if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKU_Period]",
              "                    ), [Sales_SKU_Period]), 0",
              "    )",
              "    , ALLSELECTED()",
              ")",
              "",
              "var bot_brand = calculatetable(",
              "    TOPN(values('AUX_Top_Selection_Prod'[Top_Value]),",
              "    CALCULATETABLE(VALUES('Dim_Product_Client_Top_Analysis'[top_items]), FILTER('Dim_Product_Client_Top_Analysis', [Sales_SKU_Period] <> 0 )),",
              "    if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKU_Period]",
              "                    ), [Sales_SKU_Period]), 1",
              "    )",
              "    , ALLSELECTED()",
              ")",
              "",
              "var top_only = CALCULATE(",
              "    1 * (NOT ISEMPTY('Dim_Product_Client_Top_Analysis')),",
              "    KEEPFILTERS(top_brand)",
              ")",
              "",
              "var bot_only = CALCULATE(",
              "    1 * (NOT ISEMPTY('Dim_Product_Client_Top_Analysis')),",
              "    KEEPFILTERS(bot_brand)",
              ")",
              "",
              "return if([Sales_SKU_Period] <> 0 && HASONEVALUE(AUX_Top_Selection_Prod[Top_Type]), switch(TRUE(),",
              "                                    top_only = 1, 1,",
              "                                    bot_only = 1, -1",
              "                                    ))"
            ],
            "formatString": "0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Top_Filter_SKU_Prod",
            "expression": [
              "",
              "var top_prod_l1 = calculatetable(",
              "    TOPN(values('AUX_Top_Selection_Prod'[Top_Value]),",
              "    CALCULATETABLE(VALUES('Dim_Product_Client_Hierarchy'[prod_level_1]), FILTER('Dim_Product_Client_Hierarchy', [Sales_SKU_Period] <> 0 )),",
              "    if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKU_Period]",
              "                    ), [Sales_SKU_Period]), 0",
              "    )",
              "    , ALLSELECTED()",
              ")",
              "",
              "var top_prod_l2 = calculatetable(",
              "    TOPN(values('AUX_Top_Selection_Prod'[Top_Value]),",
              "    CALCULATETABLE(VALUES('Dim_Product_Client_Hierarchy'[prod_level_2]), FILTER('Dim_Product_Client_Hierarchy', [Sales_SKU_Period] <> 0 )),",
              "    if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKU_Period]",
              "                    ), [Sales_SKU_Period]), 0",
              "    )",
              "    , ALLSELECTED()",
              ")",
              "",
              "var top_prod_l3 = calculatetable(",
              "    TOPN(values('AUX_Top_Selection_Prod'[Top_Value]),",
              "    CALCULATETABLE(VALUES('Dim_Product_Client_Hierarchy'[prod_level_3]), FILTER('Dim_Product_Client_Hierarchy', [Sales_SKU_Period] <> 0 )),",
              "    if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKU_Period]",
              "                    ), [Sales_SKU_Period]), 0",
              "    )",
              "    , ALLSELECTED()",
              ")",
              "",
              "var top_prod_l4 = calculatetable(",
              "    TOPN(values('AUX_Top_Selection_Prod'[Top_Value]),",
              "    CALCULATETABLE(VALUES('Dim_Product_Client_Hierarchy'[prod_level_4]), FILTER('Dim_Product_Client_Hierarchy', [Sales_SKU_Period] <> 0 )),",
              "    if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKU_Period]",
              "                    ), [Sales_SKU_Period]), 0",
              "    )",
              "    , ALLSELECTED()",
              ")",
              "",
              "var top_prod_l5 = calculatetable(",
              "    TOPN(values('AUX_Top_Selection_Prod'[Top_Value]),",
              "    CALCULATETABLE(VALUES('Dim_Product_Client_Hierarchy'[prod_level_5]), FILTER('Dim_Product_Client_Hierarchy', [Sales_SKU_Period] <> 0 )),",
              "    if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKU_Period]",
              "                    ), [Sales_SKU_Period]), 0",
              "    )",
              "    , ALLSELECTED()",
              ")",
              "",
              "",
              "",
              "var top_l1 = CALCULATE(",
              "    1 * (NOT ISEMPTY('Dim_Product_Client')),",
              "    KEEPFILTERS(top_prod_l1)",
              ")",
              "",
              "var top_l2 = CALCULATE(",
              "    1 * (NOT ISEMPTY('Dim_Product_Client')),",
              "    KEEPFILTERS(top_prod_l2)",
              ")",
              "",
              "var top_l3 = CALCULATE(",
              "    1 * (NOT ISEMPTY('Dim_Product_Client')),",
              "    KEEPFILTERS(top_prod_l3)",
              ")",
              "",
              "var top_l4 = CALCULATE(",
              "    1 * (NOT ISEMPTY('Dim_Product_Client')),",
              "    KEEPFILTERS(top_prod_l4)",
              ")",
              "",
              "var top_l5 = CALCULATE(",
              "    1 * (NOT ISEMPTY('Dim_Product_Client')),",
              "    KEEPFILTERS(top_prod_l5)",
              ")",
              "",
              "",
              "return if([Sales_SKU_Period] <> 0 && HASONEVALUE(AUX_Top_Selection_Prod[Top_Type]), switch(TRUE(),",
              "                                    [Filter_Prod_L5], top_l5,",
              "                                    [Filter_Prod_L4], top_l4,",
              "                                    [Filter_Prod_L3], top_l3,",
              "                                    [Filter_Prod_L2], top_l2,",
              "\t\t\t\t\t\t\t\t\t[Filter_Prod_L1], top_l1",
              "                                    ))",
              ""
            ],
            "formatString": "0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "EI_SKU",
            "expression": "if(HASONEVALUE(AUX_Previous_Period[name]), SWITCH(TRUE(), values(AUX_Previous_Period[name]) = \"LY\", [YOY_EI_SKU], [POP_EI_SKU]), [YOY_EI_SKU])",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Top_Filter_SKU_Prod_2",
            "expression": [
              "",
              "var top_prod_l1 = calculatetable(",
              "    TOPN(values('AUX_Top_Selection_Prod'[Top_Value]),",
              "    CALCULATETABLE(VALUES('Dim_Product_Client_Hierarchy'[prod_level_1]), FILTER('Dim_Product_Client_Hierarchy', [Sales_SKU_Period] <> 0 )),",
              "    if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKU_Period]",
              "                    ), [Sales_SKU_Period]), 0",
              "    )",
              "    , ALLSELECTED()",
              ")",
              "",
              "var top_prod_l2 = calculatetable(",
              "    TOPN(values('AUX_Top_Selection_Prod'[Top_Value]),",
              "    CALCULATETABLE(VALUES('Dim_Product_Client_Hierarchy'[prod_level_2]), FILTER('Dim_Product_Client_Hierarchy', [Sales_SKU_Period] <> 0 )),",
              "    if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKU_Period]",
              "                    ), [Sales_SKU_Period]), 0",
              "    )",
              "    , ALLSELECTED()",
              ")",
              "",
              "var top_prod_l3 = calculatetable(",
              "    TOPN(values('AUX_Top_Selection_Prod'[Top_Value]),",
              "    CALCULATETABLE(VALUES('Dim_Product_Client_Hierarchy'[prod_level_3]), FILTER('Dim_Product_Client_Hierarchy', [Sales_SKU_Period] <> 0 )),",
              "    if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKU_Period]",
              "                    ), [Sales_SKU_Period]), 0",
              "    )",
              "    , ALLSELECTED()",
              ")",
              "",
              "var top_prod_l4 = calculatetable(",
              "    TOPN(values('AUX_Top_Selection_Prod'[Top_Value]),",
              "    CALCULATETABLE(VALUES('Dim_Product_Client_Hierarchy'[prod_level_4]), FILTER('Dim_Product_Client_Hierarchy', [Sales_SKU_Period] <> 0 )),",
              "    if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKU_Period]",
              "                    ), [Sales_SKU_Period]), 0",
              "    )",
              "    , ALLSELECTED()",
              ")",
              "",
              "var top_prod_l5 = calculatetable(",
              "    TOPN(values('AUX_Top_Selection_Prod'[Top_Value]),",
              "    CALCULATETABLE(VALUES('Dim_Product_Client_Hierarchy'[prod_level_5]), FILTER('Dim_Product_Client_Hierarchy', [Sales_SKU_Period] <> 0 )),",
              "    if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKU_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKU_Period]",
              "                    ), [Sales_SKU_Period]), 0",
              "    )",
              "    , ALLSELECTED()",
              ")",
              "",
              "",
              "",
              "var top_l1 = CALCULATE(",
              "    1 * (NOT ISEMPTY('Dim_Product_Client')),",
              "    KEEPFILTERS(top_prod_l1)",
              ")",
              "",
              "var top_l2 = CALCULATE(",
              "    1 * (NOT ISEMPTY('Dim_Product_Client')),",
              "    KEEPFILTERS(top_prod_l2)",
              ")",
              "",
              "var top_l3 = CALCULATE(",
              "    1 * (NOT ISEMPTY('Dim_Product_Client')),",
              "    KEEPFILTERS(top_prod_l3)",
              ")",
              "",
              "var top_l4 = CALCULATE(",
              "    1 * (NOT ISEMPTY('Dim_Product_Client')),",
              "    KEEPFILTERS(top_prod_l4)",
              ")",
              "",
              "var top_l5 = CALCULATE(",
              "    1 * (NOT ISEMPTY('Dim_Product_Client')),",
              "    KEEPFILTERS(top_prod_l5)",
              ")",
              "",
              "",
              "return if([Sales_SKU_Period] <> 0 && HASONEVALUE(AUX_Top_Selection_Prod[Top_Type]), switch(TRUE(),",
              "\t\t\t\t\t\t\t\t\tISINSCOPE('Dim_Product_Client_Hierarchy'[prod_level_1]), top_l1,",
              "\t\t\t\t\t\t\t\t\tISINSCOPE('Dim_Product_Client_Hierarchy'[prod_level_2]), top_l2,",
              "\t\t\t\t\t\t\t\t\tISINSCOPE('Dim_Product_Client_Hierarchy'[prod_level_3]), top_l3,",
              "\t\t\t\t\t\t\t\t\tISINSCOPE('Dim_Product_Client_Hierarchy'[prod_level_4]), top_l4,",
              "                                    ISINSCOPE('Dim_Product_Client_Hierarchy'[prod_level_5]), top_l5",
              "                                    ))"
            ],
            "formatString": "0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Top_Filter_SKU_Prod_3",
            "expression": [
              "",
              "var top_prod_l1 = calculatetable(",
              "    TOPN(values('AUX_Top_Selection_Prod'[Top_Value]),",
              "    CALCULATETABLE(VALUES('Dim_Product_Client_Hierarchy'[prod_level_1]), FILTER('Dim_Product_Client_Hierarchy', [Sales_SKU_Product_TOT] <> 0 )),",
              "    if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKU_Product_TOT],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKU_Product_TOT],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKU_Product_TOT]",
              "                    ), [Sales_SKU_Product_TOT]), 0",
              "    )",
              "    , ALLSELECTED()",
              ")",
              "",
              "var top_prod_l2 = calculatetable(",
              "    TOPN(values('AUX_Top_Selection_Prod'[Top_Value]),",
              "    CALCULATETABLE(VALUES('Dim_Product_Client_Hierarchy'[prod_level_2]), FILTER('Dim_Product_Client_Hierarchy', [Sales_SKU_Product_TOT] <> 0 )),",
              "    if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKU_Product_TOT],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKU_Product_TOT],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKU_Product_TOT]",
              "                    ), [Sales_SKU_Product_TOT]), 0",
              "    )",
              "    , ALLSELECTED()",
              ")",
              "",
              "var top_prod_l3 = calculatetable(",
              "    TOPN(values('AUX_Top_Selection_Prod'[Top_Value]),",
              "    CALCULATETABLE(VALUES('Dim_Product_Client_Hierarchy'[prod_level_3]), FILTER('Dim_Product_Client_Hierarchy', [Sales_SKU_Product_TOT] <> 0 )),",
              "    if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKU_Product_TOT],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKU_Product_TOT],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKU_Product_TOT]",
              "                    ), [Sales_SKU_Product_TOT]), 0",
              "    )",
              "    , ALLSELECTED()",
              ")",
              "",
              "var top_prod_l4 = calculatetable(",
              "    TOPN(values('AUX_Top_Selection_Prod'[Top_Value]),",
              "    CALCULATETABLE(VALUES('Dim_Product_Client_Hierarchy'[prod_level_4]), FILTER('Dim_Product_Client_Hierarchy', [Sales_SKU_Product_TOT] <> 0 )),",
              "    if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKU_Product_TOT],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKU_Product_TOT],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKU_Product_TOT]",
              "                    ), [Sales_SKU_Product_TOT]), 0",
              "    )",
              "    , ALLSELECTED()",
              ")",
              "",
              "var top_prod_l5 = calculatetable(",
              "    TOPN(values('AUX_Top_Selection_Prod'[Top_Value]),",
              "    CALCULATETABLE(VALUES('Dim_Product_Client_Hierarchy'[prod_level_5]), FILTER('Dim_Product_Client_Hierarchy', [Sales_SKU_Product_TOT] <> 0 )),",
              "    if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKU_Product_TOT],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKU_Product_TOT],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKU_Product_TOT]",
              "                    ), [Sales_SKU_Product_TOT]), 0",
              "    )",
              "    , ALLSELECTED()",
              ")",
              "",
              "",
              "",
              "var top_l1 = CALCULATE(",
              "    1 * (NOT ISEMPTY('Dim_Product_Client')),",
              "    KEEPFILTERS(top_prod_l1)",
              ")",
              "",
              "var top_l2 = CALCULATE(",
              "    1 * (NOT ISEMPTY('Dim_Product_Client')),",
              "    KEEPFILTERS(top_prod_l2)",
              ")",
              "",
              "var top_l3 = CALCULATE(",
              "    1 * (NOT ISEMPTY('Dim_Product_Client')),",
              "    KEEPFILTERS(top_prod_l3)",
              ")",
              "",
              "var top_l4 = CALCULATE(",
              "    1 * (NOT ISEMPTY('Dim_Product_Client')),",
              "    KEEPFILTERS(top_prod_l4)",
              ")",
              "",
              "var top_l5 = CALCULATE(",
              "    1 * (NOT ISEMPTY('Dim_Product_Client')),",
              "    KEEPFILTERS(top_prod_l5)",
              ")",
              "",
              "",
              "return if([Sales_SKU_Product_TOT] <> 0 && HASONEVALUE(AUX_Top_Selection_Prod[Top_Type]), switch(TRUE(),",
              "\t\t\t\t\t\t\t\t\tISINSCOPE('Dim_Product_Client_Hierarchy'[prod_level_1]), top_l1,",
              "\t\t\t\t\t\t\t\t\tISINSCOPE('Dim_Product_Client_Hierarchy'[prod_level_2]), top_l2,",
              "\t\t\t\t\t\t\t\t\tISINSCOPE('Dim_Product_Client_Hierarchy'[prod_level_3]), top_l3,",
              "\t\t\t\t\t\t\t\t\tISINSCOPE('Dim_Product_Client_Hierarchy'[prod_level_4]), top_l4,",
              "                                    ISINSCOPE('Dim_Product_Client_Hierarchy'[prod_level_5]), top_l5",
              "                                    ))"
            ],
            "formatString": "0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Rank_SKU_Product_2",
            "expression": [
              "",
              "",
              "var Rank_SKU_Product_L1 = calculate(rankx(ALL('Dim_Product_Client_Hierarchy'[prod_level_1]), ",
              "if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKU_Product],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKU_Product],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKU_Product]",
              "                    ), [Sales_SKU_Product])))",
              "var Rank_SKU_Product_L2 = calculate(rankx(ALL('Dim_Product_Client_Hierarchy'[prod_level_2]), ",
              "if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKU_Product],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKU_Product],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKU_Product]",
              "                    ), [Sales_SKU_Product])))",
              "var Rank_SKU_Product_L3 = calculate(rankx(ALL('Dim_Product_Client_Hierarchy'[prod_level_3]), ",
              "if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKU_Product],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKU_Product],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKU_Product]",
              "                    ), [Sales_SKU_Product])))",
              "var Rank_SKU_Product_L4 = calculate(rankx(ALL('Dim_Product_Client_Hierarchy'[prod_level_4]), ",
              "if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKU_Product],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKU_Product],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKU_Product]",
              "                    ), [Sales_SKU_Product])))",
              "var Rank_SKU_Product_L5 = calculate(rankx(ALL('Dim_Product_Client_Hierarchy'[prod_level_5]), ",
              "if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKU_Product],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKU_Product],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKU_Product]",
              "                    ), [Sales_SKU_Product])))",
              "",
              "return if([Sales_SKU_Product] <> 0, Switch(True(),",
              "[Filter_SKUName],[Rank_SKU_Product_Pack],",
              "[Filter_Prod_L5], Rank_SKU_Product_L5,",
              "[Filter_Prod_L4], Rank_SKU_Product_L4,",
              "[Filter_Prod_L3], Rank_SKU_Product_L3,",
              "[Filter_Prod_L2], Rank_SKU_Product_L2,",
              "[Filter_Prod_L1], Rank_SKU_Product_L1,",
              "Blank()), blank())",
              ""
            ],
            "formatString": "0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Sales_SKU_Market_TnB",
            "expression": "calculate([Sales_SKU_Period], ALL(Dim_Product_Client_Top_Analysis[top_items]))",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "LY_Sales_SKU_Market_TnB",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var last_year = calculate(values('Dim_Period'[MAT_year]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) - 1",
              "var seq = calculate(values('Dim_Period'[period_seq]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod))",
              "",
              "return calculate([Sales_SKU_Market_TnB], filter(all('Dim_Period'), Dim_Period[MAT_year] = last_year && 'Dim_Period'[period_seq] = seq && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "LP_Sales_SKU_Market_TnB",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var num = calculate(values('Dim_Period'[period_num]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) + 1",
              "",
              "return calculate([Sales_SKU_Market_TnB], filter(all('Dim_Period'), 'Dim_Period'[period_num] = num && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "PP_Sales_SKU_Market_TnB",
            "expression": "if(HASONEVALUE(AUX_Previous_Period[name]), SWITCH(TRUE(), values(AUX_Previous_Period[name]) = \"LY\", [LY_Sales_SKU_Market_TnB], [LP_Sales_SKU_Market_TnB]), [LY_Sales_SKU_Market_TnB])",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "MAT_Sales_SKU_Period",
            "expression": "calculate([Sales_SKU_Period], filter(ALL(Dim_Period), 'Dim_Period'[Period_Type] = \"MAT\"))",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "P_Dummy",
            "expression": "calculate(max('Dim_Period'[period_start]), all('Dim_Period'[Period_Type]))",
            "formatString": "General Date",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"3081\" Group=\"GeneralDateTimeLong\" FormatString=\"G\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "name": "P_Dummy_2",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var num = calculate(values('Dim_Period'[period_num]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) + 1",
              "return num"
            ],
            "formatString": "0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Sales_SKU_Period_CTD",
            "expression": [
              "",
              "var pt = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start_day]), filter(ALL('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = pt))",
              "var c_date_num = calculate(max('Dim_Period'[weekdatenumber]), filter(all('Dim_Period'), 'Dim_Period'[Period_Type] = pt && 'Dim_Period'[period_start_day] = currentperiod))",
              "var c_year = calculate(max('Dim_Period'[MAT_year]), filter(all('Dim_Period'), 'Dim_Period'[Period_Type] = pt && 'Dim_Period'[period_start_day] = currentperiod))",
              "var start_period = calculate(min('Dim_Period'[period_start_day]), filter(all('Dim_Period'), 'Dim_Period'[Period_Type] = pt && 'Dim_Period'[MAT_year] = c_year))",
              "",
              "return CALCULATE([Sales_SKU_Base], filter(all(Dim_Period), 'Dim_Period'[Period_Type] = pt && 'Dim_Period'[period_start_day] >= start_period && 'Dim_Period'[period_start_day] <= currentperiod))"
            ],
            "formatString": "#,0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" ThousandSeparator=\"True\" />"
              }
            ]
          },
          {
            "name": "Sales_SKU_Period_Base",
            "expression": [
              "",
              "var pt = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = pt))",
              "var sales_period_normal = CALCULATE([Sales_SKU_Base], filter(all(Dim_Period), 'Dim_Period'[Period_Type] = pt && 'Dim_Period'[period_start] = currentperiod))",
              "",
              "return sales_period_normal"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "LY_Sales_SKU_Period_base",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var last_year = calculate(values('Dim_Period'[MAT_year]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) - 1",
              "var seq = calculate(values('Dim_Period'[period_seq]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod))",
              "",
              "return calculate([Sales_SKU_Period_Base], filter(all('Dim_Period'), Dim_Period[MAT_year] = last_year && 'Dim_Period'[period_seq] = seq && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "LY_Sales_SKU_Period_CTD",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start_day]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var last_year = calculate(values('Dim_Period'[MAT_year]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start_day] = currentperiod)) - 1",
              "var seq = calculate(values('Dim_Period'[weekdatenumber]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod))",
              "",
              "return calculate([Sales_SKU_Period_CTD], filter(all('Dim_Period'), Dim_Period[MAT_year] = last_year && 'Dim_Period'[weekdatenumber] = seq && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "d7a15bcf-2e4a-4983-a1be-b809fcec1aea"
          },
          {
            "name": "LinkedQueryName",
            "value": "Fact_Sales_Metrics_SKU"
          },
          {
            "name": "PBI_QueryRelationships",
            "value": "{\"columnCount\":1,\"keyColumnNames\":[],\"queryRelationships\":[],\"columnIdentities\":[\"Section1/Fact_Sales_Metrics_SKU/Changed Type.{Metrics,0}\"],\"ColumnCount\":1,\"KeyColumnNames\":[],\"ColumnIdentities\":[\"Section1/Fact_Sales_Metrics_SKU/Changed Type.{Metrics,0}\"],\"RelationshipInfo\":[]}"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Dim_Product_Client_Hierarchy",
        "isHidden": true,
        "columns": [
          {
            "name": "prod_level_1",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "prod_level_1",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "prod_level_1"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "prod_level_2",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "prod_level_2",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "prod_level_2"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "prod_level_3",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "prod_level_3",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "prod_level_3"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "prod_level_4",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "prod_level_4",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "prod_level_4"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "prod_level_5",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "prod_level_5",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "prod_level_5"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "hierarchy_id",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "hierarchy_id",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "hierarchy_id"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "product_client_id",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "product_client_id",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "product_client_id"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "pack_name",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "pack_name",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "pack_name"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Dim_Product_Client_Hierarchy-92ae801e-c48f-47bd-883d-639a20eaed4e",
            "mode": "import",
            "source": {
              "type": "query",
              "query": "SELECT * FROM [Dim_Product_Client_Hierarchy]",
              "dataSource": "acd0870d-7a81-4de3-8913-52efde558c05"
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "c3659b69-321f-497a-97e5-ffeb566edc08"
          },
          {
            "name": "LinkedQueryName",
            "value": "Dim_Product_Client_Hierarchy"
          },
          {
            "name": "PBI_QueryRelationships",
            "value": "{\"columnCount\":8,\"keyColumnNames\":[],\"queryRelationships\":[],\"columnIdentities\":[\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Product_Client_Hierarchy.{product_client_id,0}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Product_Client_Hierarchy.{pack_name,1}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Product_Client_Hierarchy.{prod_level_1,2}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Product_Client_Hierarchy.{prod_level_2,3}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Product_Client_Hierarchy.{prod_level_3,4}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Product_Client_Hierarchy.{prod_level_4,5}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Product_Client_Hierarchy.{prod_level_5,6}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Product_Client_Hierarchy.{hierarchy_id,7}\"],\"ColumnCount\":8,\"KeyColumnNames\":[],\"ColumnIdentities\":[\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Product_Client_Hierarchy.{product_client_id,0}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Product_Client_Hierarchy.{pack_name,1}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Product_Client_Hierarchy.{prod_level_1,2}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Product_Client_Hierarchy.{prod_level_2,3}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Product_Client_Hierarchy.{prod_level_3,4}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Product_Client_Hierarchy.{prod_level_4,5}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Product_Client_Hierarchy.{prod_level_5,6}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Product_Client_Hierarchy.{hierarchy_id,7}\"],\"RelationshipInfo\":[]}"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Dim_Hierarchy_Name_Product",
        "columns": [
          {
            "name": "hierarchy_id",
            "dataType": "int64",
            "sourceColumn": "hierarchy_id",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "hierarchy_id"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "client_number",
            "dataType": "int64",
            "sourceColumn": "client_number",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "client_number"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "hierarchy_name",
            "dataType": "string",
            "sourceColumn": "hierarchy_name",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "hierarchy_name"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Dim_Hierarchy_Name_Product-421bfd2d-7cb4-4435-b8f6-c792a398f312",
            "mode": "import",
            "source": {
              "type": "query",
              "query": "SELECT * FROM [Dim_Hierarchy_Name_Product]",
              "dataSource": "b8df250c-b1c5-499c-9f69-ef10439446c7"
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "36dae229-0721-4c61-89cb-5ac2de36044e"
          },
          {
            "name": "LinkedQueryName",
            "value": "Dim_Hierarchy_Name_Product"
          },
          {
            "name": "PBI_QueryRelationships",
            "value": "{\"columnCount\":3,\"keyColumnNames\":[],\"queryRelationships\":[],\"columnIdentities\":[\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Hierarchy_Name_Product.{hierarchy_id,0}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Hierarchy_Name_Product.{client_number,1}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Hierarchy_Name_Product.{hierarchy_name,2}\"],\"ColumnCount\":3,\"KeyColumnNames\":[],\"ColumnIdentities\":[\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Hierarchy_Name_Product.{hierarchy_id,0}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Hierarchy_Name_Product.{client_number,1}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Hierarchy_Name_Product.{hierarchy_name,2}\"],\"RelationshipInfo\":[]}"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Dim_Hierarchy_Level_Name_Product",
        "isHidden": true,
        "columns": [
          {
            "name": "client_number",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "client_number",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "client_number"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "client_name",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "client_name",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "client_name"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "hierarchy_name",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "hierarchy_name",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "hierarchy_name"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "level",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "level",
            "formatString": "0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "level"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "level_name",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "level_name",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "level_name"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "MarketLevel",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "MarketLevel",
            "formatString": "0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "MarketLevel"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Dim_Hierarchy_Level_Name_Product-5513fc25-6f64-4264-b8fb-f47ac3aaf1fd",
            "mode": "import",
            "source": {
              "type": "query",
              "query": "SELECT * FROM [Dim_Hierarchy_Level_Name_Product]",
              "dataSource": "b736716f-b6ee-48c5-8351-489cc0ce7490"
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "495410a5-5757-4745-a8f7-26c44f6b2094"
          },
          {
            "name": "LinkedQueryName",
            "value": "Dim_Hierarchy_Level_Name_Product"
          },
          {
            "name": "PBI_QueryRelationships",
            "value": "{\"columnCount\":6,\"keyColumnNames\":[],\"queryRelationships\":[],\"columnIdentities\":[\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Hierarchy_Level_Name_Product.{client_number,0}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Hierarchy_Level_Name_Product.{client_name,1}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Hierarchy_Level_Name_Product.{hierarchy_name,2}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Hierarchy_Level_Name_Product.{level,3}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Hierarchy_Level_Name_Product.{level_name,4}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Hierarchy_Level_Name_Product.{MarketLevel,5}\"],\"ColumnCount\":6,\"KeyColumnNames\":[],\"ColumnIdentities\":[\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Hierarchy_Level_Name_Product.{client_number,0}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Hierarchy_Level_Name_Product.{client_name,1}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Hierarchy_Level_Name_Product.{hierarchy_name,2}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Hierarchy_Level_Name_Product.{level,3}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Hierarchy_Level_Name_Product.{level_name,4}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Hierarchy_Level_Name_Product.{MarketLevel,5}\"],\"RelationshipInfo\":[]}"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Dim_Product_Coding_Source",
        "isHidden": true,
        "columns": [
          {
            "name": "product_source_id",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "product_source_id",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "product_source_id"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "product_coding_source",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "product_coding_source",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "product_coding_source"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Dim_Product_Coding_Source-fc59ca36-0e44-4c3b-82e8-7bb5ad658c49",
            "mode": "import",
            "source": {
              "type": "query",
              "query": "SELECT * FROM [Dim_Product_Coding_Source]",
              "dataSource": "b4434604-f94f-4808-bc51-8edf0b4a6484"
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "1b60cb5d-dbcd-484e-9ca1-030db2a963bb"
          },
          {
            "name": "LinkedQueryName",
            "value": "Dim_Product_Coding_Source"
          },
          {
            "name": "PBI_QueryRelationships",
            "value": "{\"columnCount\":2,\"keyColumnNames\":[],\"queryRelationships\":[],\"columnIdentities\":[\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Product_Coding_Source.{product_source_id,0}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Product_Coding_Source.{product_coding_source,1}\"],\"ColumnCount\":2,\"KeyColumnNames\":[],\"ColumnIdentities\":[\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Product_Coding_Source.{product_source_id,0}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Product_Coding_Source.{product_coding_source,1}\"],\"RelationshipInfo\":[]}"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Dim_Product_Client",
        "columns": [
          {
            "name": "cw_pack_key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "cw_pack_key",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "cw_pack_key"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "product_code",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "product_code",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "product_code"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Brand",
            "dataType": "string",
            "sourceColumn": "Brand",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Brand"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Sub_brand",
            "dataType": "string",
            "sourceColumn": "Sub_brand",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Sub_brand"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Manufacturer",
            "dataType": "string",
            "sourceColumn": "Manufacturer",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Manufacturer"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "client_category_id",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "client_category_id",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "client_category_id"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "product_ownership_id",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "product_ownership_id",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "product_ownership_id"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Segment",
            "dataType": "string",
            "sourceColumn": "Segment",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Segment"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Sub_segment",
            "dataType": "string",
            "sourceColumn": "Sub_segment",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Sub_segment"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "product_source_id",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "product_source_id",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "product_source_id"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "client_number",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "client_number",
            "formatString": "0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "client_number"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "product_client_id",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "product_client_id",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "product_client_id"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Pack",
            "dataType": "string",
            "sourceColumn": "Pack",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Pack"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Age",
            "dataType": "string",
            "sourceColumn": "Age",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Age"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Form",
            "dataType": "string",
            "sourceColumn": "Form",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Form"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Ingredient",
            "dataType": "string",
            "sourceColumn": "Ingredient",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Ingredient"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Dim_Product_Client-dd068bbc-fe9c-4f70-b97f-5058d80f5f08",
            "mode": "import",
            "source": {
              "type": "query",
              "query": "SELECT * FROM [Dim_Product_Client]",
              "dataSource": "69a12b0a-3020-45a8-b5bb-16baa3ea4a1e"
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "968bd3b9-c3d8-41e9-8d4a-04f02faa8800"
          },
          {
            "name": "LinkedQueryName",
            "value": "Dim_Product_Client"
          },
          {
            "name": "PBI_QueryRelationships",
            "value": "{\"columnCount\":13,\"keyColumnNames\":[],\"queryRelationships\":[],\"columnIdentities\":[\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Product_Client.{cw_pack_key,0}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Product_Client.{product_code,1}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Product_Client.{pack,2}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Product_Client.{brand,3}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Product_Client.{sub_brand,4}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Product_Client.{manufacturer,5}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Product_Client.{client_category_id,6}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Product_Client.{product_ownership_id,7}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Product_Client.{segment,8}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Product_Client.{sub_segment,9}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Product_Client.{product_source_id,10}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Product_Client.{client_number,11}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Product_Client.{product_client_id,12}\"],\"ColumnCount\":13,\"KeyColumnNames\":[],\"ColumnIdentities\":[\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Product_Client.{cw_pack_key,0}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Product_Client.{product_code,1}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Product_Client.{pack,2}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Product_Client.{brand,3}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Product_Client.{sub_brand,4}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Product_Client.{manufacturer,5}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Product_Client.{client_category_id,6}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Product_Client.{product_ownership_id,7}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Product_Client.{segment,8}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Product_Client.{sub_segment,9}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Product_Client.{product_source_id,10}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Product_Client.{client_number,11}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Product_Client.{product_client_id,12}\"],\"RelationshipInfo\":[]}"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Dim_Category",
        "columns": [
          {
            "name": "client_category_id",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "client_category_id",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "client_category_id"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "client_number",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "client_number",
            "formatString": "0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "client_number"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Category",
            "dataType": "string",
            "sourceColumn": "Category",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Category"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Dim_Category-bce99e82-4bbe-4d6f-9607-1f4da9be3367",
            "mode": "import",
            "source": {
              "type": "query",
              "query": "SELECT * FROM [Dim_Category]",
              "dataSource": "62c66131-25d4-482d-b62f-75a1b0d4b978"
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "48fcdf05-9315-4a0e-b189-0dd08ac3aff4"
          },
          {
            "name": "LinkedQueryName",
            "value": "Dim_Category"
          },
          {
            "name": "PBI_QueryRelationships",
            "value": "{\"columnCount\":3,\"keyColumnNames\":[],\"queryRelationships\":[],\"columnIdentities\":[\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Category_Client.{client_category_id,0}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Category_Client.{client_number,1}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Category_Client.{client_category,2}\"],\"ColumnCount\":3,\"KeyColumnNames\":[],\"ColumnIdentities\":[\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Category_Client.{client_category_id,0}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Category_Client.{client_number,1}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Category_Client.{client_category,2}\"],\"RelationshipInfo\":[]}"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Dim_Geography",
        "columns": [
          {
            "name": "geography_name_id",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "geography_name_id",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "geography_name_id"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "geography_id",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "geography_id",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "geography_id"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Geography_Name",
            "dataType": "string",
            "sourceColumn": "Geography_Name",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Geography_Name"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Members",
            "dataType": "int64",
            "sourceColumn": "Members",
            "formatString": "0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Members"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "display_yn",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "display_yn",
            "formatString": "0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "display_yn"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Area",
            "dataType": "double",
            "sourceColumn": "Area",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Double#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Area"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Long",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Long",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Double#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Long"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Lat",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Lat",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Double#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Lat"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "State",
            "dataType": "string",
            "sourceColumn": "State",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "State"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Store_Num",
            "dataType": "int64",
            "sourceColumn": "Store_Num",
            "formatString": "0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Store_Num"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Population",
            "dataType": "double",
            "sourceColumn": "Population",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Double#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Population"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Pop_Density",
            "dataType": "double",
            "sourceColumn": "Pop_Density",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Double#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Pop_Density"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Pop_per_Store",
            "dataType": "double",
            "sourceColumn": "Pop_per_Store",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Double#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Pop_per_Store"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "to_display",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "[Geo_Display_Rule]",
            "formatString": "0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Dummy_Value",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "blank()",
            "formatString": "0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Dim_Geography-9751b096-9cef-49f1-b3e4-f954ab8661ea",
            "mode": "import",
            "source": {
              "type": "query",
              "query": "SELECT * FROM [Dim_Geography]",
              "dataSource": "a747a4ed-defc-446d-abcf-3be62a2a0c37"
            }
          }
        ],
        "measures": [
          {
            "name": "Geo_Display_Rule",
            "expression": "if(and([Filter_Outlet_Restriction], values(Dim_Geography[display_yn]) = 0), 0, 1)",
            "formatString": "0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "328ef911-8036-4d9a-bc8b-6d03e1dc4a17"
          },
          {
            "name": "LinkedQueryName",
            "value": "Dim_Geography"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_QueryRelationships",
            "value": "{\"columnCount\":13,\"keyColumnNames\":[],\"queryRelationships\":[],\"columnIdentities\":[\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Geography.{geography_name_id,0}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Geography.{geography_id,1}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Geography.{geography_name,2}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Geography.{members,3}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Geography.{display_yn,4}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Geography.{Area,5}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Geography.{Long,6}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Geography.{Lat,7}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Geography.{State,8}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Geography.{Store_Num,9}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Geography.{Population,10}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Geography.{Pop_Density,11}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Geography.{Pop_per_Store,12}\"],\"ColumnCount\":13,\"KeyColumnNames\":[],\"ColumnIdentities\":[\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Geography.{geography_name_id,0}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Geography.{geography_id,1}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Geography.{geography_name,2}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Geography.{members,3}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Geography.{display_yn,4}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Geography.{Area,5}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Geography.{Long,6}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Geography.{Lat,7}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Geography.{State,8}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Geography.{Store_Num,9}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Geography.{Population,10}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Geography.{Pop_Density,11}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Geography.{Pop_per_Store,12}\"],\"RelationshipInfo\":[]}"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Dim_Geography_Type",
        "columns": [
          {
            "name": "geography_field",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "geography_field",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "geography_field"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Geography_Type",
            "dataType": "string",
            "sourceColumn": "Geography_Type",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Geography_Type"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "geography_id",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "geography_id",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "geography_id"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "item_to_display",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "if([Filter_Outlet_Restriction] && Dim_Geography_Type[geography_field] = \"cw_outlet_name\", 0, 1)",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "geo_to_display",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "if(Dim_Geography_Type[geography_field] in {\"outlet_state\", \"banner_group_name\", \"SUA_NAME\", \"lga_name\"}, 0, if([item_to_display] = 0, 0, 1))",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Dim_Geography_Type-d24f8bd8-4c47-4de5-8fac-9cf56e5657ca",
            "mode": "import",
            "source": {
              "type": "query",
              "query": "SELECT * FROM [Dim_Geography_Type]",
              "dataSource": "4badfd5a-a0ea-4fc1-aec5-647f23d7b0ec"
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "32cdfee7-e9c0-4531-8496-db6d0480b943"
          },
          {
            "name": "LinkedQueryName",
            "value": "Dim_Geography_Type"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_QueryRelationships",
            "value": "{\"columnCount\":3,\"keyColumnNames\":[],\"queryRelationships\":[],\"columnIdentities\":[\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Geography_Selection.{geography_field,0}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Geography_Selection.{geography_display,1}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Geography_Selection.{geography_id,2}\"],\"ColumnCount\":3,\"KeyColumnNames\":[],\"ColumnIdentities\":[\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Geography_Selection.{geography_field,0}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Geography_Selection.{geography_display,1}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Geography_Selection.{geography_id,2}\"],\"RelationshipInfo\":[]}"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "AUX_Filter",
        "isHidden": true,
        "columns": [
          {
            "name": "Filter_Name",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Filter_Name",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Filter_Name"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "AUX_Filter-5e6330d8-7ca3-49a7-8f7c-fe37ad55253d",
            "mode": "import",
            "source": {
              "type": "query",
              "query": "SELECT * FROM [AUX_Filter]",
              "dataSource": "cb30e0f9-efc4-41e0-8385-542b1894f127"
            }
          }
        ],
        "measures": [
          {
            "name": "Filter_Segment",
            "expression": "ISFILTERED('Dim_Product_Client'[Segment])",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Boolean\" />"
              }
            ]
          },
          {
            "name": "Filter_Subsegment",
            "expression": "ISFILTERED('Dim_Product_Client'[Sub_segment])",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Boolean\" />"
              }
            ]
          },
          {
            "name": "Filter_Brand",
            "expression": "ISFILTERED('Dim_Product_Client'[Brand])",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Boolean\" />"
              }
            ]
          },
          {
            "name": "Filter_Subbrand",
            "expression": "isfiltered('Dim_Product_Client'[Sub_brand])",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Boolean\" />"
              }
            ]
          },
          {
            "name": "Filter_Prod_L1",
            "expression": "isfiltered('Dim_Product_Client_Hierarchy'[prod_level_1])",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Boolean\" />"
              }
            ]
          },
          {
            "name": "Filter_Prod_L2",
            "expression": "isfiltered('Dim_Product_Client_Hierarchy'[prod_level_2])",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Boolean\" />"
              }
            ]
          },
          {
            "name": "Filter_Prod_L3",
            "expression": "isfiltered('Dim_Product_Client_Hierarchy'[prod_level_3])",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Boolean\" />"
              }
            ]
          },
          {
            "name": "Filter_Prod_L4",
            "expression": "isfiltered('Dim_Product_Client_Hierarchy'[prod_level_4])",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Boolean\" />"
              }
            ]
          },
          {
            "name": "Filter_Prod_L5",
            "expression": "isfiltered('Dim_Product_Client_Hierarchy'[prod_level_5])",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Boolean\" />"
              }
            ]
          },
          {
            "name": "Filter_SKUName",
            "expression": "ISFILTERED(Dim_Product_Client_Hierarchy[pack_name])",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Boolean\" />"
              }
            ]
          },
          {
            "name": "CrossFilter_Prod_L2",
            "expression": "ISCROSSFILTERED('Dim_Product_Client_Hierarchy'[prod_level_2])",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Boolean\" />"
              }
            ]
          },
          {
            "name": "CrossFilter_SKUName",
            "expression": "ISCROSSFILTERED(Dim_Product_Client_Hierarchy[pack_name])",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Boolean\" />"
              }
            ]
          },
          {
            "name": "CrossFilter_Prod_L1",
            "expression": "ISCROSSFILTERED('Dim_Product_Client_Hierarchy'[prod_level_1])",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Boolean\" />"
              }
            ]
          },
          {
            "name": "CrossFilter_Prod_L3",
            "expression": "ISCROSSFILTERED('Dim_Product_Client_Hierarchy'[prod_level_3])",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Boolean\" />"
              }
            ]
          },
          {
            "name": "CrossFilter_Prod_L4",
            "expression": "ISCROSSFILTERED('Dim_Product_Client_Hierarchy'[prod_level_4])",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Boolean\" />"
              }
            ]
          },
          {
            "name": "CrossFilter_Prod_L5",
            "expression": "ISCROSSFILTERED('Dim_Product_Client_Hierarchy'[prod_level_5])",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Boolean\" />"
              }
            ]
          },
          {
            "name": "Filter_OutletName_cw",
            "expression": "ISFILTERED('Dim_Outlet'[cw_outlet_name])",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Boolean\" />"
              }
            ]
          },
          {
            "name": "Filter_OutletName_iqvia",
            "expression": "ISFILTERED('Dim_Outlet'[iqvia_outlet_name])",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Boolean\" />"
              }
            ]
          },
          {
            "name": "Filter_Outlet_Restriction",
            "expression": "if(values('Client'[outlet_restriction]) = \"Cluster\", TRUE, False)",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Boolean\" />"
              }
            ]
          },
          {
            "name": "TnB_Filter",
            "expression": [
              "if(HASONEVALUE(AUX_ReportTemplate[metric_base]), ",
              "\tSWITCH(TRUE(), ",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKU\", [TnB_Filter_SKU], ",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"Outlet\", [TnB_Filter_Outlet],",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKUOutlet\", [TnB_Filter_SKUOutlet]",
              "\t), ",
              "\t[TnB_Filter_SKU])"
            ],
            "formatString": "0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "TnB_Filter_Label",
            "expression": [
              "if(HASONEVALUE(AUX_ReportTemplate[metric_base]), ",
              "\tSWITCH(TRUE(), ",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKU\", [TnB_Filter_SKU_Label], ",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"Outlet\", [TnB_Filter_Outlet_Label],",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKUOutlet\", [TnB_Filter_SKUOutlet_Label]",
              "\t), ",
              "\t[TnB_Filter_SKU_Label])"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "TnB_Filter_Value",
            "expression": [
              "if(HASONEVALUE(AUX_ReportTemplate[metric_base]), ",
              "\tSWITCH(TRUE(), ",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKU\", [TnB_Filter_SKU_Value], ",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"Outlet\", [TnB_Filter_Outlet_Value],",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKUOutlet\", [TnB_Filter_SKUOutlet_Value]",
              "\t), ",
              "\t[TnB_Filter_SKU_Value])"
            ],
            "formatString": "0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Top_Filter_Prod",
            "expression": [
              "if(HASONEVALUE(AUX_ReportTemplate[metric_base]), ",
              "\tSWITCH(TRUE(), ",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKU\", [Top_Filter_SKU_Prod], ",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKUOutlet\", [Top_Filter_SKUOutlet_Prod]",
              "\t), ",
              "\t[Top_Filter_SKU_Prod])"
            ],
            "formatString": "0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Filter_ReportUse",
            "expression": "if(SELECTEDVALUE('AUX_ReportTemplate'[report_use], \"All\") = \"Tab\", True(), FALSE())",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Boolean\" />"
              }
            ]
          },
          {
            "name": "Filter_PeriodType",
            "expression": "SELECTEDVALUE('Dim_Period'[Period_Type], \"MAT\")",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "Filter_PeriodLongName_Alone",
            "expression": "ISFILTERED('Dim_Period_Alone'[period_long_name])",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Boolean\" />"
              }
            ]
          },
          {
            "name": "Filter_PeriodColumn_Display",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var latest = calculate(min('Dim_Period'[period_num]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod))",
              "",
              "return if([Filter_PeriodLongName_Alone], 1, if(latest = 1,1,0))"
            ],
            "formatString": "0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Filter_PeriodLongName",
            "expression": "ISFILTERED('Dim_Period'[Period_Long_Name])",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Boolean\" />"
              }
            ]
          },
          {
            "name": "Filter_PeriodType_Alone",
            "expression": "SELECTEDVALUE('Dim_Period_Type'[Period_Type], \"MAT\")",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "Filter_GeographySelection",
            "expression": [
              "",
              "var geo_name = SELECTEDVALUE('Dim_Geography_Type'[Geography_Type], \"CW Brick Name\")",
              "",
              "return if(geo_name = \"State\", \"State with Value\", geo_name)"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "Filter_GeoState",
            "expression": "if([Filter_GeographySelection] = \"Remoteness\", \"Remoteness Class\", \"State\")",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "Filter_GeographyName",
            "expression": "ISFILTERED(Dim_Geography[Geography_Name])",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Boolean\" />"
              }
            ]
          },
          {
            "name": "Filter_ClientCategory",
            "expression": "ISFILTERED('Dim_Category'[Category])",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Boolean\" />"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "0efefdde-aa06-45e0-bde9-360dd0b7fda8"
          },
          {
            "name": "LinkedQueryName",
            "value": "AUX_Filter"
          },
          {
            "name": "PBI_QueryRelationships",
            "value": "{\"columnCount\":1,\"keyColumnNames\":[],\"queryRelationships\":[],\"columnIdentities\":[\"Section1/AUX_Filter/Source.{Filter_Name,0}\"],\"ColumnCount\":1,\"KeyColumnNames\":[],\"ColumnIdentities\":[\"Section1/AUX_Filter/Source.{Filter_Name,0}\"],\"RelationshipInfo\":[]}"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Fact_SKU_Outlet_Sales",
        "isHidden": true,
        "columns": [
          {
            "name": "period_key",
            "dataType": "int64",
            "isHidden": true,
            "isNullable": false,
            "sourceColumn": "period_key",
            "formatString": "0",
            "sourceProviderType": "int",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "period_key"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "cw_pack_key",
            "dataType": "int64",
            "isHidden": true,
            "isNullable": false,
            "sourceColumn": "cw_pack_key",
            "formatString": "0",
            "sourceProviderType": "int",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "cw_pack_key"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "cw_outlet_key",
            "dataType": "int64",
            "isHidden": true,
            "isNullable": false,
            "sourceColumn": "cw_outlet_key",
            "formatString": "0",
            "sourceProviderType": "int",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "cw_outlet_key"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "measure_id",
            "dataType": "int64",
            "isHidden": true,
            "isNullable": false,
            "sourceColumn": "measure_id",
            "formatString": "0",
            "sourceProviderType": "int",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "measure_id"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "market_id",
            "dataType": "int64",
            "isHidden": true,
            "isNullable": false,
            "sourceColumn": "market_id",
            "formatString": "0",
            "sourceProviderType": "int",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "market_id"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "sales",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "sales",
            "formatString": "0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "sales"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Fact_SKU_Outlet_Sales-8a59b07f-9354-4c56-bbe4-41c88cea6e05",
            "mode": "import",
            "source": {
              "type": "query",
              "query": "SELECT * FROM [Fact_SKU_Outlet_Sales]",
              "dataSource": "c3a4813f-679e-4dfe-bad2-4ceb716a8177"
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "f15fe386-e382-409c-bd3b-546a0376be91"
          },
          {
            "name": "LinkedQueryName",
            "value": "Fact_SKU_Outlet_Sales"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_QueryRelationships",
            "value": "{\"columnCount\":6,\"keyColumnNames\":[],\"queryRelationships\":[],\"columnIdentities\":[\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Fact_SKU_Outlet_Sales_MthWk.{period_key,0}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Fact_SKU_Outlet_Sales_MthWk.{cw_pack_key,1}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Fact_SKU_Outlet_Sales_MthWk.{cw_outlet_key,2}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Fact_SKU_Outlet_Sales_MthWk.{measure_id,3}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Fact_SKU_Outlet_Sales_MthWk.{market_id,4}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Fact_SKU_Outlet_Sales_MthWk.{sales,5}\"],\"ColumnCount\":6,\"KeyColumnNames\":[],\"ColumnIdentities\":[\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Fact_SKU_Outlet_Sales_MthWk.{period_key,0}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Fact_SKU_Outlet_Sales_MthWk.{cw_pack_key,1}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Fact_SKU_Outlet_Sales_MthWk.{cw_outlet_key,2}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Fact_SKU_Outlet_Sales_MthWk.{measure_id,3}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Fact_SKU_Outlet_Sales_MthWk.{market_id,4}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Fact_SKU_Outlet_Sales_MthWk.{sales,5}\"],\"RelationshipInfo\":[]}"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "AUX_Previous_Period",
        "isHidden": true,
        "columns": [
          {
            "name": "name",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "name",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "name"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "definition",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "definition",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "definition"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "display",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "display",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "display"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "p_period_type",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "p_period_type",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "p_period_type"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "AUX_Previous_Period-2994c309-c620-4a19-8685-0b7ff63ed990",
            "mode": "import",
            "source": {
              "type": "query",
              "query": "SELECT * FROM [AUX_Previous_Period]",
              "dataSource": "affc23e0-cd1f-4663-ae15-7b01be90c995"
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "01c15210-dd63-4b79-b1ca-fa23854ca0fb"
          },
          {
            "name": "LinkedQueryName",
            "value": "AUX_Previous_Period"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_QueryRelationships",
            "value": "{\"columnCount\":4,\"keyColumnNames\":[],\"queryRelationships\":[],\"columnIdentities\":[\"Section1/AUX_Previous_Period/Changed Type.{name,0}\",\"Section1/AUX_Previous_Period/Replaced Value1.{display,1}\",\"Section1/AUX_Previous_Period/Replaced Value2.{definition,2}\",\"Section1/AUX_Previous_Period/Replaced Value3.{p_period_type,3}\"],\"ColumnCount\":4,\"KeyColumnNames\":[],\"ColumnIdentities\":[\"Section1/AUX_Previous_Period/Changed Type.{name,0}\",\"Section1/AUX_Previous_Period/Replaced Value1.{display,1}\",\"Section1/AUX_Previous_Period/Replaced Value2.{definition,2}\",\"Section1/AUX_Previous_Period/Replaced Value3.{p_period_type,3}\"],\"RelationshipInfo\":[]}"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "AUX_Top_Select_Option",
        "isHidden": true,
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "top_option",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[top_option]",
            "sortByColumn": "order",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "order",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[order]",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "AUX_Top_Select_Option-a9ca9b11-cebf-44e7-a34c-01bfc4db883f",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "DATATABLE(  \"top_option\", string,",
                "            \"order\", INTEGER,",
                "            {",
                "                    {\"Value\", 1},",
                "                    {\"Growth\", 2},",
                "                    {\"Growth %\", 3}",
                "            })"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "8239546a3cc147f89102366faed11857"
          }
        ]
      },
      {
        "name": "AUX_Top_Select_Base",
        "isHidden": true,
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "top_base",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[top_base]",
            "sortByColumn": "order",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "order",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[order]",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "AUX_Top_Select_Base-f6a1fa9d-997c-4a39-9ad8-33bef46db382",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "DATATABLE(  \"top_base\", string,",
                "            \"order\", INTEGER,",
                "            {",
                "                    {\"Brand\", 1},",
                "                    {\"Manufacturer\", 2},",
                "                    {\"SKU\", 3}",
                "            })"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "1fe9581996fc47d0b4b8789a0a2f3f3c"
          }
        ]
      },
      {
        "name": "Dim_Product_Client_Top_Analysis",
        "isHidden": true,
        "columns": [
          {
            "name": "top_items",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "top_items",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "top_items"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "top_base",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "top_base",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "top_base"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "product_client_id",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "product_client_id",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "product_client_id"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Dim_Product_Client_Top_Analysis-b155c655-5e44-468a-8127-ba8ae682dc70",
            "mode": "import",
            "source": {
              "type": "query",
              "query": "SELECT * FROM [Dim_Product_Client_Top_Analysis]",
              "dataSource": "6b59a040-c3ef-4d41-af90-8152566c4343"
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "63dd94bc-0632-400a-bea0-8c2e1df4360c"
          },
          {
            "name": "LinkedQueryName",
            "value": "Dim_Product_Client_Top_Analysis"
          },
          {
            "name": "PBI_QueryRelationships",
            "value": "{\"columnCount\":3,\"keyColumnNames\":[],\"queryRelationships\":[],\"columnIdentities\":[\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Product_Client_Top_Analysis.{product_client_id,0}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Product_Client_Top_Analysis.{top_items,1}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Product_Client_Top_Analysis.{top_base,2}\"],\"ColumnCount\":3,\"KeyColumnNames\":[],\"ColumnIdentities\":[\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Product_Client_Top_Analysis.{product_client_id,0}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Product_Client_Top_Analysis.{top_items,1}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Product_Client_Top_Analysis.{top_base,2}\"],\"RelationshipInfo\":[]}"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Fact_Sales_Metrics_Outlet",
        "isHidden": true,
        "columns": [
          {
            "name": "Metrics",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Metrics",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Metrics"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Fact_Sales_Metrics_Outlet-6dfdc8b4-3bb5-407c-9090-b6a838632cb4",
            "mode": "import",
            "source": {
              "type": "query",
              "query": "SELECT * FROM [Fact_Sales_Metrics_Outlet]",
              "dataSource": "25bbd7bf-ed18-4289-8b9d-f45d16ba1578"
            }
          }
        ],
        "measures": [
          {
            "name": "Sales_Outlet_Base",
            "expression": [
              "",
              "var outsales_base = if(countrows('Fact_Outlet_Category_Sales') > 0, (calculate(sum('Fact_Outlet_Category_Sales'[sales]) / 100)))",
              "return if(and(AUX_Filter[Filter_Outlet_Restriction], or([Filter_OutletName_cw], [Filter_OutletName_iqvia])), BLANK(), outsales_base)"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Sales_Outlet_Period",
            "expression": [
              "",
              "var period_base_type = SELECTEDVALUE('Dim_Period'[period_type_base], \"MTH\")",
              "",
              "return if(period_base_type = \"WTD\", [Sales_Outlet_Period_CTD], [Sales_Outlet_Period_Base])"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Sales_Outlet_Market",
            "expression": "[Sales_Outlet_Period]",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Sales_Outlet_Product_Own",
            "expression": "calculate([Sales_Outlet_Period], 'Dim_Product_Ownership'[Product_Ownership] = \"Own Product\")",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Sales_Outlet_Competitor",
            "expression": "if([Sales_Outlet_Product_Own] > 0,  calculate([Sales_Outlet_Period], 'Dim_Product_Ownership'[Product_Ownership] = \"Competitor\"))",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Sales_Outlet_Product",
            "expression": "[Sales_Outlet_Product_Own]",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "MS_Outlet_Product",
            "expression": "DIVIDE([Sales_Outlet_Product], [Sales_Outlet_Market])",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Rank_Outlet_Market",
            "expression": [
              "",
              "var Rank_Outlet_Market = calculate(rankx(ALL('Dim_Geography'[Geography_Name]), ",
              "if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_Outlet_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_Outlet_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_Outlet_Period]",
              "                    ), [Sales_Outlet_Period])))",
              "",
              "return if(countrows('Fact_Outlet_Category_Sales') > 0, Rank_Outlet_Market,",
              "Blank())",
              ""
            ],
            "formatString": "0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Rank_Outlet_Product",
            "expression": [
              "",
              "var Rank_Outlet_Product = calculate(rankx(ALL('Dim_Geography'[Geography_Name]), ",
              "if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_Outlet_Product],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_Outlet_Product],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_Outlet_Product]",
              "                    ), [Sales_Outlet_Product])))",
              "",
              "return if(countrows('Fact_Outlet_Category_Sales') > 0, Rank_Outlet_product,",
              "Blank())"
            ],
            "formatString": "0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "LY_Sales_Outlet_Product",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var last_year = calculate(values('Dim_Period'[MAT_year]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) - 1",
              "var seq = calculate(values('Dim_Period'[period_seq]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod))",
              "",
              "return calculate([Sales_Outlet_Product], filter(all('Dim_Period'), Dim_Period[MAT_year] = last_year && 'Dim_Period'[period_seq] = seq && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "LY_Sales_Outlet_Period",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var last_year = calculate(values('Dim_Period'[MAT_year]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) - 1",
              "var seq = calculate(values('Dim_Period'[period_seq]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod))",
              "",
              "return calculate([Sales_Outlet_Period], filter(all('Dim_Period'), Dim_Period[MAT_year] = last_year && 'Dim_Period'[period_seq] = seq && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "LY_Sales_Outlet_Market",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var last_year = calculate(values('Dim_Period'[MAT_year]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) - 1",
              "var seq = calculate(values('Dim_Period'[period_seq]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod))",
              "",
              "return calculate([Sales_Outlet_Market], filter(all('Dim_Period'), Dim_Period[MAT_year] = last_year && 'Dim_Period'[period_seq] = seq && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "LY_Sales_Outlet_Competitor",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var last_year = calculate(values('Dim_Period'[MAT_year]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) - 1",
              "var seq = calculate(values('Dim_Period'[period_seq]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod))",
              "",
              "return calculate([Sales_Outlet_Competitor], filter(all('Dim_Period'), Dim_Period[MAT_year] = last_year && 'Dim_Period'[period_seq] = seq && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "LY_MS_Outlet_Product",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var last_year = calculate(values('Dim_Period'[MAT_year]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) - 1",
              "var seq = calculate(values('Dim_Period'[period_seq]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod))",
              "",
              "return calculate([MS_Outlet_Product], filter(all('Dim_Period'), Dim_Period[MAT_year] = last_year && 'Dim_Period'[period_seq] = seq && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "YOY_EI_Outlet",
            "expression": "DIVIDE([MS_Outlet_Product],[LY_MS_Outlet_Product],BLANK())*100",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "YOY_Gth_%_Outlet_Product",
            "expression": "divide([YOY_Gth_Outlet_Product] , [LY_Sales_Outlet_Product])",
            "isHidden": true
          },
          {
            "name": "YOY_Gth_Outlet_Market",
            "expression": "[Sales_Outlet_Market] - [LY_Sales_Outlet_Market]",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "YOY_Gth_Outlet_Product",
            "expression": "[Sales_Outlet_Product] - [LY_Sales_Outlet_Product]",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "YOY_MS_Change_Outlet",
            "expression": "[MS_Outlet_Product] - [LY_MS_Outlet_Product]",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "LY_Gth_%_Outlet_Product",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var last_year = calculate(values('Dim_Period'[MAT_year]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) - 1",
              "var seq = calculate(values('Dim_Period'[period_seq]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod))",
              "",
              "return calculate([YOY_Gth_%_Outlet_Product], filter(all('Dim_Period'), Dim_Period[MAT_year] = last_year && 'Dim_Period'[period_seq] = seq && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "LP_MS_Outlet_Product",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var num = calculate(values('Dim_Period'[period_num]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) + 1",
              "",
              "return calculate([MS_Outlet_Product], filter(all('Dim_Period'), 'Dim_Period'[period_num] = num && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "LP_Sales_Outlet_Product",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var num = calculate(values('Dim_Period'[period_num]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) + 1",
              "",
              "return calculate([Sales_Outlet_Product], filter(all('Dim_Period'), 'Dim_Period'[period_num] = num && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "LP_Sales_Outlet_Period",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var num = calculate(values('Dim_Period'[period_num]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) + 1",
              "",
              "return calculate([Sales_Outlet_Period], filter(all('Dim_Period'), 'Dim_Period'[period_num] = num && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "LP_Sales_Outlet_Market",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var num = calculate(values('Dim_Period'[period_num]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) + 1",
              "",
              "return calculate([Sales_Outlet_Market], filter(all('Dim_Period'), 'Dim_Period'[period_num] = num && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "LP_Sales_Outlet_Competitor",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var num = calculate(values('Dim_Period'[period_num]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) + 1",
              "",
              "return calculate([Sales_Outlet_Competitor], filter(all('Dim_Period'), 'Dim_Period'[period_num] = num && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "POP_MS_Change_Outlet",
            "expression": "[MS_Outlet_Product] - [LP_MS_Outlet_Product]",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "POP_Gth_Outlet_Product",
            "expression": "[Sales_Outlet_Product] - [LP_Sales_Outlet_Product]",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "POP_Gth_Outlet_Market",
            "expression": "[Sales_Outlet_Market] - [LP_Sales_Outlet_Market]",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "POP_Gth_%_Outlet_Product",
            "expression": "divide([POP_Gth_Outlet_Product] , [LP_Sales_Outlet_Product])",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "POP_EI_Outlet",
            "expression": "DIVIDE([MS_Outlet_Product],[LP_MS_Outlet_Product],BLANK())*100",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "MAT_Gth_%_Outlet_Product",
            "expression": "calculate([YOY_Gth_%_Outlet_Product], filter(ALL(Dim_Period), 'Dim_Period'[Period_Type] = \"MAT\"))",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "MAT_MS_Change_Outlet",
            "expression": "calculate([YOY_MS_Change_Outlet], filter(ALL(Dim_Period), 'Dim_Period'[Period_Type] = \"MAT\"))",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "MAT_MS_Outlet_Product",
            "expression": "calculate([MS_Outlet_Product], filter(ALL(Dim_Period), 'Dim_Period'[Period_Type] = \"MAT\"))",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "MAT_Sales_Outlet_Market",
            "expression": "calculate([Sales_Outlet_Market], filter(ALL(Dim_Period), 'Dim_Period'[Period_Type] = \"MAT\"))",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "MAT_Sales_Outlet_Product",
            "expression": "calculate([Sales_Outlet_Product], filter(ALL(Dim_Period), 'Dim_Period'[Period_Type] = \"MAT\"))",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "YTD_Gth_%_Outlet_Product",
            "expression": "calculate([YOY_Gth_%_Outlet_Product], filter(ALL(Dim_Period), 'Dim_Period'[Period_Type] = \"YTD\"))",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "YTD_MS_Change_Outlet",
            "expression": "calculate([YOY_MS_Change_Outlet], filter(ALL(Dim_Period), 'Dim_Period'[Period_Type] = \"YTD\"))",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "YTD_MS_Outlet_Product",
            "expression": "calculate([MS_Outlet_Product], filter(ALL(Dim_Period), 'Dim_Period'[Period_Type] = \"YTD\"))",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "YTD_Sales_Outlet_Market",
            "expression": "calculate([Sales_Outlet_Market], filter(ALL(Dim_Period), 'Dim_Period'[Period_Type] = \"YTD\"))",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "YTD_Sales_Outlet_Product",
            "expression": "calculate([Sales_Outlet_Product], filter(ALL(Dim_Period), 'Dim_Period'[Period_Type] = \"YTD\"))",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "PP_Sales_Outlet_Product",
            "expression": "if(HASONEVALUE(AUX_Previous_Period[name]), SWITCH(TRUE(), values(AUX_Previous_Period[name]) = \"LY\", [LY_Sales_Outlet_Product], [LP_Sales_Outlet_Product]), [LY_Sales_Outlet_Product])",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "PP_Sales_Outlet_Period",
            "expression": "if(HASONEVALUE(AUX_Previous_Period[name]), SWITCH(TRUE(), values(AUX_Previous_Period[name]) = \"LY\", [LY_Sales_Outlet_Period], [LP_Sales_Outlet_Period]), [LY_Sales_Outlet_Period])",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "PP_Sales_Outlet_Market",
            "expression": "if(HASONEVALUE(AUX_Previous_Period[name]), SWITCH(TRUE(), values(AUX_Previous_Period[name]) = \"LY\", [LY_Sales_Outlet_Market], [LP_Sales_Outlet_Market]), [LY_Sales_Outlet_Market])",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "PP_Sales_Outlet_Competitor",
            "expression": "if(HASONEVALUE(AUX_Previous_Period[name]), SWITCH(TRUE(), values(AUX_Previous_Period[name]) = \"LY\", [LY_Sales_Outlet_Competitor], [LP_Sales_Outlet_Competitor]), [LY_Sales_Outlet_Competitor])",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "PP_MS_Outlet_Product",
            "expression": "if(HASONEVALUE(AUX_Previous_Period[name]), SWITCH(TRUE(), values(AUX_Previous_Period[name]) = \"LY\", [LY_MS_Outlet_Product], [LP_MS_Outlet_Product]), [LY_MS_Outlet_Product])",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Gth_Outlet_Product",
            "expression": "if(isblank([PP_Sales_Outlet_Product]), blank(), [Sales_Outlet_Product] - [PP_Sales_Outlet_Product])",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Gth_Outlet_Period",
            "expression": "if(isblank([PP_Sales_Outlet_Period]), blank(), [Sales_Outlet_Period] - [PP_Sales_Outlet_Period])",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Gth_Outlet_Market",
            "expression": "if(isblank([PP_Sales_Outlet_Market]), blank(), [Sales_Outlet_Market] - [PP_Sales_Outlet_Market])",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Gth_%_Outlet_Product",
            "expression": "divide([Gth_Outlet_Product] , [PP_Sales_Outlet_Product])",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Gth_%_Outlet_Period",
            "expression": "divide([Gth_Outlet_Period] , [PP_Sales_Outlet_Period])",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Gth_%_Outlet_Market",
            "expression": "divide([Gth_Outlet_Market] , [PP_Sales_Outlet_Market])",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "MS_Change_Outlet",
            "expression": "[MS_Outlet_Product] - [PP_MS_Outlet_Product]",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "TnB_Filter_Outlet",
            "expression": [
              "",
              "var top_brand = calculatetable(",
              "    TOPN(values('AUX_Top_Selection_Prod'[Top_Value]),",
              "    CALCULATETABLE(VALUES('Dim_Geography'[Geography_Name]), 'Dim_Geography_Type'[Geography_Type] = values(Dim_Geography_Type[Geography_Type])),",
              "    if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_Outlet_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_Outlet_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_Outlet_Period]",
              "                    ), [Sales_Outlet_Period]), 0",
              "    )",
              "    , ALLSELECTED()",
              ")",
              "",
              "var bot_brand = calculatetable(",
              "    TOPN(values('AUX_Top_Selection_Prod'[Top_Value]),",
              "    CALCULATETABLE(VALUES('Dim_Geography'[Geography_Name]), 'Dim_Geography_Type'[Geography_Type] = values(Dim_Geography_Type[Geography_Type])),",
              "    if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_Outlet_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_Outlet_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_Outlet_Period]",
              "                    ), [Sales_Outlet_Period]), 1",
              "    )",
              "    , ALLSELECTED()",
              ")",
              "",
              "var tnb_union = UNION(top_brand,bot_brand)",
              "",
              "var top_only = CALCULATE(",
              "    1 * (NOT ISEMPTY('Dim_Geography')),",
              "    KEEPFILTERS(top_brand)",
              ")",
              "",
              "var bot_only = CALCULATE(",
              "    1 * (NOT ISEMPTY('Dim_Geography')),",
              "    KEEPFILTERS(bot_brand)",
              ")",
              "",
              "var tnb_both = CALCULATE(",
              "    1 * (NOT ISEMPTY('Dim_Geography')),",
              "    KEEPFILTERS(tnb_union)",
              ")",
              "",
              "return if(HASONEVALUE(AUX_Top_Selection_Prod[Top_Type]), switch(TRUE(),",
              "                                    values(AUX_Top_Selection_Prod[Top_Type]) = \"Top\", top_only,",
              "                                    values(AUX_Top_Selection_Prod[Top_Type]) = \"Bottom\", bot_only,",
              "                                    values(AUX_Top_Selection_Prod[Top_Type]) = \"TnB\", tnb_both,",
              "                                    top_only",
              "                                    ),",
              "                                    top_only)"
            ],
            "formatString": "0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "TnB_Filter_Outlet_Label",
            "expression": [
              "",
              "var top_brand = calculatetable(",
              "    TOPN(values('AUX_Top_Selection_Prod'[Top_Value]),",
              "    CALCULATETABLE(VALUES('Dim_Geography'[Geography_Name])),",
              "    if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_Outlet_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_Outlet_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_Outlet_Period]",
              "                    ), [Sales_Outlet_Period]), 0",
              "    )",
              "    , ALLSELECTED()",
              ")",
              "",
              "var bot_brand = calculatetable(",
              "    TOPN(values('AUX_Top_Selection_Prod'[Top_Value]),",
              "    CALCULATETABLE(VALUES('Dim_Geography'[Geography_Name])),",
              "    if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_Outlet_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_Outlet_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_Outlet_Period]",
              "                    ), [Sales_Outlet_Period]), 1",
              "    )",
              "    , ALLSELECTED()",
              ")",
              "",
              "var top_only = CALCULATE(",
              "    1 * (NOT ISEMPTY('Dim_Geography')),",
              "    KEEPFILTERS(top_brand)",
              ")",
              "",
              "var bot_only = CALCULATE(",
              "    1 * (NOT ISEMPTY('Dim_Geography')),",
              "    KEEPFILTERS(bot_brand)",
              ")",
              "",
              "return if(HASONEVALUE(AUX_Top_Selection_Prod[Top_Type]), switch(TRUE(),",
              "                                    top_only = 1, \"Top\",",
              "                                    bot_only = 1, \"Bottom\"",
              "                                    ))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "TnB_Filter_Outlet_Value",
            "expression": [
              "",
              "var top_brand = calculatetable(",
              "    TOPN(values('AUX_Top_Selection_Prod'[Top_Value]),",
              "    CALCULATETABLE(VALUES('Dim_Geography'[Geography_Name])),",
              "    if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_Outlet_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_Outlet_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_Outlet_Period]",
              "                    ), [Sales_Outlet_Period]), 0",
              "    )",
              "    , ALLSELECTED()",
              ")",
              "",
              "var bot_brand = calculatetable(",
              "    TOPN(values('AUX_Top_Selection_Prod'[Top_Value]),",
              "    CALCULATETABLE(VALUES('Dim_Geography'[Geography_Name])),",
              "    if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_Outlet_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_Outlet_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_Outlet_Period]",
              "                    ), [Sales_Outlet_Period]), 1",
              "    )",
              "    , ALLSELECTED()",
              ")",
              "",
              "var top_only = CALCULATE(",
              "    1 * (NOT ISEMPTY('Dim_Geography')),",
              "    KEEPFILTERS(top_brand)",
              ")",
              "",
              "var bot_only = CALCULATE(",
              "    1 * (NOT ISEMPTY('Dim_Geography')),",
              "    KEEPFILTERS(bot_brand)",
              ")",
              "",
              "return if(HASONEVALUE(AUX_Top_Selection_Prod[Top_Type]), switch(TRUE(),",
              "                                    top_only = 1, 1,",
              "                                    bot_only = 1, -1",
              "                                    ))"
            ],
            "formatString": "0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "EI_Outlet",
            "expression": "if(HASONEVALUE(AUX_Previous_Period[name]), SWITCH(TRUE(), values(AUX_Previous_Period[name]) = \"LY\", [YOY_EI_Outlet], [POP_EI_Outlet]), [YOY_EI_Outlet])",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Sales_Outlet_Market_TnB",
            "expression": "calculate([Sales_Outlet_Period], ALL(Dim_Geography[Geography_Name]))",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "LY_Sales_Outlet_Market_TnB",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var last_year = calculate(values('Dim_Period'[MAT_year]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) - 1",
              "var seq = calculate(values('Dim_Period'[period_seq]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod))",
              "",
              "return calculate([Sales_Outlet_Market_TnB], filter(all('Dim_Period'), Dim_Period[MAT_year] = last_year && 'Dim_Period'[period_seq] = seq && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "LP_Sales_Outlet_Market_TnB",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var num = calculate(values('Dim_Period'[period_num]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) + 1",
              "",
              "return calculate([Sales_Outlet_Market_TnB], filter(all('Dim_Period'), 'Dim_Period'[period_num] = num && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "PP_Sales_Outlet_Market_TnB",
            "expression": "if(HASONEVALUE(AUX_Previous_Period[name]), SWITCH(TRUE(), values(AUX_Previous_Period[name]) = \"LY\", [LY_Sales_Outlet_Market_TnB], [LP_Sales_Outlet_Market_TnB]), [LY_Sales_Outlet_Market_TnB]) ",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "TnB_Filter_Outlet_1",
            "expression": [
              "",
              "var top_geo = calculatetable(",
              "    TOPN(values('AUX_Top_Selection_Prod'[Top_Value]),",
              "    CALCULATETABLE(VALUES('Dim_Geography'[Geography_Name]), 'Dim_Geography_Type'[Geography_Type] = values(Dim_Geography_Type[Geography_Type])),",
              "    if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_Outlet_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_Outlet_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_Outlet_Period]",
              "                    ), [Sales_Outlet_Period]), 0",
              "    )",
              "    , ALLSELECTED()",
              ")",
              "",
              "var bot_geo = calculatetable(",
              "    TOPN(values('AUX_Top_Selection_Prod'[Top_Value]),",
              "    CALCULATETABLE(VALUES('Dim_Geography'[Geography_Name]), 'Dim_Geography_Type'[Geography_Type] = values(Dim_Geography_Type[Geography_Type])),",
              "    if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_Outlet_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_Outlet_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_Outlet_Period]",
              "                    ), [Sales_Outlet_Period]), 1",
              "    )",
              "    , ALLSELECTED()",
              ")",
              "",
              "var tnb_union_geo = UNION(top_geo, bot_geo)",
              "",
              "var top_only = CALCULATE(",
              "    1 * (NOT ISEMPTY('Dim_Geography')),",
              "    KEEPFILTERS(top_geo)",
              ")",
              "",
              "var bot_only = CALCULATE(",
              "    1 * (NOT ISEMPTY('Dim_Geography')),",
              "    KEEPFILTERS(bot_geo)",
              ")",
              "",
              "var tnb_both = CALCULATE(",
              "    1 * (NOT ISEMPTY('Dim_Geography')),",
              "    KEEPFILTERS(tnb_union_geo)",
              ")",
              "",
              "return if(not isblank([Sales_Outlet_Period]) && HASONEVALUE(AUX_Top_Selection_Prod[Top_Type]), switch(TRUE(),",
              "                                    values(AUX_Top_Selection_Prod[Top_Type]) = \"Top\", top_only,",
              "                                    values(AUX_Top_Selection_Prod[Top_Type]) = \"Bottom\", bot_only,",
              "                                    values(AUX_Top_Selection_Prod[Top_Type]) = \"TnB\", tnb_both,",
              "                                    top_only",
              "                                    ),",
              "                                    top_only)"
            ],
            "formatString": "0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Sales_Outlet_Period_Base",
            "expression": [
              "",
              "var pt = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = pt))",
              "var sales_period_normal_out = CALCULATE([Sales_Outlet_Base], filter(all(Dim_Period), 'Dim_Period'[Period_Type] = pt && 'Dim_Period'[period_start] = currentperiod))",
              "",
              "return sales_period_normal_out"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Sales_Outlet_Period_CTD",
            "expression": [
              "",
              "var pt = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start_day]), filter(ALL('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = pt))",
              "var c_date_num = calculate(max('Dim_Period'[weekdatenumber]), filter(all('Dim_Period'), 'Dim_Period'[Period_Type] = pt && 'Dim_Period'[period_start_day] = currentperiod))",
              "var c_year = calculate(max('Dim_Period'[MAT_year]), filter(all('Dim_Period'), 'Dim_Period'[Period_Type] = pt && 'Dim_Period'[period_start_day] = currentperiod))",
              "var start_period = calculate(min('Dim_Period'[period_start_day]), filter(all('Dim_Period'), 'Dim_Period'[Period_Type] = pt && 'Dim_Period'[MAT_year] = c_year))",
              "",
              "return CALCULATE([Sales_Outlet_Base], filter(all(Dim_Period), 'Dim_Period'[Period_Type] = pt && 'Dim_Period'[period_start_day] >= start_period && 'Dim_Period'[period_start_day] <= currentperiod))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "5206d359-2020-4302-b9b8-fa3e30baa04b"
          },
          {
            "name": "LinkedQueryName",
            "value": "Fact_Sales_Metrics_Outlet"
          },
          {
            "name": "PBI_QueryRelationships",
            "value": "{\"columnCount\":1,\"keyColumnNames\":[],\"queryRelationships\":[],\"columnIdentities\":[\"Section1/Fact_Sales_Metrics_Outlet/Changed Type.{Metrics,0}\"],\"ColumnCount\":1,\"KeyColumnNames\":[],\"ColumnIdentities\":[\"Section1/Fact_Sales_Metrics_Outlet/Changed Type.{Metrics,0}\"],\"RelationshipInfo\":[]}"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Fact_Sales_Metrics_SKUOutlet",
        "isHidden": true,
        "columns": [
          {
            "name": "Metrics",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Metrics",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Metrics"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Fact_Sales_Metrics_SKUOutlet-d5b728c0-821b-48fc-a067-2286b6e5c9d4",
            "mode": "import",
            "source": {
              "type": "query",
              "query": "SELECT * FROM [Fact_Sales_Metrics_SKUOutlet]",
              "dataSource": "77a09189-637f-4f07-acd3-362e7b48e8ee"
            }
          }
        ],
        "measures": [
          {
            "name": "Sales_SKUOutlet_Base",
            "expression": [
              "",
              "var sobase = if(countrows('Fact_SKU_Outlet_Sales') > 0, (calculate(sum('Fact_SKU_Outlet_Sales'[sales]) / 100)))",
              "return if(and(AUX_Filter[Filter_Outlet_Restriction], or([Filter_OutletName_cw], [Filter_OutletName_iqvia])), BLANK(), sobase)"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Sales_SKUOutlet_Period",
            "expression": [
              "",
              "var period_base_type = SELECTEDVALUE('Dim_Period'[period_type_base], \"MTH\")",
              "",
              "return if(period_base_type = \"WTD\", [Sales_SKUOutlet_Period_CTD], [Sales_SKUOutlet_Period_Base])"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Sales_SKUOutlet_Product_Own",
            "expression": "calculate([Sales_SKUOutlet_Period], 'Dim_Product_Ownership'[Product_Ownership] = \"Own Product\")",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Sales_SKUOutlet_Product",
            "expression": [
              "",
              "var ownship = calculate(countrows(values('Dim_Product_Ownership'[product_ownership_id])), CROSSFILTER('Dim_Product_Ownership'[product_ownership_id], 'Dim_Product_Client'[product_ownership_id],Both))",
              "",
              "return if([Filter_SKUName], [Sales_SKUOutlet_Period], ",
              "\t\t\tif(and(or([Filter_Prod_L2], [Filter_Prod_L3]), or([Hierarchy_Prod_L2_Name] in {\"Manufacturer\", \"Ingredient\", \"Brand\", \"Subbrand\"}, [Hierarchy_Prod_L3_Name] in {\"Manufacturer\", \"Ingredient\", \"Brand\", \"Subbrand\"})), [Sales_SKUOutlet_Period],",
              "\t\t\t[Sales_SKUOutlet_Product_Own]))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Sales_SKUOutlet_Competitor",
            "expression": "if([Sales_SKUOutlet_Product_Own] > 0,  calculate([Sales_SKUOutlet_Period], 'Dim_Product_Ownership'[Product_Ownership] = \"Competitor\"))",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Sales_SKUOutlet_Market_Pack",
            "expression": [
              "",
              "var hier_id = Calculate(values(Dim_Hierarchy_Name_Product[hierarchy_id]), Dim_Hierarchy_Name_Product[hierarchy_name] = values(Dim_Hierarchy_Name_Product[hierarchy_name]))",
              "var prod_l1_selected = values('Dim_Product_Client_Hierarchy'[prod_level_1])",
              "var prod_l2_selected = values('Dim_Product_Client_Hierarchy'[prod_level_2])",
              "var prod_l3_selected = values('Dim_Product_Client_Hierarchy'[prod_level_3])",
              "var prod_l4_selected = values('Dim_Product_Client_Hierarchy'[prod_level_4])",
              "var prod_l5_selected = values('Dim_Product_Client_Hierarchy'[prod_level_5])",
              "",
              "",
              "var market_l5 = calculate([Sales_SKUOutlet_Period], filter(all('Dim_Product_Client_Hierarchy'), 'Dim_Product_Client_Hierarchy'[prod_level_5] in prod_l5_selected && 'Dim_Product_Client_Hierarchy'[hierarchy_id] = hier_id))",
              "var market_l4 = calculate([Sales_SKUOutlet_Period], filter(all('Dim_Product_Client_Hierarchy'), 'Dim_Product_Client_Hierarchy'[prod_level_4] in prod_l4_selected && 'Dim_Product_Client_Hierarchy'[hierarchy_id] = hier_id))",
              "var market_l3 = calculate([Sales_SKUOutlet_Period], filter(all('Dim_Product_Client_Hierarchy'), 'Dim_Product_Client_Hierarchy'[prod_level_3] in prod_l3_selected && 'Dim_Product_Client_Hierarchy'[hierarchy_id] = hier_id))",
              "var market_l2 = calculate([Sales_SKUOutlet_Period], filter(all('Dim_Product_Client_Hierarchy'), 'Dim_Product_Client_Hierarchy'[prod_level_2] in prod_l2_selected && 'Dim_Product_Client_Hierarchy'[hierarchy_id] = hier_id))",
              "var market_l1 = calculate([Sales_SKUOutlet_Period], filter(all('Dim_Product_Client_Hierarchy'), 'Dim_Product_Client_Hierarchy'[prod_level_1] in prod_l1_selected && 'Dim_Product_Client_Hierarchy'[hierarchy_id] = hier_id))",
              "var market_oth = calculate([Sales_SKUOutlet_Period], ALLSELECTED('Dim_Product_Client_Hierarchy'))",
              "",
              "var market =  switch(True(), [Filter_SKUName] && [Filter_Prod_L5], market_l5,",
              "                      [Filter_SKUName] && [Filter_Prod_L4], market_l4,",
              "                      [Filter_SKUName] && [Filter_Prod_L3], market_l3,",
              "                      [Filter_SKUName] && [Filter_Prod_L2], market_l2,",
              "                      [Filter_SKUName] && [Filter_Prod_L1], market_l1,",
              "                      [Filter_SKUName] , market_l1, market_oth)",
              "                                        ",
              "return if(countrows('Fact_SKU_Outlet_Sales') > 0, market)"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Sales_SKUOutlet_Market",
            "expression": [
              "",
              "var market_SKUOutlet = if([Filter_SKUName], [Sales_SKUOutlet_Market_Pack],",
              "                        if(and(or([Filter_Prod_L2], [Filter_Prod_L3]), or([Hierarchy_Prod_L2_Name] in {\"Manufacturer\", \"Ingredient\", \"Brand\", \"Subbrand\"}, [Hierarchy_Prod_L3_Name] in {\"Manufacturer\", \"Ingredient\", \"Brand\", \"Subbrand\"})),",
              "                        [Sales_SKUOutlet_Market_Parent],",
              "                        [Sales_SKUOutlet_Period]))",
              "\t\t\t\t\t\t",
              "return market_SKUOutlet\t"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Sales_SKUOutlet_Market_Category",
            "expression": [
              "",
              "var hier_id = Calculate(values(Dim_Hierarchy_Name_Product[hierarchy_id]), Dim_Hierarchy_Name_Product[hierarchy_name] = values(Dim_Hierarchy_Name_Product[hierarchy_name]))",
              "var prod_l1_selected = values('Dim_Product_Client_Hierarchy'[prod_level_1])",
              "",
              "return calculate([Sales_SKUOutlet_Period], filter(all('Dim_Product_Client_Hierarchy'), 'Dim_Product_Client_Hierarchy'[prod_level_1] in prod_l1_selected && 'Dim_Product_Client_Hierarchy'[hierarchy_id] = hier_id))",
              ""
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Sales_SKUOutlet_Market_Parent",
            "expression": [
              "",
              "var market_l5 = if(countrows('Fact_SKU_Outlet_Sales') > 0, calculate([Sales_SKUOutlet_Period], All('Dim_Product_Client_Hierarchy'[prod_level_5])))",
              "var market_l4 = if(countrows('Fact_SKU_Outlet_Sales') > 0, calculate([Sales_SKUOutlet_Period], All('Dim_Product_Client_Hierarchy'[prod_level_4])))",
              "var market_l3 = if(countrows('Fact_SKU_Outlet_Sales') > 0, calculate([Sales_SKUOutlet_Period], All('Dim_Product_Client_Hierarchy'[prod_level_3])))",
              "var market_l2 = if(countrows('Fact_SKU_Outlet_Sales') > 0, calculate([Sales_SKUOutlet_Period], All('Dim_Product_Client_Hierarchy'[prod_level_2])))",
              "var market_l1 = if(countrows('Fact_SKU_Outlet_Sales') > 0, calculate([Sales_SKUOutlet_Period], All('Dim_Product_Client_Hierarchy'[prod_level_1])))",
              "var market_oth = if(countrows('Fact_SKU_Outlet_Sales') > 0, calculate([Sales_SKUOutlet_Period], ALLSELECTED('Dim_Product_Client_Hierarchy')))",
              "",
              "var market =  if([Filter_SKUName],",
              "                    [Sales_SKUOutlet_Market_Pack],",
              "                    if([Filter_Prod_L5],",
              "                            market_l5,",
              "                            if([Filter_Prod_L4],",
              "                                market_l4,",
              "                                if([Filter_Prod_L3],",
              "                                    market_l3,",
              "                                    if([Filter_Prod_L2],",
              "                                        market_l2,",
              "                                        if([Filter_Prod_L1],",
              "                                        market_l1, market_oth))))))",
              "                                        ",
              "return market"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "LY_Sales_SKUOutlet_Product_Own",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var last_year = calculate(values('Dim_Period'[MAT_year]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) - 1",
              "var seq = calculate(values('Dim_Period'[period_seq]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod))",
              "",
              "return calculate([Sales_SKUOutlet_Product_Own], filter(all('Dim_Period'), Dim_Period[MAT_year] = last_year && 'Dim_Period'[period_seq] = seq && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "LY_Sales_SKUOutlet_Product",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var last_year = calculate(values('Dim_Period'[MAT_year]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) - 1",
              "var seq = calculate(values('Dim_Period'[period_seq]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod))",
              "",
              "return calculate([Sales_SKUOutlet_Product], filter(all('Dim_Period'), Dim_Period[MAT_year] = last_year && 'Dim_Period'[period_seq] = seq && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "LY_Sales_SKUOutlet_Period",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var last_year = calculate(values('Dim_Period'[MAT_year]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) - 1",
              "var seq = calculate(values('Dim_Period'[period_seq]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod))",
              "",
              "return calculate([Sales_SKUOutlet_Period], filter(all('Dim_Period'), Dim_Period[MAT_year] = last_year && 'Dim_Period'[period_seq] = seq && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "LY_Sales_SKUOutlet_Market_Parent",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var last_year = calculate(values('Dim_Period'[MAT_year]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) - 1",
              "var seq = calculate(values('Dim_Period'[period_seq]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod))",
              "",
              "return calculate([Sales_SKUOutlet_Market_Parent], filter(all('Dim_Period'), Dim_Period[MAT_year] = last_year && 'Dim_Period'[period_seq] = seq && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "LY_Sales_SKUOutlet_Market_Category",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var last_year = calculate(values('Dim_Period'[MAT_year]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) - 1",
              "var seq = calculate(values('Dim_Period'[period_seq]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod))",
              "",
              "return calculate([Sales_SKUOutlet_Market_Category], filter(all('Dim_Period'), Dim_Period[MAT_year] = last_year && 'Dim_Period'[period_seq] = seq && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "LY_Sales_SKUOutlet_Market",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var last_year = calculate(values('Dim_Period'[MAT_year]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) - 1",
              "var seq = calculate(values('Dim_Period'[period_seq]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod))",
              "",
              "return calculate([Sales_SKUOutlet_Market], filter(all('Dim_Period'), Dim_Period[MAT_year] = last_year && 'Dim_Period'[period_seq] = seq && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "LY_Sales_SKUOutlet_Competitor",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var last_year = calculate(values('Dim_Period'[MAT_year]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) - 1",
              "var seq = calculate(values('Dim_Period'[period_seq]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod))",
              "",
              "return calculate([Sales_SKUOutlet_Competitor], filter(all('Dim_Period'), Dim_Period[MAT_year] = last_year && 'Dim_Period'[period_seq] = seq && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "MS_SKUOutlet_Product",
            "expression": "DIVIDE([Sales_SKUOutlet_Product], [Sales_SKUOutlet_Market]) ",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "MS_SKUOutlet_Parent",
            "expression": "DIVIDE([Sales_SKUOutlet_Product], [Sales_SKUOutlet_Market_Parent])",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "MS_SKUOutlet_Category",
            "expression": "DIVIDE([Sales_SKUOutlet_Product], [Sales_SKUOutlet_Market_Category])",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "LY_MS_SKUOutlet_Product",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var last_year = calculate(values('Dim_Period'[MAT_year]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) - 1",
              "var seq = calculate(values('Dim_Period'[period_seq]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod))",
              "",
              "return calculate([MS_SKUOutlet_Product], filter(all('Dim_Period'), Dim_Period[MAT_year] = last_year && 'Dim_Period'[period_seq] = seq && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "LY_MS_SKUOutlet_Parent",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var last_year = calculate(values('Dim_Period'[MAT_year]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) - 1",
              "var seq = calculate(values('Dim_Period'[period_seq]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod))",
              "",
              "return calculate([MS_SKUOutlet_Parent], filter(all('Dim_Period'), Dim_Period[MAT_year] = last_year && 'Dim_Period'[period_seq] = seq && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "LY_MS_SKUOutlet_Category",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var last_year = calculate(values('Dim_Period'[MAT_year]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) - 1",
              "var seq = calculate(values('Dim_Period'[period_seq]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod))",
              "",
              "return calculate([MS_SKUOutlet_Category], filter(all('Dim_Period'), Dim_Period[MAT_year] = last_year && 'Dim_Period'[period_seq] = seq && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "YOY_MS_Change_SKUOutlet",
            "expression": "[MS_SKUOutlet_Product] - [LY_MS_SKUOutlet_Product]",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "YOY_Gth_SKUOutlet_Product",
            "expression": "[Sales_SKUOutlet_Product] - [LY_Sales_SKUOutlet_Product]",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "YOY_Gth_SKUOutlet_Market",
            "expression": "[Sales_SKUOutlet_Market] - [LY_Sales_SKUOutlet_Market]",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "YOY_Gth_%_SKUOutlet_Product",
            "expression": "divide([YOY_Gth_SKUOutlet_Product] , [LY_Sales_SKUOutlet_Product])",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "YOY_EI_SKUOutlet",
            "expression": "DIVIDE([MS_SKUOutlet_Product],[LY_MS_SKUOutlet_Product],BLANK())*100",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "LY_Gth_%_SKUOutlet_Product",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var last_year = calculate(values('Dim_Period'[MAT_year]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) - 1",
              "var seq = calculate(values('Dim_Period'[period_seq]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod))",
              "",
              "return calculate([YOY_Gth_%_SKUOutlet_Product], filter(all('Dim_Period'), Dim_Period[MAT_year] = last_year && 'Dim_Period'[period_seq] = seq && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "LP_Sales_SKUOutlet_Product_Own",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var num = calculate(values('Dim_Period'[period_num]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) + 1",
              "",
              "return calculate([Sales_SKUOutlet_Product_Own], filter(all('Dim_Period'), 'Dim_Period'[period_num] = num && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "LP_Sales_SKUOutlet_Product",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var num = calculate(values('Dim_Period'[period_num]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) + 1",
              "",
              "return calculate([Sales_SKUOutlet_Product], filter(all('Dim_Period'), 'Dim_Period'[period_num] = num && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "LP_Sales_SKUOutlet_Period",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var num = calculate(values('Dim_Period'[period_num]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) + 1",
              "",
              "return calculate([Sales_SKUOutlet_Period], filter(all('Dim_Period'), 'Dim_Period'[period_num] = num && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "LP_Sales_SKUOutlet_Market_Parent",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var num = calculate(values('Dim_Period'[period_num]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) + 1",
              "",
              "return calculate([Sales_SKUOutlet_Market_Parent], filter(all('Dim_Period'), 'Dim_Period'[period_num] = num && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "LP_Sales_SKUOutlet_Market_Category",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var num = calculate(values('Dim_Period'[period_num]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) + 1",
              "",
              "return calculate([Sales_SKUOutlet_Market_Category], filter(all('Dim_Period'), 'Dim_Period'[period_num] = num && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "LP_Sales_SKUOutlet_Market",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var num = calculate(values('Dim_Period'[period_num]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) + 1",
              "",
              "return calculate([Sales_SKUOutlet_Market], filter(all('Dim_Period'), 'Dim_Period'[period_num] = num && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "LP_Sales_SKUOutlet_Competitor",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var num = calculate(values('Dim_Period'[period_num]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) + 1",
              "",
              "return calculate([Sales_SKUOutlet_Competitor], filter(all('Dim_Period'), 'Dim_Period'[period_num] = num && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "LP_MS_SKUOutlet_Product",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var num = calculate(values('Dim_Period'[period_num]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) + 1",
              "",
              "return calculate([MS_SKUOutlet_Product], filter(all('Dim_Period'), 'Dim_Period'[period_num] = num && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "LP_MS_SKUOutlet_Parent",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var num = calculate(values('Dim_Period'[period_num]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) + 1",
              "",
              "return calculate([MS_SKUOutlet_Parent], filter(all('Dim_Period'), 'Dim_Period'[period_num] = num && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "LP_MS_SKUOutlet_Category",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var num = calculate(values('Dim_Period'[period_num]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) + 1",
              "",
              "return calculate([MS_SKUOutlet_Category], filter(all('Dim_Period'), 'Dim_Period'[period_num] = num && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "POP_MS_Change_SKUOutlet",
            "expression": "[MS_SKUOutlet_Product] - [LP_MS_SKUOutlet_Product]",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "POP_Gth_SKUOutlet_Product",
            "expression": "[Sales_SKUOutlet_Product] - [LP_Sales_SKUOutlet_Product]",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "POP_Gth_SKUOutlet_Market",
            "expression": "[Sales_SKUOutlet_Market] - [LP_Sales_SKUOutlet_Market]",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "POP_Gth_%_SKUOutlet_Product",
            "expression": "divide([POP_Gth_SKUOutlet_Product] , [LP_Sales_SKUOutlet_Product])",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "POP_EI_SKUOutlet",
            "expression": "DIVIDE([MS_SKUOutlet_Product],[LP_MS_SKUOutlet_Product],BLANK())*100",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "PP_Sales_SKUOutlet_Product_Own",
            "expression": "if(HASONEVALUE(AUX_Previous_Period[name]), SWITCH(TRUE(), values(AUX_Previous_Period[name]) = \"LY\", [LY_Sales_SKUOutlet_Product_Own], [LP_Sales_SKUOutlet_Product_Own]), [LY_Sales_SKUOutlet_Product_Own])",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "PP_Sales_SKUOutlet_Product",
            "expression": "if(HASONEVALUE(AUX_Previous_Period[name]), SWITCH(TRUE(), values(AUX_Previous_Period[name]) = \"LY\", [LY_Sales_SKUOutlet_Product], [LP_Sales_SKUOutlet_Product]), [LY_Sales_SKUOutlet_Product])",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "PP_Sales_SKUOutlet_Period",
            "expression": "if(HASONEVALUE(AUX_Previous_Period[name]), SWITCH(TRUE(), values(AUX_Previous_Period[name]) = \"LY\", [LY_Sales_SKUOutlet_Period], [LP_Sales_SKUOutlet_Period]), [LY_Sales_SKUOutlet_Period])",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "PP_Sales_SKUOutlet_Market_Parent",
            "expression": "if(HASONEVALUE(AUX_Previous_Period[name]), SWITCH(TRUE(), values(AUX_Previous_Period[name]) = \"LY\", [LY_Sales_SKUOutlet_Market_Parent], [LP_Sales_SKUOutlet_Market_Parent]), [LY_Sales_SKUOutlet_Market_Parent]) ",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "PP_Sales_SKUOutlet_Market_Category",
            "expression": "if(HASONEVALUE(AUX_Previous_Period[name]), SWITCH(TRUE(), values(AUX_Previous_Period[name]) = \"LY\", [LY_Sales_SKUOutlet_Market_Category], [LP_Sales_SKUOutlet_Market_Category]), [LY_Sales_SKUOutlet_Market_Category])",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "PP_Sales_SKUOutlet_Market",
            "expression": "if(HASONEVALUE(AUX_Previous_Period[name]), SWITCH(TRUE(), values(AUX_Previous_Period[name]) = \"LY\", [LY_Sales_SKUOutlet_Market], [LP_Sales_SKUOutlet_Market]), [LY_Sales_SKUOutlet_Market])",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "PP_Sales_SKUOutlet_Competitor",
            "expression": "if(HASONEVALUE(AUX_Previous_Period[name]), SWITCH(TRUE(), values(AUX_Previous_Period[name]) = \"LY\", [LY_Sales_SKUOutlet_Competitor], [LP_Sales_SKUOutlet_Competitor]), [LY_Sales_SKUOutlet_Competitor])",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "PP_MS_SKUOutlet_Product",
            "expression": "if(HASONEVALUE(AUX_Previous_Period[name]), SWITCH(TRUE(), values(AUX_Previous_Period[name]) = \"LY\", [LY_MS_SKUOutlet_Product], [LP_MS_SKUOutlet_Product]), [LY_MS_SKUOutlet_Product])",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "PP_MS_SKUOutlet_Parent",
            "expression": "if(HASONEVALUE(AUX_Previous_Period[name]), SWITCH(TRUE(), values(AUX_Previous_Period[name]) = \"LY\", [LY_MS_SKUOutlet_Parent], [LP_MS_SKUOutlet_Parent]), [LY_MS_SKUOutlet_Parent])",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "PP_MS_SKUOutlet_Category",
            "expression": "if(HASONEVALUE(AUX_Previous_Period[name]), SWITCH(TRUE(), values(AUX_Previous_Period[name]) = \"LY\", [LY_MS_SKUOutlet_Category], [LP_MS_SKUOutlet_Category]), [LY_MS_SKUOutlet_Category])",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "MS_Change_SKUOutlet",
            "expression": "[MS_SKUOutlet_Product] - [PP_MS_SKUOutlet_Product]",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Gth_SKUOutlet_Product",
            "expression": "[Sales_SKUOutlet_Product] - [PP_Sales_SKUOutlet_Product]",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Gth_SKUOutlet_Period",
            "expression": "[Sales_SKUOutlet_Period] - [PP_Sales_SKUOutlet_Period]",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Gth_SKUOutlet_Market",
            "expression": "[Sales_SKUOutlet_Market] - [PP_Sales_SKUOutlet_Market]",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Gth_%_SKUOutlet_Product",
            "expression": "divide([Gth_SKUOutlet_Product] , [PP_Sales_SKUOutlet_Product])",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Gth_%_SKUOutlet_Period",
            "expression": "divide([Gth_SKUOutlet_Period] , [PP_Sales_SKUOutlet_Period])",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Gth_%_SKUOutlet_Market",
            "expression": "divide([Gth_SKUOutlet_Market] , [PP_Sales_SKUOutlet_Market])",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Rank_SKUOutlet_Market",
            "expression": [
              "",
              "var Rank_SKUOutlet_Market_L1 = calculate(rankx(ALL('Dim_Product_Client_Hierarchy'[prod_level_1]), ",
              "if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKUOutlet_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKUOutlet_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKUOutlet_Period]",
              "                    ), [Sales_SKUOutlet_Period])))",
              "var Rank_SKUOutlet_Market_L2 = calculate(rankx(ALL('Dim_Product_Client_Hierarchy'[prod_level_2]), ",
              "if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKUOutlet_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKUOutlet_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKUOutlet_Period]",
              "                    ), [Sales_SKUOutlet_Period])))",
              "var Rank_SKUOutlet_Market_L3 = calculate(rankx(ALL('Dim_Product_Client_Hierarchy'[prod_level_3]), ",
              "if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKUOutlet_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKUOutlet_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKUOutlet_Period]",
              "                    ), [Sales_SKUOutlet_Period])))",
              "var Rank_SKUOutlet_Market_L4 = calculate(rankx(ALL('Dim_Product_Client_Hierarchy'[prod_level_4]), ",
              "if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKUOutlet_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKUOutlet_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKUOutlet_Period]",
              "                    ), [Sales_SKUOutlet_Period])))",
              "var Rank_SKUOutlet_Market_L5 = calculate(rankx(ALL('Dim_Product_Client_Hierarchy'[prod_level_5]), ",
              "if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKUOutlet_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKUOutlet_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKUOutlet_Period]",
              "                    ), [Sales_SKUOutlet_Period])))",
              "",
              "return if(countrows('Fact_SKU_Outlet_Sales') > 0, Switch(True(),",
              "[Filter_SKUName], blank(),",
              "[Filter_Prod_L5], Rank_SKUOutlet_Market_L5,",
              "[Filter_Prod_L4], Rank_SKUOutlet_Market_L4,",
              "[Filter_Prod_L3], if([Hierarchy_Prod_L3_Name] =\"Subbrand\", blank(), Rank_SKUOutlet_Market_L3),",
              "[Filter_Prod_L2], if([Hierarchy_Prod_L2_Name] = \"Brand\", blank(), Rank_SKUOutlet_Market_L2),",
              "[Filter_Prod_L1], Rank_SKUOutlet_Market_L1,",
              "Blank()))"
            ],
            "formatString": "0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Rank_SKUOutlet_Product_Pack",
            "expression": [
              "",
              "var hier_id = Calculate(values(Dim_Hierarchy_Name_Product[hierarchy_id]), Dim_Hierarchy_Name_Product[hierarchy_name] = values(Dim_Hierarchy_Name_Product[hierarchy_name]))",
              "var rank_oth = calculate(rankx(ALL('Dim_Product_Client_Hierarchy'[pack_name]), ",
              "if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKUOutlet_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKUOutlet_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKUOutlet_Period]",
              "                    ), [Sales_SKUOutlet_Period])), ",
              "'Dim_Product_Client_Hierarchy'[hierarchy_id] = hier_id)",
              "                                        ",
              "return if(countrows('Fact_SKU_Outlet_Sales') > 0 && [Filter_SKUName], rank_oth)"
            ],
            "formatString": "0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Rank_SKUOutlet_Product",
            "expression": [
              "",
              "",
              "var Rank_SKUOutlet_Product_L1 = calculate(rankx(ALL('Dim_Product_Client_Hierarchy'[prod_level_1]), ",
              "if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKUOutlet_Product],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKUOutlet_Product],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKUOutlet_Product]",
              "                    ), [Sales_SKUOutlet_Product])))",
              "var Rank_SKUOutlet_Product_L2 = calculate(rankx(ALL('Dim_Product_Client_Hierarchy'[prod_level_2]), ",
              "if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKUOutlet_Product],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKUOutlet_Product],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKUOutlet_Product]",
              "                    ), [Sales_SKUOutlet_Product])))",
              "var Rank_SKUOutlet_Product_L3 = calculate(rankx(ALL('Dim_Product_Client_Hierarchy'[prod_level_3]), ",
              "if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKUOutlet_Product],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKUOutlet_Product],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKUOutlet_Product]",
              "                    ), [Sales_SKUOutlet_Product])))",
              "var Rank_SKUOutlet_Product_L4 = calculate(rankx(ALL('Dim_Product_Client_Hierarchy'[prod_level_4]), ",
              "if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKUOutlet_Product],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKUOutlet_Product],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKUOutlet_Product]",
              "                    ), [Sales_SKUOutlet_Product])))",
              "var Rank_SKUOutlet_Product_L5 = calculate(rankx(ALL('Dim_Product_Client_Hierarchy'[prod_level_5]), ",
              "if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKUOutlet_Product],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKUOutlet_Product],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKUOutlet_Product]",
              "                    ), [Sales_SKUOutlet_Product])))",
              "",
              "return if([Sales_SKUOutlet_Product] <> 0, Switch(True(),",
              "[Filter_SKUName],[Rank_SKUOutlet_Product_Pack],",
              "[Filter_Prod_L5], Rank_SKUOutlet_Product_L5,",
              "[Filter_Prod_L4], Rank_SKUOutlet_Product_L4,",
              "[Filter_Prod_L3], Rank_SKUOutlet_Product_L3,",
              "[Filter_Prod_L2], Rank_SKUOutlet_Product_L2,",
              "[Filter_Prod_L1], Rank_SKUOutlet_Product_L1,",
              "Blank()), blank())"
            ],
            "formatString": "0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "TnB_Filter_SKUOutlet",
            "expression": [
              "",
              "var top_brand = calculatetable(",
              "    TOPN(values('AUX_Top_Selection_Prod'[Top_Value]),",
              "    CALCULATETABLE(VALUES('Dim_Product_Client_Top_Analysis'[top_items]), FILTER('Dim_Product_Client_Top_Analysis', [Sales_SKUOutlet_Period] <> 0 )),",
              "    if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKUOutlet_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKUOutlet_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKUOutlet_Period]",
              "                    ), [Sales_SKUOutlet_Period]), 0",
              "    )",
              "    , ALLSELECTED()",
              ")",
              "",
              "var bot_brand = calculatetable(",
              "    TOPN(values('AUX_Top_Selection_Prod'[Top_Value]),",
              "    CALCULATETABLE(VALUES('Dim_Product_Client_Top_Analysis'[top_items]), FILTER('Dim_Product_Client_Top_Analysis', [Sales_SKUOutlet_Period] <> 0 )),",
              "    if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKUOutlet_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKUOutlet_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKUOutlet_Period]",
              "                    ), [Sales_SKUOutlet_Period]), 1",
              "    )",
              "    , ALLSELECTED()",
              ")",
              "",
              "var tnb_union = UNION(top_brand,bot_brand)",
              "",
              "var top_only = CALCULATE(",
              "    1 * (NOT ISEMPTY('Dim_Product_Client_Top_Analysis')),",
              "    KEEPFILTERS(top_brand)",
              ")",
              "",
              "var bot_only = CALCULATE(",
              "    1 * (NOT ISEMPTY('Dim_Product_Client_Top_Analysis')),",
              "    KEEPFILTERS(bot_brand)",
              ")",
              "",
              "var tnb_both = CALCULATE(",
              "    1 * (NOT ISEMPTY('Dim_Product_Client_Top_Analysis')),",
              "    KEEPFILTERS(tnb_union)",
              ")",
              "",
              "return if([Sales_SKUOutlet_Period] <> 0 && HASONEVALUE(AUX_Top_Selection_Prod[Top_Type]), switch(TRUE(),",
              "                                    values(AUX_Top_Selection_Prod[Top_Type]) = \"Top\", top_only,",
              "                                    values(AUX_Top_Selection_Prod[Top_Type]) = \"Bottom\", bot_only,",
              "                                    values(AUX_Top_Selection_Prod[Top_Type]) = \"TnB\", tnb_both,",
              "                                    top_only",
              "                                    ),",
              "                                    top_only)"
            ],
            "formatString": "0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "TnB_Filter_SKUOutlet_Label",
            "expression": [
              "",
              "var top_brand = calculatetable(",
              "    TOPN(values('AUX_Top_Selection_Prod'[Top_Value]),",
              "    CALCULATETABLE(VALUES('Dim_Product_Client_Top_Analysis'[top_items]), FILTER('Dim_Product_Client_Top_Analysis', [Sales_SKUOutlet_Period] <> 0 )),",
              "    if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKUOutlet_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKUOutlet_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKUOutlet_Period]",
              "                    ), [Sales_SKUOutlet_Period]), 0",
              "    )",
              "    , ALLSELECTED()",
              ")",
              "",
              "var bot_brand = calculatetable(",
              "    TOPN(values('AUX_Top_Selection_Prod'[Top_Value]),",
              "    CALCULATETABLE(VALUES('Dim_Product_Client_Top_Analysis'[top_items]), FILTER('Dim_Product_Client_Top_Analysis', [Sales_SKUOutlet_Period] <> 0 )),",
              "    if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKUOutlet_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKUOutlet_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKUOutlet_Period]",
              "                    ), [Sales_SKUOutlet_Period]), 1",
              "    )",
              "    , ALLSELECTED()",
              ")",
              "",
              "var top_only = CALCULATE(",
              "    1 * (NOT ISEMPTY('Dim_Product_Client_Top_Analysis')),",
              "    KEEPFILTERS(top_brand)",
              ")",
              "",
              "var bot_only = CALCULATE(",
              "    1 * (NOT ISEMPTY('Dim_Product_Client_Top_Analysis')),",
              "    KEEPFILTERS(bot_brand)",
              ")",
              "",
              "return if([Sales_SKUOutlet_Period] <> 0 && HASONEVALUE(AUX_Top_Selection_Prod[Top_Type]), switch(TRUE(),",
              "                                    top_only = 1, \"Top\",",
              "                                    bot_only = 1, \"Bottom\"",
              "                                    ))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "TnB_Filter_SKUOutlet_Value",
            "expression": [
              "",
              "var top_brand = calculatetable(",
              "    TOPN(values('AUX_Top_Selection_Prod'[Top_Value]),",
              "    CALCULATETABLE(VALUES('Dim_Product_Client_Top_Analysis'[top_items]), FILTER('Dim_Product_Client_Top_Analysis', [Sales_SKUOutlet_Period] <> 0 )),",
              "    if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKUOutlet_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKUOutlet_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKUOutlet_Period]",
              "                    ), [Sales_SKUOutlet_Period]), 0",
              "    )",
              "    , ALLSELECTED()",
              ")",
              "",
              "var bot_brand = calculatetable(",
              "    TOPN(values('AUX_Top_Selection_Prod'[Top_Value]),",
              "    CALCULATETABLE(VALUES('Dim_Product_Client_Top_Analysis'[top_items]), FILTER('Dim_Product_Client_Top_Analysis', [Sales_SKUOutlet_Period] <> 0 )),",
              "    if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKUOutlet_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKUOutlet_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKUOutlet_Period]",
              "                    ), [Sales_SKUOutlet_Period]), 1",
              "    )",
              "    , ALLSELECTED()",
              ")",
              "",
              "var top_only = CALCULATE(",
              "    1 * (NOT ISEMPTY('Dim_Product_Client_Top_Analysis')),",
              "    KEEPFILTERS(top_brand)",
              ")",
              "",
              "var bot_only = CALCULATE(",
              "    1 * (NOT ISEMPTY('Dim_Product_Client_Top_Analysis')),",
              "    KEEPFILTERS(bot_brand)",
              ")",
              "",
              "return if([Sales_SKUOutlet_Period] <> 0 && HASONEVALUE(AUX_Top_Selection_Prod[Top_Type]), switch(TRUE(),",
              "                                    top_only = 1, 1,",
              "                                    bot_only = 1, -1",
              "                                    ))"
            ],
            "formatString": "0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Top_Filter_SKUOutlet_Prod",
            "expression": [
              "",
              "var top_prod_l1 = calculatetable(",
              "    TOPN(values('AUX_Top_Selection_Prod'[Top_Value]),",
              "    CALCULATETABLE(VALUES('Dim_Product_Client_Hierarchy'[prod_level_1]), FILTER('Dim_Product_Client_Hierarchy', [Sales_SKUOutlet_Period] <> 0 )),",
              "    if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKUOutlet_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKUOutlet_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKUOutlet_Period]",
              "                    ), [Sales_SKUOutlet_Period]), 0",
              "    )",
              "    , ALLSELECTED()",
              ")",
              "",
              "var top_prod_l2 = calculatetable(",
              "    TOPN(values('AUX_Top_Selection_Prod'[Top_Value]),",
              "    CALCULATETABLE(VALUES('Dim_Product_Client_Hierarchy'[prod_level_2]), FILTER('Dim_Product_Client_Hierarchy', [Sales_SKUOutlet_Period] <> 0 )),",
              "    if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKUOutlet_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKUOutlet_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKUOutlet_Period]",
              "                    ), [Sales_SKUOutlet_Period]), 0",
              "    )",
              "    , ALLSELECTED()",
              ")",
              "",
              "var top_prod_l3 = calculatetable(",
              "    TOPN(values('AUX_Top_Selection_Prod'[Top_Value]),",
              "    CALCULATETABLE(VALUES('Dim_Product_Client_Hierarchy'[prod_level_3]), FILTER('Dim_Product_Client_Hierarchy', [Sales_SKUOutlet_Period] <> 0 )),",
              "    if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKUOutlet_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKUOutlet_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKUOutlet_Period]",
              "                    ), [Sales_SKUOutlet_Period]), 0",
              "    )",
              "    , ALLSELECTED()",
              ")",
              "",
              "var top_prod_l4 = calculatetable(",
              "    TOPN(values('AUX_Top_Selection_Prod'[Top_Value]),",
              "    CALCULATETABLE(VALUES('Dim_Product_Client_Hierarchy'[prod_level_4]), FILTER('Dim_Product_Client_Hierarchy', [Sales_SKUOutlet_Period] <> 0 )),",
              "    if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKUOutlet_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKUOutlet_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKUOutlet_Period]",
              "                    ), [Sales_SKUOutlet_Period]), 0",
              "    )",
              "    , ALLSELECTED()",
              ")",
              "",
              "var top_prod_l5 = calculatetable(",
              "    TOPN(values('AUX_Top_Selection_Prod'[Top_Value]),",
              "    CALCULATETABLE(VALUES('Dim_Product_Client_Hierarchy'[prod_level_5]), FILTER('Dim_Product_Client_Hierarchy', [Sales_SKUOutlet_Period] <> 0 )),",
              "    if(HASONEVALUE('AUX_Top_Select_Option'[top_option]), ",
              "                    switch(TRUE(), ",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Value\", [Sales_SKUOutlet_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth\", [Gth_SKUOutlet_Period],",
              "                    values('AUX_Top_Select_Option'[top_option]) = \"Growth %\", [Gth_%_SKUOutlet_Period]",
              "                    ), [Sales_SKUOutlet_Period]), 0",
              "    )",
              "    , ALLSELECTED()",
              ")",
              "",
              "",
              "",
              "var top_l1 = CALCULATE(",
              "    1 * (NOT ISEMPTY('Dim_Product_Client')),",
              "    KEEPFILTERS(top_prod_l1)",
              ")",
              "",
              "var top_l2 = CALCULATE(",
              "    1 * (NOT ISEMPTY('Dim_Product_Client')),",
              "    KEEPFILTERS(top_prod_l2)",
              ")",
              "",
              "var top_l3 = CALCULATE(",
              "    1 * (NOT ISEMPTY('Dim_Product_Client')),",
              "    KEEPFILTERS(top_prod_l3)",
              ")",
              "",
              "var top_l4 = CALCULATE(",
              "    1 * (NOT ISEMPTY('Dim_Product_Client')),",
              "    KEEPFILTERS(top_prod_l4)",
              ")",
              "",
              "var top_l5 = CALCULATE(",
              "    1 * (NOT ISEMPTY('Dim_Product_Client')),",
              "    KEEPFILTERS(top_prod_l5)",
              ")",
              "",
              "",
              "return if([Sales_SKUOutlet_Period] <> 0 && HASONEVALUE(AUX_Top_Selection_Prod[Top_Type]), switch(TRUE(),",
              "                                    [Filter_Prod_L5], top_l5,",
              "                                    [Filter_Prod_L4], top_l4,",
              "                                    [Filter_Prod_L3], top_l3,",
              "                                    [Filter_Prod_L2], top_l2,",
              "\t\t\t\t\t\t\t\t\t[Filter_Prod_L1], top_l1",
              "                                    ))",
              ""
            ],
            "formatString": "0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "EI_SKUOutlet",
            "expression": "if(HASONEVALUE(AUX_Previous_Period[name]), SWITCH(TRUE(), values(AUX_Previous_Period[name]) = \"LY\", [YOY_EI_SKUOutlet], [POP_EI_SKUOutlet]), [YOY_EI_SKUOutlet])",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Sales_SKUOutlet_Market_TnB",
            "expression": "calculate([Sales_SKUOutlet_Base], ALL(Dim_Product_Client_Top_Analysis[top_items]))",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "LY_Sales_SKUOutlet_Market_TnB",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var last_year = calculate(values('Dim_Period'[MAT_year]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) - 1",
              "var seq = calculate(values('Dim_Period'[period_seq]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod))",
              "",
              "return calculate([Sales_SKUOutlet_Market_TnB], filter(all('Dim_Period'), Dim_Period[MAT_year] = last_year && 'Dim_Period'[period_seq] = seq && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "LP_Sales_SKUOutlet_Market_TnB",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var num = calculate(values('Dim_Period'[period_num]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) + 1",
              "",
              "return calculate([Sales_SKUOutlet_Market_TnB], filter(all('Dim_Period'), 'Dim_Period'[period_num] = num && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "PP_Sales_SKUOutlet_Market_TnB",
            "expression": "if(HASONEVALUE(AUX_Previous_Period[name]), SWITCH(TRUE(), values(AUX_Previous_Period[name]) = \"LY\", [LY_Sales_SKUOutlet_Market_TnB], [LP_Sales_SKUOutlet_Market_TnB]), [LY_Sales_SKUOutlet_Market_TnB]) ",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Sales_SKUOutlet_Period_Base",
            "expression": [
              "",
              "var pt = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = pt))",
              "var sales_period_normal = CALCULATE([Sales_SKUOutlet_Base], filter(all(Dim_Period), 'Dim_Period'[Period_Type] = pt && 'Dim_Period'[period_start] = currentperiod))",
              "",
              "return sales_period_normal"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Sales_SKUOutlet_Period_CTD",
            "expression": [
              "",
              "var pt = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start_day]), filter(ALL('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = pt))",
              "var c_date_num = calculate(max('Dim_Period'[weekdatenumber]), filter(all('Dim_Period'), 'Dim_Period'[Period_Type] = pt && 'Dim_Period'[period_start_day] = currentperiod))",
              "var c_year = calculate(max('Dim_Period'[MAT_year]), filter(all('Dim_Period'), 'Dim_Period'[Period_Type] = pt && 'Dim_Period'[period_start_day] = currentperiod))",
              "var start_period = calculate(min('Dim_Period'[period_start_day]), filter(all('Dim_Period'), 'Dim_Period'[Period_Type] = pt && 'Dim_Period'[MAT_year] = c_year))",
              "",
              "return CALCULATE([Sales_SKUOutlet_Base], filter(all(Dim_Period), 'Dim_Period'[Period_Type] = pt && 'Dim_Period'[period_start_day] >= start_period && 'Dim_Period'[period_start_day] <= currentperiod))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Dist_SKUOutlet_Store_Tot",
            "expression": [
              "",
              "var period_base_type = SELECTEDVALUE('Dim_Period'[period_type_base], \"MTH\")",
              "",
              "return if(period_base_type = \"WTD\", [Dist_SKUOutlet_Store_Tot_CTD], [Dist_SKUOutlet_Store_Tot_Base])"
            ],
            "formatString": "0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Dist_SKUOutlet_Store",
            "expression": [
              "",
              "var period_base_type = SELECTEDVALUE('Dim_Period'[period_type_base], \"MTH\")",
              "",
              "return if(period_base_type = \"WTD\", [Dist_SKUOutlet_Store_CTD], [Dist_SKUOutlet_Store_Base])"
            ],
            "formatString": "0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Sales_SKUOutlet_Period_Tot",
            "expression": "calculate([Sales_SKUOutlet_Period], ALLEXCEPT(Dim_Product_Client_Hierarchy, Dim_Product_Client_Hierarchy[prod_level_1]))",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Sales_SKUOutlet_Period_Distributed",
            "expression": [
              "",
              "var stores = CALCULATETABLE(values(Fact_SKU_Outlet_Sales[cw_outlet_key]))",
              "return calculate([Sales_SKUOutlet_Period_Tot], stores)"
            ],
            "formatString": "0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "LY_Sales_SKUOutlet_Period_Tot",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var last_year = calculate(values('Dim_Period'[MAT_year]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) - 1",
              "var seq = calculate(values('Dim_Period'[period_seq]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod))",
              "",
              "return calculate([Sales_SKUOutlet_Period_Tot], filter(all('Dim_Period'), Dim_Period[MAT_year] = last_year && 'Dim_Period'[period_seq] = seq && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "LP_Sales_SKUOutlet_Period_Tot",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var num = calculate(values('Dim_Period'[period_num]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) + 1",
              "",
              "return calculate([Sales_SKUOutlet_Period_Tot], filter(all('Dim_Period'), 'Dim_Period'[period_num] = num && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "PP_Sales_SKUOutlet_Period_Tot",
            "expression": "if(HASONEVALUE(AUX_Previous_Period[name]), SWITCH(TRUE(), values(AUX_Previous_Period[name]) = \"LY\", [LY_Sales_SKUOutlet_Period_Tot], [LP_Sales_SKUOutlet_Period_Tot]), [LY_Sales_SKUOutlet_Period_Tot])",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "LY_Sales_SKUOutlet_Period_Distributed_1",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var last_year = calculate(values('Dim_Period'[MAT_year]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) - 1",
              "var seq = calculate(values('Dim_Period'[period_seq]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod))",
              "",
              "var stores = CALCULATETABLE(values(Fact_SKU_Outlet_Sales[cw_outlet_key]), filter(all('Dim_Period'), Dim_Period[MAT_year] = last_year && 'Dim_Period'[period_seq] = seq && 'Dim_Period'[Period_Type] = p_type))",
              "",
              "return calculate([LY_Sales_SKUOutlet_Period_Tot], stores)"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "LP_Sales_SKUOutlet_Period_Distributed",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var num = calculate(values('Dim_Period'[period_num]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) + 1",
              "",
              "return calculate([Sales_SKUOutlet_Period_Distributed], filter(all('Dim_Period'), 'Dim_Period'[period_num] = num && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "PP_Sales_SKUOutlet_Period_Distributed",
            "expression": "if(HASONEVALUE(AUX_Previous_Period[name]), SWITCH(TRUE(), values(AUX_Previous_Period[name]) = \"LY\", [LY_Sales_SKUOutlet_Period_Distributed_1], [LP_Sales_SKUOutlet_Period_Distributed]), [LY_Sales_SKUOutlet_Period_Distributed_1])",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "LY_Sales_SKUOutlet_Period_Distributed",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var last_year = calculate(values('Dim_Period'[MAT_year]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) - 1",
              "var seq = calculate(values('Dim_Period'[period_seq]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod))",
              "",
              "return calculate([Sales_SKUOutlet_Period_Distributed], filter(all('Dim_Period'), Dim_Period[MAT_year] = last_year && 'Dim_Period'[period_seq] = seq && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Dist_SKUOutlet_Store_Tot_Base",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var currentperiod_end = calculate(max('Dim_Period'[period_end]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "",
              "return calculate(countrows(Dim_Outlet), filter(Dim_Outlet, Dim_Outlet[iqvia_outlet_name] <> \"Uncoded\" && Dim_Outlet[date_store_close] > currentperiod && Dim_Outlet[date_store_open] < currentperiod_end))"
            ],
            "formatString": "0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Dist_SKUOutlet_Store_Tot_CTD",
            "expression": [
              "",
              "var pt = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start_day]), filter(ALL('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = pt))",
              "var c_year = calculate(max('Dim_Period'[MAT_year]), filter(all('Dim_Period'), 'Dim_Period'[Period_Type] = pt && 'Dim_Period'[period_start_day] = currentperiod))",
              "var start_period = calculate(min('Dim_Period'[period_start_day]), filter(all('Dim_Period'), 'Dim_Period'[Period_Type] = pt && 'Dim_Period'[MAT_year] = c_year))",
              "",
              "return calculate(countrows(Dim_Outlet), Filter(Dim_Outlet, Dim_Outlet[iqvia_outlet_name] <> \"Uncoded\" && Dim_Outlet[date_store_close] > start_period && Dim_Outlet[date_store_open] < currentperiod))"
            ],
            "formatString": "0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Dist_SKUOutlet_Store_Base",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var currentperiod_end = calculate(max('Dim_Period'[period_end]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "",
              "return calculate(DISTINCTCOUNT(Fact_SKU_Outlet_Sales[cw_outlet_key]), ",
              "filter(all('Dim_Period'), 'Dim_Period'[period_start] >= currentperiod && 'Dim_Period'[period_start] <= currentperiod_end),",
              "filter(Dim_Outlet, Dim_Outlet[iqvia_outlet_name] <> \"Uncoded\" && Dim_Outlet[date_store_close] > currentperiod && Dim_Outlet[date_store_open] < currentperiod_end))"
            ],
            "formatString": "0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Dist_SKUOutlet_Store_CTD",
            "expression": [
              "",
              "var pt = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start_day]), filter(ALL('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = pt))",
              "var c_year = calculate(max('Dim_Period'[MAT_year]), filter(all('Dim_Period'), 'Dim_Period'[Period_Type] = pt && 'Dim_Period'[period_start_day] = currentperiod))",
              "var start_period = calculate(min('Dim_Period'[period_start_day]), filter(all('Dim_Period'), 'Dim_Period'[Period_Type] = pt && 'Dim_Period'[MAT_year] = c_year))",
              "",
              "return calculate(DISTINCTCOUNT(Fact_SKU_Outlet_Sales[cw_outlet_key]), ",
              "filter(all('Dim_Period'), 'Dim_Period'[period_start] >= start_period && 'Dim_Period'[period_start] <= currentperiod),",
              "filter(Dim_Outlet, Dim_Outlet[iqvia_outlet_name] <> \"Uncoded\" && Dim_Outlet[date_store_close] > start_period && Dim_Outlet[date_store_open] < currentperiod))"
            ],
            "formatString": "0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "LY_Dist_SKUOutlet_Store_Tot",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var last_year = calculate(values('Dim_Period'[MAT_year]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) - 1",
              "var seq = calculate(values('Dim_Period'[period_seq]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod))",
              "",
              "return calculate([Dist_SKUOutlet_Store_Tot], filter(all('Dim_Period'), Dim_Period[MAT_year] = last_year && 'Dim_Period'[period_seq] = seq && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "formatString": "0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "LP_Dist_SKUOutlet_Store_Tot",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var num = calculate(values('Dim_Period'[period_num]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) + 1",
              "",
              "return calculate([Dist_SKUOutlet_Store_Tot], filter(all('Dim_Period'), 'Dim_Period'[period_num] = num && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "formatString": "0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "PP_Dist_SKUOutlet_Store_Tot",
            "expression": [
              "if(HASONEVALUE(AUX_Previous_Period[name]), ",
              "SWITCH(TRUE(), values(AUX_Previous_Period[name]) = \"LY\", [LY_Dist_SKUOutlet_Store_Tot], [LP_Dist_SKUOutlet_Store_Tot]), [LY_Dist_SKUOutlet_Store_Tot])"
            ],
            "formatString": "0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "LY_Dist_SKUOutlet_Store",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var last_year = calculate(values('Dim_Period'[MAT_year]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) - 1",
              "var seq = calculate(values('Dim_Period'[period_seq]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod))",
              "",
              "return calculate([Dist_SKUOutlet_Store], filter(all('Dim_Period'), Dim_Period[MAT_year] = last_year && 'Dim_Period'[period_seq] = seq && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "formatString": "0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "LP_Dist_SKUOutlet_Store",
            "expression": [
              "",
              "var p_type = [Filter_PeriodType]",
              "var currentperiod = calculate(max('Dim_Period'[period_start]), filter(all('Dim_Period'[Period_Type]), 'Dim_Period'[Period_Type] = p_type))",
              "var num = calculate(values('Dim_Period'[period_num]), filter(all(Dim_Period), 'Dim_Period'[Period_Type] = p_type && 'Dim_Period'[period_start] = currentperiod)) + 1",
              "",
              "return calculate([Dist_SKUOutlet_Store], filter(all('Dim_Period'), 'Dim_Period'[period_num] = num && 'Dim_Period'[Period_Type] = p_type))"
            ],
            "formatString": "0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "PP_Dist_SKUOutlet_Store",
            "expression": [
              "if(HASONEVALUE(AUX_Previous_Period[name]), ",
              "SWITCH(TRUE(), values(AUX_Previous_Period[name]) = \"LY\", [LY_Dist_SKUOutlet_Store], [LP_Dist_SKUOutlet_Store]), [LY_Dist_SKUOutlet_Store])"
            ],
            "formatString": "0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Dist_%_SKUOutlet_Store",
            "expression": "divide([Dist_SKUOutlet_Store], [Dist_SKUOutlet_Store_Tot])",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Percentage\" Accuracy=\"2\" />"
              }
            ]
          },
          {
            "name": "Dist_%_Change_SKUOutlet_Store",
            "expression": "if([PP_Dist_%_SKUOutlet_Store] > 0, [Dist_%_SKUOutlet_Store] - [PP_Dist_%_SKUOutlet_Store])",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Percentage\" Accuracy=\"2\" />"
              }
            ]
          },
          {
            "name": "PP_Dist_%_SKUOutlet_Store",
            "expression": "divide([PP_Dist_SKUOutlet_Store], [PP_Dist_SKUOutlet_Store_Tot])",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Percentage\" Accuracy=\"2\" />"
              }
            ]
          },
          {
            "name": "PP_Dist_%_SKUOutlet_Weighted",
            "expression": "divide([PP_Sales_SKUOutlet_Period_Distributed], [PP_Sales_SKUOutlet_Period_Tot])",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Percentage\" Accuracy=\"2\" />"
              }
            ]
          },
          {
            "name": "Dist_%_SKUOutlet_Weighted",
            "expression": "divide([Sales_SKUOutlet_Period_Distributed], [Sales_SKUOutlet_Period_Tot])",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Percentage\" Accuracy=\"2\" />"
              }
            ]
          },
          {
            "name": "Dist_%_Change_SKUOutlet_Weighted",
            "expression": "[Dist_%_SKUOutlet_Weighted] - [PP_Dist_%_SKUOutlet_Weighted]",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Percentage\" Accuracy=\"2\" />"
              }
            ]
          },
          {
            "name": "Dist_Ind_Weighted_to_Store",
            "expression": "divide([Dist_%_SKUOutlet_Weighted], [Dist_%_SKUOutlet_Store]) * 100",
            "formatString": "#,0.0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberDecimal\" Accuracy=\"1\" ThousandSeparator=\"True\" />"
              }
            ]
          },
          {
            "name": "Dist_Change_SKUOutlet_Store",
            "expression": "if([PP_Dist_SKUOutlet_Store]> 0, [Dist_SKUOutlet_Store] - [PP_Dist_SKUOutlet_Store])",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Dist_Change_SKUOutlet_Store_Tot",
            "expression": "if([PP_Dist_SKUOutlet_Store_Tot] > 0, [Dist_SKUOutlet_Store_Tot] - [PP_Dist_SKUOutlet_Store_Tot])",
            "formatString": "0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "bb92984d-8a21-420c-8a44-536ffc9bb6cf"
          },
          {
            "name": "LinkedQueryName",
            "value": "Fact_Sales_Metrics_SKUOutlet"
          },
          {
            "name": "PBI_QueryRelationships",
            "value": "{\"columnCount\":1,\"keyColumnNames\":[],\"queryRelationships\":[],\"columnIdentities\":[\"Section1/Fact_Sales_Metrics_SKUOutlet/Changed Type.{Metrics,0}\"],\"ColumnCount\":1,\"KeyColumnNames\":[],\"ColumnIdentities\":[\"Section1/Fact_Sales_Metrics_SKUOutlet/Changed Type.{Metrics,0}\"],\"RelationshipInfo\":[]}"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "AUX_ReportTemplate",
        "isHidden": true,
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "metric_base",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[metric_base]",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "description",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[description]",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "report_use",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[report_use]",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "AUX_ReportTemplate-b5983602-83c2-453b-a146-9d51519e77ee",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "DATATABLE(  \"metric_base\", string,",
                "            \"report_use\", string,",
                "            \"description\", string,",
                "            {",
                "                    {\"SKU\", \"All\", \"The report is based on the metrics from SKU state level fact table, all purpose\"},",
                "                    {\"Outlet\", \"All\", \"The report is based on the metrics from Outlet Category level fact table, all purpose\"},",
                "                    {\"SKUOutlet\", \"All\", \"The report is based on the metrics from SKU and Outlet level fact table, all purpose. This is the lowest granularity.\"},",
                "                    {\"SKU\", \"Tab\", \"The report is based on the metrics from SKU state level fact table, for tabular report purpose\"},",
                "                    {\"Outlet\", \"Tab\", \"The report is based on the metrics from Outlet Category level fact table, for tabular report purpose\"},",
                "                    {\"SKUOutlet\", \"Tab\", \"The report is based on the metrics from SKU and Outlet level fact table, for tabular report purpose. This is the lowest granularity.\"}",
                "            })"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "26a2ae66063746dda45cc7dc96ab1777"
          }
        ]
      },
      {
        "name": "Fact_Sales",
        "columns": [
          {
            "name": "Metrics",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Metrics",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Metrics"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Fact_Sales-0503f3c7-ccf4-4595-9df0-976cd835ebca",
            "mode": "import",
            "source": {
              "type": "query",
              "query": "SELECT * FROM [Fact_Sales]",
              "dataSource": "4910aa27-f028-4766-834b-bb0ca731d9a1"
            }
          }
        ],
        "measures": [
          {
            "name": "Sales_Period",
            "expression": [
              "",
              "var pd_sales = if(HASONEVALUE(AUX_ReportTemplate[metric_base]), ",
              "\tSWITCH(TRUE(), ",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKU\", [Sales_SKU_Period], ",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"Outlet\", [Sales_Outlet_Period],",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKUOutlet\", [Sales_SKUOutlet_Period]",
              "\t), ",
              "\t[Sales_SKU_Period])",
              "    ",
              "return if([Filter_ReportUse], if([Filter_PeriodColumn_Display] > 0, pd_sales), pd_sales)   "
            ],
            "formatString": "#,0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" ThousandSeparator=\"True\" />"
              }
            ]
          },
          {
            "name": "Sales_Competitor",
            "expression": [
              "",
              "",
              "var c_sales = if(HASONEVALUE(AUX_ReportTemplate[metric_base]), ",
              "\tSWITCH(TRUE(), ",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKU\", [Sales_SKU_Competitor], ",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"Outlet\", [Sales_Outlet_Competitor],",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKUOutlet\", [Sales_SKUOutlet_Competitor]",
              "\t), ",
              "\t[Sales_SKU_Competitor])",
              "",
              "return if([Filter_ReportUse], if([Filter_PeriodColumn_Display] > 0, c_sales), c_sales)",
              ""
            ],
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Sales_Market",
            "expression": [
              "",
              "var m_sales = if(HASONEVALUE(AUX_ReportTemplate[metric_base]), ",
              "\tSWITCH(TRUE(), ",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKU\", [Sales_SKU_Market], ",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"Outlet\", [Sales_Outlet_Market],",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKUOutlet\", [Sales_SKUOutlet_Market]",
              "\t), ",
              "\t[Sales_SKU_Market])",
              "",
              "return if([Filter_ReportUse], if([Filter_PeriodColumn_Display] > 0, m_sales), m_sales)"
            ],
            "formatString": "#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" ThousandSeparator=\"True\" />"
              }
            ]
          },
          {
            "name": "Sales_Market_Category",
            "expression": [
              "",
              "",
              "var mc_sales = if(HASONEVALUE(AUX_ReportTemplate[metric_base]), ",
              "\tSWITCH(TRUE(), ",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKU\", [Sales_SKU_Market_Category], ",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKUOutlet\", [Sales_SKUOutlet_Market_Category]",
              "\t), ",
              "\t[Sales_SKU_Market_Category])",
              "",
              "return if([Filter_ReportUse], if([Filter_PeriodColumn_Display] > 0, mc_sales), mc_sales)"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Sales_Market_Pack",
            "expression": [
              "",
              "",
              "var mp_sales = if(HASONEVALUE(AUX_ReportTemplate[metric_base]), ",
              "\tSWITCH(TRUE(), ",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKU\", [Sales_SKU_Market_Pack], ",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKUOutlet\", [Sales_SKUOutlet_Market_Pack]",
              "\t), ",
              "\t[Sales_SKU_Market_Pack])",
              "",
              "return if([Filter_ReportUse], if([Filter_PeriodColumn_Display] > 0, mp_sales), mp_sales)"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Sales_Market_Parent",
            "expression": [
              "",
              "var m_sales_p = if(HASONEVALUE(AUX_ReportTemplate[metric_base]), ",
              "\tSWITCH(TRUE(), ",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKU\", [Sales_SKU_Market_Parent], ",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKUOutlet\", [Sales_SKUOutlet_Market_Parent]",
              "\t), ",
              "\t[Sales_SKU_Market_Parent])",
              "",
              "return if([Filter_ReportUse], if([Filter_PeriodColumn_Display] > 0, m_sales_p), m_sales_p)"
            ],
            "formatString": "#,0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" ThousandSeparator=\"True\" />"
              }
            ]
          },
          {
            "name": "Sales_Product",
            "expression": [
              "",
              "Var p_sales = if(HASONEVALUE(AUX_ReportTemplate[metric_base]), ",
              "\tSWITCH(TRUE(), ",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKU\", [Sales_SKU_Product], ",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"Outlet\", [Sales_Outlet_Product],",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKUOutlet\", [Sales_SKUOutlet_Product]",
              "\t), ",
              "\t[Sales_SKU_Product])",
              "\t",
              "\t",
              "return if([Filter_ReportUse], if([Filter_PeriodColumn_Display] > 0, p_sales), p_sales)"
            ],
            "formatString": "#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" ThousandSeparator=\"True\" />"
              }
            ]
          },
          {
            "name": "Sales_Product_Own",
            "expression": [
              "",
              "var p_sales_o = if(HASONEVALUE(AUX_ReportTemplate[metric_base]), ",
              "\tSWITCH(TRUE(), ",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKU\", [Sales_SKU_Product_Own], ",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"Outlet\", [Sales_Outlet_Product_Own],",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKUOutlet\", [Sales_SKUOutlet_Product_Own]",
              "\t), ",
              "\t[Sales_SKU_Product_Own])",
              "",
              "return if([Filter_ReportUse], if([Filter_PeriodColumn_Display] > 0, p_sales_o), p_sales_o)"
            ],
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "PP_MS_Category",
            "expression": [
              "",
              "var pp_ms_c = if(HASONEVALUE(AUX_ReportTemplate[metric_base]), ",
              "\tSWITCH(TRUE(), ",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKU\", [PP_MS_SKU_Category], ",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKUOutlet\", [PP_MS_SKUOutlet_Category]",
              "\t), ",
              "\t[PP_MS_SKU_Category])",
              "",
              "return if([Filter_ReportUse], if([Filter_PeriodColumn_Display] > 0, pp_ms_c), pp_ms_c)"
            ],
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "PP_MS_Parent",
            "expression": [
              "",
              "var pp_ms_pa = if(HASONEVALUE(AUX_ReportTemplate[metric_base]), ",
              "\tSWITCH(TRUE(), ",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKU\", [PP_MS_SKU_Parent],",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKUOutlet\", [PP_MS_SKUOutlet_Parent]",
              "\t), ",
              "\t[PP_MS_SKU_Parent])",
              "",
              "return if([Filter_ReportUse], if([Filter_PeriodColumn_Display] > 0, pp_ms_pa), pp_ms_pa)"
            ],
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "PP_MS_Product",
            "expression": [
              "",
              "var pp_ms_p = if(HASONEVALUE(AUX_ReportTemplate[metric_base]), ",
              "\tSWITCH(TRUE(), ",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKU\", [PP_MS_SKU_Product], ",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"Outlet\", [PP_MS_Outlet_Product],",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKUOutlet\", [PP_MS_SKUOutlet_Product]",
              "\t), ",
              "\t[PP_MS_SKU_Product])",
              "",
              "return if([Filter_ReportUse], if([Filter_PeriodColumn_Display] > 0, pp_ms_p), pp_ms_p)"
            ],
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "PP_Sales_Competitor",
            "expression": [
              "",
              "var pp_sales_co = if(HASONEVALUE(AUX_ReportTemplate[metric_base]), ",
              "\tSWITCH(TRUE(), ",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKU\", [PP_Sales_SKU_Competitor], ",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"Outlet\", [PP_Sales_Outlet_Competitor],",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKUOutlet\", [PP_Sales_SKUOutlet_Competitor]",
              "\t), ",
              "\t[PP_Sales_SKU_Competitor])",
              "",
              "return if([Filter_ReportUse], if([Filter_PeriodColumn_Display] > 0, pp_sales_co), pp_sales_co)"
            ],
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "PP_Sales_Market",
            "expression": [
              "",
              "var pp_sales_m = if(HASONEVALUE(AUX_ReportTemplate[metric_base]), ",
              "\tSWITCH(TRUE(), ",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKU\", [PP_Sales_SKU_Market], ",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"Outlet\", [PP_Sales_Outlet_Market],",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKUOutlet\", [PP_Sales_SKUOutlet_Market]",
              "\t), ",
              "\t[PP_Sales_SKU_Market])",
              "",
              "return if([Filter_ReportUse], if([Filter_PeriodColumn_Display] > 0, pp_sales_m), pp_sales_m)\t"
            ],
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "PP_Sales_Market_Category",
            "expression": [
              "",
              "var pp_sales_mc = if(HASONEVALUE(AUX_ReportTemplate[metric_base]), ",
              "\tSWITCH(TRUE(), ",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKU\", [PP_Sales_SKU_Market_Category], ",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKUOutlet\", [PP_Sales_SKUOutlet_Market_Category]",
              "\t), ",
              "\t[PP_Sales_SKU_Market_Category])",
              "",
              "return if([Filter_ReportUse], if([Filter_PeriodColumn_Display] > 0, pp_sales_mc), pp_sales_mc)"
            ],
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "PP_Sales_Market_Parent",
            "expression": [
              "",
              "var pp_sales_mp = if(HASONEVALUE(AUX_ReportTemplate[metric_base]), ",
              "\tSWITCH(TRUE(), ",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKU\", [PP_Sales_SKU_Market_Parent],",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKUOutlet\", [PP_Sales_SKUOutlet_Market_Parent]",
              "\t), ",
              "\t[PP_Sales_SKU_Market_Parent])",
              "",
              "return if([Filter_ReportUse], if([Filter_PeriodColumn_Display] > 0, pp_sales_mp), pp_sales_mp)"
            ],
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "PP_Sales_Period",
            "expression": [
              "",
              "var pp_sales_p = if(HASONEVALUE(AUX_ReportTemplate[metric_base]), ",
              "\tSWITCH(TRUE(), ",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKU\", [PP_Sales_SKU_Period], ",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"Outlet\", [PP_Sales_Outlet_Period],",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKUOutlet\", [PP_Sales_SKUOutlet_Period]",
              "\t), ",
              "\t[PP_Sales_SKU_Period])",
              "",
              "return if([Filter_ReportUse], if([Filter_PeriodColumn_Display] > 0, pp_sales_p), pp_sales_p)"
            ],
            "formatString": "#,0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" ThousandSeparator=\"True\" />"
              }
            ]
          },
          {
            "name": "PP_Sales_Product",
            "expression": [
              "",
              "var pp_p_sales = if(HASONEVALUE(AUX_ReportTemplate[metric_base]), ",
              "\tSWITCH(TRUE(), ",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKU\", [PP_Sales_SKU_Product], ",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"Outlet\", [PP_Sales_Outlet_Product],",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKUOutlet\", [PP_Sales_SKUOutlet_Product]",
              "\t), ",
              "\t[PP_Sales_SKU_Product])",
              "",
              "return if([Filter_ReportUse], if([Filter_PeriodColumn_Display] > 0, pp_p_sales), pp_p_sales)"
            ],
            "formatString": "#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" ThousandSeparator=\"True\" />"
              }
            ]
          },
          {
            "name": "PP_Sales_Product_Own",
            "expression": [
              "",
              "var p_sales_o = if(HASONEVALUE(AUX_ReportTemplate[metric_base]), ",
              "\tSWITCH(TRUE(), ",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKU\", [PP_Sales_SKU_Product_Own], ",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKUOutlet\", [PP_Sales_SKUOutlet_Product_Own]",
              "\t), ",
              "\t[PP_Sales_SKU_Product_Own])",
              "",
              "return if([Filter_ReportUse], if([Filter_PeriodColumn_Display] > 0, p_sales_o), p_sales_o)"
            ],
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "MS_Change",
            "expression": [
              "",
              "var ms_c = if(HASONEVALUE(AUX_ReportTemplate[metric_base]), ",
              "\tSWITCH(TRUE(), ",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKU\", [MS_Change_SKU], ",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"Outlet\", [MS_Change_Outlet],",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKUOutlet\", [MS_Change_SKUOutlet]",
              "\t), ",
              "\t[MS_Change_SKU])",
              "",
              "return if([Filter_ReportUse], if([Filter_PeriodColumn_Display] > 0, ms_c), ms_c)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Percentage\" Accuracy=\"2\" />"
              }
            ]
          },
          {
            "name": "MS_Category",
            "expression": [
              "",
              "var ms_cat = if(HASONEVALUE(AUX_ReportTemplate[metric_base]), ",
              "\tSWITCH(TRUE(), ",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKU\", [MS_SKU_Category], ",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKUOutlet\", [MS_SKUOutlet_Category]",
              "\t), ",
              "\t[MS_SKU_Category])",
              "",
              "return if([Filter_ReportUse], if([Filter_PeriodColumn_Display] > 0, ms_cat), ms_cat)"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Percentage\" Accuracy=\"1\" />"
              }
            ]
          },
          {
            "name": "MS_Parent",
            "expression": [
              "",
              "var ms_pa = if(HASONEVALUE(AUX_ReportTemplate[metric_base]), ",
              "\tSWITCH(TRUE(), ",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKU\", [MS_SKU_Parent], ",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKUOutlet\", [MS_SKUOutlet_Parent]",
              "\t), ",
              "\t[MS_SKU_Parent])",
              "",
              "return if([Filter_ReportUse], if([Filter_PeriodColumn_Display] > 0, ms_pa), ms_pa)"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Percentage\" Accuracy=\"1\" />"
              }
            ]
          },
          {
            "name": "MS_Product",
            "expression": [
              "",
              "var ms_p = if(HASONEVALUE(AUX_ReportTemplate[metric_base]), ",
              "\tSWITCH(TRUE(), ",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKU\", [MS_SKU_Product], ",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"Outlet\", [MS_Outlet_Product],",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKUOutlet\", [MS_SKUOutlet_Product]",
              "\t), ",
              "\t[MS_SKU_Product])",
              "",
              "return if([Filter_ReportUse], if([Filter_PeriodColumn_Display] > 0, ms_p), ms_p)"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Percentage\" Accuracy=\"1\" />"
              }
            ]
          },
          {
            "name": "Gth_%_Market",
            "expression": [
              "",
              "var gth_pc_m = if(HASONEVALUE(AUX_ReportTemplate[metric_base]), ",
              "\tSWITCH(TRUE(), ",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKU\", [Gth_%_SKU_Market], ",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"Outlet\", [Gth_%_Outlet_Market],",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKUOutlet\", [Gth_%_SKUOutlet_Market]",
              "\t), ",
              "\t[Gth_%_SKU_Market])",
              "",
              "return if([Filter_ReportUse], if([Filter_PeriodColumn_Display] > 0, gth_pc_m), gth_pc_m)"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Percentage\" Accuracy=\"1\" />"
              }
            ]
          },
          {
            "name": "Gth_%_Period",
            "expression": [
              "",
              "var gth_pc_per = if(HASONEVALUE(AUX_ReportTemplate[metric_base]), ",
              "\tSWITCH(TRUE(), ",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKU\", [Gth_%_SKU_Period], ",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"Outlet\", [Gth_%_Outlet_Period],",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKUOutlet\", [Gth_%_SKUOutlet_Period]",
              "\t), ",
              "\t[Gth_%_SKU_Period])",
              "",
              "return if([Filter_ReportUse], if([Filter_PeriodColumn_Display] > 0, gth_pc_per), gth_pc_per)"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Percentage\" Accuracy=\"1\" />"
              }
            ]
          },
          {
            "name": "Gth_%_Product",
            "expression": [
              "",
              "var gth_pc = if(HASONEVALUE(AUX_ReportTemplate[metric_base]), ",
              "\tSWITCH(TRUE(), ",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKU\", [Gth_%_SKU_Product], ",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"Outlet\", [Gth_%_Outlet_Product],",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKUOutlet\", [Gth_%_SKUOutlet_Product]",
              "\t), ",
              "\t[Gth_%_SKU_Product])",
              "",
              "return if([Filter_ReportUse], if([Filter_PeriodColumn_Display] > 0, gth_pc), gth_pc)"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Percentage\" Accuracy=\"1\" />"
              }
            ]
          },
          {
            "name": "Gth_Market",
            "expression": [
              "",
              "var gth_m = if(HASONEVALUE(AUX_ReportTemplate[metric_base]), ",
              "\tSWITCH(TRUE(), ",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKU\", [Gth_SKU_Market], ",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"Outlet\", [Gth_Outlet_Market],",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKUOutlet\", [Gth_SKUOutlet_Market]",
              "\t), ",
              "\t[Gth_SKU_Market])",
              "",
              "return if([Filter_ReportUse], if([Filter_PeriodColumn_Display] > 0, gth_m), gth_m)"
            ],
            "formatString": "#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" ThousandSeparator=\"True\" />"
              }
            ]
          },
          {
            "name": "Gth_Period",
            "expression": [
              "",
              "var gth_per = if(HASONEVALUE(AUX_ReportTemplate[metric_base]), ",
              "\tSWITCH(TRUE(), ",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKU\", [Gth_SKU_Period], ",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"Outlet\", [Gth_Outlet_Period],",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKUOutlet\", [Gth_SKUOutlet_Period]",
              "\t), ",
              "\t[Gth_SKU_Period])",
              "",
              "return if([Filter_ReportUse], if([Filter_PeriodColumn_Display] > 0, gth_per), gth_per)"
            ],
            "formatString": "#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" ThousandSeparator=\"True\" />"
              }
            ]
          },
          {
            "name": "Gth_Product",
            "expression": [
              "",
              "var gth_p = if(HASONEVALUE(AUX_ReportTemplate[metric_base]), ",
              "\tSWITCH(TRUE(), ",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKU\", [Gth_SKU_Product], ",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"Outlet\", [Gth_Outlet_Product],",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKUOutlet\", [Gth_SKUOutlet_Product]",
              "\t), ",
              "\t[Gth_SKU_Product])",
              "",
              "return if([Filter_ReportUse], if([Filter_PeriodColumn_Display] > 0, gth_p), gth_p)"
            ],
            "formatString": "#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" ThousandSeparator=\"True\" />"
              }
            ]
          },
          {
            "name": "Rank_Market",
            "expression": [
              "",
              "var m_rank = if(HASONEVALUE(AUX_ReportTemplate[metric_base]), ",
              "\tSWITCH(TRUE(), ",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKU\", [Rank_SKU_Market], ",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"Outlet\", [Rank_Outlet_Market],",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKUOutlet\", [Rank_SKUOutlet_Market]",
              "\t), ",
              "\t[Rank_SKU_Market])",
              "",
              "return if([Filter_ReportUse], if([Filter_PeriodColumn_Display] > 0, m_rank), m_rank)"
            ],
            "formatString": "0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Rank_Product",
            "expression": [
              "",
              "var p_rank = if(HASONEVALUE(AUX_ReportTemplate[metric_base]), ",
              "\tSWITCH(TRUE(), ",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKU\", [Rank_SKU_Product], ",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"Outlet\", [Rank_Outlet_Product],",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKUOutlet\", [Rank_SKUOutlet_Product]",
              "\t), ",
              "\t[Rank_SKU_Product])",
              "",
              "return if([Filter_ReportUse], if([Filter_PeriodColumn_Display] > 0, p_rank), p_rank)"
            ],
            "formatString": "0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "EI",
            "expression": [
              "",
              "var ei = if(HASONEVALUE(AUX_ReportTemplate[metric_base]), ",
              "\tSWITCH(TRUE(), ",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKU\", [EI_SKU], ",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"Outlet\", [EI_Outlet],",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKUOutlet\", [EI_SKUOutlet]",
              "\t), ",
              "\t[EI_SKU])",
              "",
              "return if([Filter_ReportUse], if([Filter_PeriodColumn_Display] > 0, ei), ei)"
            ],
            "formatString": "0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Measure_LineChart_T",
            "expression": [
              "if(HASONEVALUE(AUX_LineChartMeasure[LineMeasure]), ",
              "\tSWITCH(TRUE(), ",
              "\tvalues(AUX_LineChartMeasure[LineMeasure]) in {\"MS\", \"P_Gth_%\", \"M_Gth_%\"}, FORMAT([Measure_LineChart_V], \"0.00%\"), ",
              "\tvalues(AUX_LineChartMeasure[LineMeasure]) in {\"P_Sales\", \"M_Sales\", \"P_Gth\", \"M_Gth\"}, if(values(Dim_Measure_Type[Measure]) = \"Amount\", FORMAT([Measure_LineChart_V], \"$#,##0\"), FORMAT([Measure_LineChart_V], \"#,##0\")),",
              "\tvalues(AUX_LineChartMeasure[LineMeasure]) in {\"P_PC\", \"M_PC\"}, if(values(Dim_Measure_Type[Measure]) = \"Amount\", FORMAT([Measure_LineChart_V], \"$#,##0.00\"), FORMAT([Measure_LineChart_V], \"#,##0.00\")),",
              "\tvalues(AUX_LineChartMeasure[LineMeasure]) in {\"Pop_Density\"},  FORMAT([Measure_LineChart_V], \"0.00\"),",
              "\tvalues(AUX_LineChartMeasure[LineMeasure]) in {\"EI\", \"Pop_PS\"}, FORMAT([EI], \"0\")",
              "\t), ",
              "\tFORMAT([Measure_LineChart_V], \"0.00%\"))"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "Measure_LineChart_V",
            "expression": [
              "if(HASONEVALUE(AUX_LineChartMeasure[LineMeasure]), ",
              "\tSWITCH(TRUE(), ",
              "\tvalues(AUX_LineChartMeasure[LineMeasure]) = \"MS\", [MS_Product], ",
              "    values(AUX_LineChartMeasure[LineMeasure]) = \"MSC\", [MS_Change],",
              "\tvalues(AUX_LineChartMeasure[LineMeasure]) = \"P_Sales\", [Sales_Product],",
              "\tvalues(AUX_LineChartMeasure[LineMeasure]) = \"EI\", [EI],",
              "\tvalues(AUX_LineChartMeasure[LineMeasure]) = \"M_Sales\", [Sales_Market],",
              "\tvalues(AUX_LineChartMeasure[LineMeasure]) = \"P_Gth\", [Gth_Product],",
              "\tvalues(AUX_LineChartMeasure[LineMeasure]) = \"M_Gth\", [Gth_Market],",
              "\tvalues(AUX_LineChartMeasure[LineMeasure]) = \"P_Gth_%\", [Gth_%_Product],",
              "\tvalues(AUX_LineChartMeasure[LineMeasure]) = \"M_Gth_%\", [Gth_%_Market],",
              "\tvalues(AUX_LineChartMeasure[LineMeasure]) = \"Pop_Density\", [Geo_Pop_Density],",
              "\tvalues(AUX_LineChartMeasure[LineMeasure]) = \"Pop_PS\", [Geo_Pop_Per_Store],",
              "\tvalues(AUX_LineChartMeasure[LineMeasure]) = \"P_PC\", [Sales_Prod_Per_Capita],",
              "\tvalues(AUX_LineChartMeasure[LineMeasure]) = \"M_PC\", [Sales_Market_Per_Capita]",
              "\t), ",
              "\t[MS_Product])"
            ],
            "formatString": "#,0.00",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberDecimal\" Accuracy=\"2\" ThousandSeparator=\"True\" />"
              }
            ]
          },
          {
            "name": "Count_L1_Total",
            "expression": [
              "",
              "var hier_id = Calculate(values(Dim_Hierarchy_Name_Product[hierarchy_id]), Dim_Hierarchy_Name_Product[hierarchy_name] = values(Dim_Hierarchy_Name_Product[hierarchy_name]))",
              "",
              "return calculate(countrows(values('Dim_Product_Client_Hierarchy'[prod_level_1])), filter(all('Dim_Product_Client_Hierarchy'),'Dim_Product_Client_Hierarchy'[hierarchy_id] = hier_id))"
            ],
            "formatString": "0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Count_L1",
            "expression": "calculate(countrows(values('Dim_Product_Client_Hierarchy'[prod_level_1])))",
            "formatString": "0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Count_L2_Total",
            "expression": [
              "",
              "var hier_id = Calculate(values(Dim_Hierarchy_Name_Product[hierarchy_id]), Dim_Hierarchy_Name_Product[hierarchy_name] = values(Dim_Hierarchy_Name_Product[hierarchy_name]))",
              "",
              "return calculate(countrows(values('Dim_Product_Client_Hierarchy'[prod_level_2])), filter(all('Dim_Product_Client_Hierarchy'),'Dim_Product_Client_Hierarchy'[hierarchy_id] = hier_id))"
            ],
            "formatString": "0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Count_L3_Total",
            "expression": [
              "",
              "var hier_id = Calculate(values(Dim_Hierarchy_Name_Product[hierarchy_id]), Dim_Hierarchy_Name_Product[hierarchy_name] = values(Dim_Hierarchy_Name_Product[hierarchy_name]))",
              "",
              "return calculate(countrows(values('Dim_Product_Client_Hierarchy'[prod_level_3])), filter(all('Dim_Product_Client_Hierarchy'),'Dim_Product_Client_Hierarchy'[hierarchy_id] = hier_id))"
            ],
            "formatString": "0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Count_L2",
            "expression": "calculate(countrows(values('Dim_Product_Client_Hierarchy'[prod_level_2])))",
            "formatString": "0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Count_L3",
            "expression": "calculate(countrows(values('Dim_Product_Client_Hierarchy'[prod_level_3])))",
            "formatString": "0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Count_State_Total",
            "expression": "calculate(countrows(values(Dim_State[State_Group])), All(Dim_State))",
            "formatString": "0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Count_State",
            "expression": "calculate(countrows(values(Dim_State[State_Group])))",
            "formatString": "0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Top_Gth_%_Product",
            "expression": [
              "",
              "if(hasonevalue('AUX_Top_Selection_Prod'[Top_Value]),",
              "if([Rank_Product] <= values('AUX_Top_Selection_Prod'[Top_Value]), [Gth_%_Product], BLANK()))"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Percentage\" Accuracy=\"2\" />"
              }
            ]
          },
          {
            "name": "Gth_%_Period_Display",
            "expression": "if(abs([Gth_%_Period]) > 1, BLANK(), [Gth_%_Period])",
            "formatString": "0.0%;-0.0%;0.0%",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Percentage\" Accuracy=\"1\" />"
              }
            ]
          },
          {
            "name": "Measure_Chart_TnB",
            "expression": [
              "if(HASONEVALUE(AUX_Top_Select_Option[top_option]), ",
              "\tSWITCH(TRUE(), ",
              "\tvalues(AUX_Top_Select_Option[top_option]) = \"Value\", [Sales_Period], ",
              "    [Gth_Period]",
              "\t), ",
              "\t[Gth_Period])"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Sales_Market_TnB",
            "expression": [
              "if(HASONEVALUE(AUX_ReportTemplate[metric_base]), ",
              "\tSWITCH(TRUE(), ",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKU\", [Sales_SKU_Market_TnB], ",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"Outlet\", [Sales_Outlet_Market_TnB],",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKUOutlet\", [Sales_SKUOutlet_Market_TnB]",
              "\t), ",
              "\t[Sales_SKU_Market_TnB])"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "MS_TnB",
            "expression": "DIVIDE([Sales_Period], [Sales_Market_TnB])",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Percentage\" Accuracy=\"2\" />"
              }
            ]
          },
          {
            "name": "PP_Sales_Market_TnB",
            "expression": [
              "if(HASONEVALUE(AUX_ReportTemplate[metric_base]), ",
              "\tSWITCH(TRUE(), ",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKU\", [PP_Sales_SKU_Market_TnB], ",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"Outlet\", [PP_Sales_Outlet_Market_TnB],",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKUOutlet\", [PP_Sales_SKUOutlet_Market_TnB]",
              "\t), ",
              "\t[PP_Sales_SKU_Market_TnB])",
              "\t"
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "PP_MS_TnB",
            "expression": "DIVIDE([PP_Sales_Period], [PP_Sales_Market_TnB])",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "MS_Change_TnB",
            "expression": "[MS_TnB] - [PP_MS_TnB]",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Percentage\" Accuracy=\"2\" />"
              }
            ]
          },
          {
            "name": "Count_Category",
            "expression": "calculate(countrows(values('Dim_Category'[Category])))",
            "formatString": "0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Count_Category_Total",
            "expression": "calculate(countrows(values('Dim_Category'[Category])), All(Dim_Category[Category]))",
            "formatString": "0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Max_Sales_Period_POP",
            "expression": "Max([Sales_Period], [PP_Sales_Period])",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Geo_Area",
            "expression": "calculate(sum('Dim_Geography'[Area]))",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Geo_Population",
            "expression": "calculate(sum('Dim_Geography'[Population]))",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Geo_Store",
            "expression": "calculate(sum('Dim_Geography'[Store_Num]))",
            "formatString": "0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Sales_Prod_Per_Capita",
            "expression": "divide([Sales_Product], [Geo_Population])",
            "formatString": "#,0.000",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberDecimal\" Accuracy=\"3\" ThousandSeparator=\"True\" />"
              }
            ]
          },
          {
            "name": "Sales_Market_Per_Capita",
            "expression": "divide([Sales_Market], [Geo_Population])",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Sales_Period_Per_Capita",
            "expression": "divide([Sales_Period], [Geo_Population])",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Geo_Pop_Density",
            "expression": "divide([Geo_Population], [Geo_Area])",
            "formatString": "#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberDecimal\" Accuracy=\"2\" ThousandSeparator=\"True\" />"
              }
            ]
          },
          {
            "name": "Geo_Pop_Per_Store",
            "expression": "divide([Geo_Population], [Geo_Store])",
            "formatString": "#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" ThousandSeparator=\"True\" />"
              }
            ]
          },
          {
            "name": "Empty_Value",
            "expression": "calculate(sum('Dim_Geography'[Dummy_Value]))",
            "formatString": "0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Measure_GeoMap_V",
            "expression": [
              "if(HASONEVALUE(AUX_LineChartMeasure_2[LineMeasure]), ",
              "\tSWITCH(TRUE(), ",
              "\tvalues(AUX_LineChartMeasure_2[LineMeasure]) = \"MS\", [MS_Product], ",
              "\tvalues(AUX_LineChartMeasure_2[LineMeasure]) = \"P_Sales\", [Sales_Product],",
              "\tvalues(AUX_LineChartMeasure_2[LineMeasure]) = \"EI\", [EI],",
              "\tvalues(AUX_LineChartMeasure_2[LineMeasure]) = \"M_Sales\", [Sales_Market],",
              "\tvalues(AUX_LineChartMeasure_2[LineMeasure]) = \"P_Gth\", [Gth_Product],",
              "\tvalues(AUX_LineChartMeasure_2[LineMeasure]) = \"M_Gth\", [Gth_Market],",
              "\tvalues(AUX_LineChartMeasure_2[LineMeasure]) = \"P_Gth_%\", [Gth_%_Product],",
              "\tvalues(AUX_LineChartMeasure_2[LineMeasure]) = \"M_Gth_%\", [Gth_%_Market],",
              "\tvalues(AUX_LineChartMeasure_2[LineMeasure]) = \"Pop_Density\", [Geo_Pop_Density],",
              "\tvalues(AUX_LineChartMeasure_2[LineMeasure]) = \"Pop_PS\", [Geo_Pop_Per_Store],",
              "\tvalues(AUX_LineChartMeasure_2[LineMeasure]) = \"P_PC\", [Sales_Prod_Per_Capita],",
              "\tvalues(AUX_LineChartMeasure_2[LineMeasure]) = \"M_PC\", [Sales_Market_Per_Capita],",
              "\tvalues(AUX_LineChartMeasure_2[LineMeasure]) = \"Dummy\", [Empty_Value]",
              "\t), ",
              "\t[MS_Product])"
            ],
            "formatString": "#,0.00",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberDecimal\" Accuracy=\"2\" ThousandSeparator=\"True\" />"
              }
            ]
          },
          {
            "name": "Sales_Prod_Per_Capita_All",
            "expression": "calculate([Sales_Prod_Per_Capita], all('Dim_Geography'[Geography_Name]), all('Dim_Geography'[State]))",
            "formatString": "#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberDecimal\" Accuracy=\"2\" ThousandSeparator=\"True\" />"
              }
            ]
          },
          {
            "name": "Index_Sales_Prod_Per_Capita_to_Nation",
            "expression": "divide([Sales_Prod_Per_Capita], [Sales_Prod_Per_Capita_All]) * 100",
            "formatString": "0.0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberDecimal\" Accuracy=\"1\" />"
              }
            ]
          },
          {
            "name": "Sales_Market_Per_Capita_All",
            "expression": "calculate([Sales_Market_Per_Capita], all('Dim_Geography'[Geography_Name]))",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Index_Sales_Market_Per_Capita_to_Nation",
            "expression": "divide([Sales_Market_Per_Capita], [Sales_Market_Per_Capita_All]) * 100",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Count_GeoState",
            "expression": "calculate(countrows(values(Dim_Geography[State])))",
            "formatString": "0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Count_GeoState_Total",
            "expression": [
              "",
              "var geo_type = selectedvalue(Dim_Geography_Type[Geography_Type], \"State\")",
              "return calculate(countrows(values(Dim_Geography[State])), 'Dim_Geography_Type'[Geography_Type] = geo_type, ALL(Dim_Geography[State]))"
            ],
            "formatString": "0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Booleon_NoMarket",
            "expression": "if(ISBLANK([Sales_Market]), 1, 0)",
            "formatString": "0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Sales_Period_Amount",
            "expression": "calculate([Sales_Period], filter(All(Dim_Measure_Type[Measure]), Dim_Measure_Type[Measure] = \"Amount\"))",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Sales_Period_Unit",
            "expression": "calculate([Sales_Period], filter(All(Dim_Measure_Type[Measure]), Dim_Measure_Type[Measure] = \"Unit\")) ",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Sales_Price",
            "expression": "divide([Sales_Period_Amount], [Sales_Period_Unit])",
            "formatString": "#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberDecimal\" Accuracy=\"2\" ThousandSeparator=\"True\" />"
              }
            ]
          },
          {
            "name": "PP_Sales_Period_Amount",
            "expression": "calculate([PP_Sales_Period], filter(All(Dim_Measure_Type[Measure]), Dim_Measure_Type[Measure] = \"Amount\"))",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "PP_Sales_Period_Unit",
            "expression": "calculate([PP_Sales_Period], filter(All(Dim_Measure_Type[Measure]), Dim_Measure_Type[Measure] = \"Unit\"))",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "PP_Sales_Price",
            "expression": "divide([PP_Sales_Period_Amount], [PP_Sales_Period_Unit]) ",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Price_Change",
            "expression": "[Sales_Price] - [PP_Sales_Price]",
            "formatString": "#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberDecimal\" Accuracy=\"2\" ThousandSeparator=\"True\" />"
              }
            ]
          },
          {
            "name": "Price_Change_%",
            "expression": "DIVIDE([Price_Change], [PP_Sales_Price])",
            "formatString": "0.00%;-0.00%;0.00%",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Percentage\" Accuracy=\"2\" />"
              }
            ]
          },
          {
            "name": "Sales_Price_AVG",
            "expression": "calculate(divide([Sales_Base_Amount], [Sales_Base_Unit]), filter(ALLEXCEPT(Dim_Period, Dim_Period[Period_Month_Name]), Dim_Period[Period_Type] = [Filter_PeriodType]))",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Sales_Base",
            "expression": [
              "",
              "var pd_sales = if(HASONEVALUE(AUX_ReportTemplate[metric_base]), ",
              "\tSWITCH(TRUE(), ",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKU\", [Sales_SKU_Base], ",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"Outlet\", [Sales_Outlet_Base],",
              "\tvalues(AUX_ReportTemplate[metric_base]) = \"SKUOutlet\", [Sales_SKUOutlet_Base]",
              "\t), ",
              "\t[Sales_SKU_Base])",
              "    ",
              "return if([Filter_ReportUse], if([Filter_PeriodColumn_Display] > 0, pd_sales), pd_sales) "
            ],
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Sales_Base_Amount",
            "expression": "calculate([Sales_Base], filter(All(Dim_Measure_Type[Measure]), Dim_Measure_Type[Measure] = \"Amount\"))",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Sales_Base_Unit",
            "expression": "calculate([Sales_Base], filter(All(Dim_Measure_Type[Measure]), Dim_Measure_Type[Measure] = \"Unit\")) ",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Dist_%_Change_Store",
            "expression": "[Dist_%_Change_SKUOutlet_Store]",
            "formatString": "0.00%;-0.00%;0.00%",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Percentage\" Accuracy=\"2\" />"
              }
            ]
          },
          {
            "name": "Dist_%_Change_Weighted",
            "expression": "[Dist_%_Change_SKUOutlet_Weighted]",
            "formatString": "0.00%;-0.00%;0.00%",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Percentage\" Accuracy=\"2\" />"
              }
            ]
          },
          {
            "name": "Dist_%_Store",
            "expression": "[Dist_%_SKUOutlet_Store]",
            "formatString": "0.0%;-0.0%;0.0%",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Percentage\" Accuracy=\"1\" />"
              }
            ]
          },
          {
            "name": "Dist_%_Weighted",
            "expression": "[Dist_%_SKUOutlet_Weighted]",
            "formatString": "0.0%;-0.0%;0.0%",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Percentage\" Accuracy=\"1\" />"
              }
            ]
          },
          {
            "name": "PP_Dist_%_Store",
            "expression": "[PP_Dist_%_SKUOutlet_Store]",
            "formatString": "0.0%;-0.0%;0.0%",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Percentage\" Accuracy=\"1\" />"
              }
            ]
          },
          {
            "name": "PP_Dist_%_Weighted",
            "expression": "[PP_Dist_%_SKUOutlet_Weighted]",
            "formatString": "0.0%;-0.0%;0.0%",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Percentage\" Accuracy=\"1\" />"
              }
            ]
          },
          {
            "name": "Dist_Store",
            "expression": "[Dist_SKUOutlet_Store]",
            "formatString": "0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Dist_Store_Tot",
            "expression": "if(countrows(Fact_SKU_Outlet_Sales) > 0, [Dist_SKUOutlet_Store_Tot])",
            "formatString": "0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Dist_Change_Store",
            "expression": "[Dist_Change_SKUOutlet_Store]",
            "formatString": "0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Dist_Change_Store_Tot",
            "expression": "[Dist_Change_SKUOutlet_Store_Tot]",
            "formatString": "0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "PP_Dist_Store",
            "expression": "[PP_Dist_SKUOutlet_Store]",
            "formatString": "0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "PP_Dist_Store_Tot",
            "expression": "[PP_Dist_SKUOutlet_Store_Tot]",
            "formatString": "0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "7857afec-bfe5-4d99-a213-e008a3077230"
          },
          {
            "name": "LinkedQueryName",
            "value": "Fact_Sales"
          },
          {
            "name": "PBI_QueryRelationships",
            "value": "{\"columnCount\":1,\"keyColumnNames\":[],\"queryRelationships\":[],\"columnIdentities\":[\"Section1/Fact_Sales/Changed Type.{Metrics,0}\"],\"ColumnCount\":1,\"KeyColumnNames\":[],\"ColumnIdentities\":[\"Section1/Fact_Sales/Changed Type.{Metrics,0}\"],\"RelationshipInfo\":[]}"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "AUX_LineChartMeasure",
        "isHidden": true,
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "LineMeasure",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[LineMeasure]",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "LineMeasure_Display",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[LineMeasure_Display]",
            "sortByColumn": "order",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "order",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[order]",
            "formatString": "0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "For_LineCHart",
            "dataType": "boolean",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[For_LineCHart]",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Boolean\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Boolean#####not a type"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "For_Geo",
            "dataType": "boolean",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[For_Geo]",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Boolean\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Boolean#####not a type"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "AUX_LineChartMeasure-436c7468-5bf4-42b3-bbc1-ea443d2c4b75",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "DATATABLE(  \"LineMeasure\", string,",
                "            \"LineMeasure_Display\", string,",
                "            \"order\", INTEGER,",
                "            \"For_LineCHart\", BOOLEAN,",
                "            \"For_Geo\", BOOLEAN,",
                "            {",
                "                    {\"MS\", \"Market Share\", 0, 1, 1},",
                "                    {\"MSC\", \"Market Change\", 1, 1, 1},",
                "                    {\"EI\", \"Evolution Index\", 2, 1, 0},",
                "                    {\"P_Sales\", \"Product Sales\", 3, 1, 1},",
                "                    {\"M_Sales\", \"Market Sales\", 4, 1, 1},",
                "                    {\"P_Gth\", \"Product Growth Value\", 5, 1, 1},",
                "                    {\"M_Gth\", \"Market Growth Value\", 6, 1, 1},",
                "                    {\"P_Gth_%\", \"Product Growth %\", 7, 1, 0},",
                "                    {\"M_Gth_%\", \"Market Growth %\", 8, 1, 0},",
                "                    {\"Pop_Density\", \"Population Density\", 9, 0, 1},",
                "                    {\"Pop_PS\", \"AVG Population per Store\", 10, 0, 1},",
                "                    {\"P_PC\", \"Product Sales per Capita\", 11,0, 1},",
                "                    {\"M_PC\", \"Market Sales per Capita\", 12, 0, 1}",
                "            })"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "4c023d009918419f885cfa1d53b02933"
          }
        ]
      },
      {
        "name": "Dim_Period_Alone",
        "isHidden": true,
        "columns": [
          {
            "name": "period_type",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "period_type",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "period_type"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "period_type_order",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "period_type_order",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "period_type_order"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "period_name",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "period_name",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "period_name"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "period_long_name",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "period_long_name",
            "sortByColumn": "sort_column",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "period_long_name"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "period_year",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "period_year",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "period_year"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "period_num",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "period_num",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "period_num"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "year_display",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "year_display",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "year_display"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "sort_column",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "Dim_Period_Alone[period_type]  & (10000 + Dim_Period_Alone[period_num])",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Dim_Period_Alone-65c417a0-f68e-4e12-a5a0-3add70d37629",
            "mode": "import",
            "source": {
              "type": "query",
              "query": "SELECT * FROM [Dim_Period_Alone]",
              "dataSource": "dd39479b-a8d2-4895-aebe-359b228ec7d1"
            }
          }
        ],
        "measures": [
          {
            "name": "Filter_PeriodDisplay",
            "expression": [
              "",
              "var type_selected = values('Dim_Period'[Period_Type])",
              "",
              "return if(values(Dim_Period_Alone[period_type]) in type_selected, 1, 0)",
              "",
              ""
            ],
            "formatString": "0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "3186dbe6-d1ba-4025-8dde-53cfc2aeb691"
          },
          {
            "name": "LinkedQueryName",
            "value": "Dim_Period_Alone"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_QueryRelationships",
            "value": "{\"columnCount\":7,\"keyColumnNames\":[\"period_type\",\"period_type_order\",\"period_name\",\"period_long_name\",\"period_year\",\"period_num\",\"year_display\"],\"queryRelationships\":[],\"columnIdentities\":[\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_MthWk.{period_type,1}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_MthWk.{period_type_order,2}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_MthWk.{period_name,3}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_MthWk.{period_long_name,4}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_MthWk.{period_year,5}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_MthWk.{period_num,14}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_MthWk.{year_display,15}\"],\"ColumnCount\":7,\"KeyColumnNames\":[\"period_type\",\"period_type_order\",\"period_name\",\"period_long_name\",\"period_year\",\"period_num\",\"year_display\"],\"ColumnIdentities\":[\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_MthWk.{period_type,1}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_MthWk.{period_type_order,2}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_MthWk.{period_name,3}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_MthWk.{period_long_name,4}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_MthWk.{period_year,5}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_MthWk.{period_num,14}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_MthWk.{year_display,15}\"],\"RelationshipInfo\":[]}"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Dim_Period_Type",
        "columns": [
          {
            "name": "Period_Type",
            "dataType": "string",
            "sourceColumn": "Period_Type",
            "sortByColumn": "period_type_order",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Period_Type"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "period_type_order",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "period_type_order",
            "formatString": "0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "period_type_order"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Dim_Period_Type-c438d2c8-dc76-4bea-ad12-7de1729fcd57",
            "mode": "import",
            "source": {
              "type": "query",
              "query": "SELECT * FROM [Dim_Period_Type]",
              "dataSource": "2d58a897-0f58-4fc7-8929-0ed3b2ddf5e3"
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "84fef608-8f75-4d4f-9c83-257fd8c457e3"
          },
          {
            "name": "LinkedQueryName",
            "value": "Dim_Period_Type"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_QueryRelationships",
            "value": "{\"columnCount\":2,\"keyColumnNames\":[\"period_type\",\"period_type_order\"],\"queryRelationships\":[],\"columnIdentities\":[\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_MthWk.{period_type,1}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_MthWk.{period_type_order,2}\"],\"ColumnCount\":2,\"KeyColumnNames\":[\"period_type\",\"period_type_order\"],\"ColumnIdentities\":[\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_MthWk.{period_type,1}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Period_MthWk.{period_type_order,2}\"],\"RelationshipInfo\":[]}"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Dim_Geography_Store",
        "isHidden": true,
        "columns": [
          {
            "name": "cw_outlet_key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "cw_outlet_key",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "cw_outlet_key"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "geography_name_id",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "geography_name_id",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "geography_name_id"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Dim_Geography_Store-ca091e54-806f-4990-870a-37db098a21af",
            "mode": "import",
            "source": {
              "type": "query",
              "query": "SELECT * FROM [Dim_Geography_Store]",
              "dataSource": "20622d71-6ee0-443c-ba3c-913bd1aaa249"
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "dc0d4804-ef46-46d7-ab6a-7be0d2acbdff"
          },
          {
            "name": "LinkedQueryName",
            "value": "Dim_Geography_Store"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_QueryRelationships",
            "value": "{\"columnCount\":2,\"keyColumnNames\":[],\"queryRelationships\":[],\"columnIdentities\":[\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Geography_Store.{cw_outlet_key,0}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Geography_Store.{geography_name_id,7}\"],\"ColumnCount\":2,\"KeyColumnNames\":[],\"ColumnIdentities\":[\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Geography_Store.{cw_outlet_key,0}\",\"Server.Database\\\\/2/SQL/sydssql162d;dw_ch_deepdive/dbo/vw_Dim_Geography_Store.{geography_name_id,7}\"],\"RelationshipInfo\":[]}"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "AUX_LineChartMeasure_2",
        "isHidden": true,
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "LineMeasure",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[LineMeasure]",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "LineMeasure_Display",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[LineMeasure_Display]",
            "sortByColumn": "order",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "order",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[order]",
            "formatString": "0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "For_LineCHart",
            "dataType": "boolean",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[For_LineCHart]",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Boolean\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Boolean#####not a type"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "For_Geo",
            "dataType": "boolean",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[For_Geo]",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Boolean\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Boolean#####not a type"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "AUX_LineChartMeasure_2-64ee1258-5851-4bb1-8108-ae4de4f509b7",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "DATATABLE(  \"LineMeasure\", string,",
                "            \"LineMeasure_Display\", string,",
                "            \"order\", INTEGER,",
                "            \"For_LineCHart\", BOOLEAN,",
                "            \"For_Geo\", BOOLEAN,",
                "            {",
                "                    {\"MS\", \"Market Share\", 1, 1, 1},",
                "                    {\"EI\", \"Evolution Index\", 2, 1, 0},",
                "                    {\"P_Sales\", \"Product Sales\", 3, 1, 1},",
                "                    {\"M_Sales\", \"Market Sales\", 4, 1, 1},",
                "                    {\"P_Gth\", \"Product Growth Value\", 5, 1, 1},",
                "                    {\"M_Gth\", \"Market Growth Value\", 6, 1, 1},",
                "                    {\"P_Gth_%\", \"Product Growth %\", 7, 1, 0},",
                "                    {\"M_Gth_%\", \"Market Growth %\", 8, 1, 0},",
                "                    {\"Pop_Density\", \"Population Density\", 9, 0, 1},",
                "                    {\"Pop_PS\", \"AVG Population per Store\", 10, 0, 1},",
                "                    {\"P_PC\", \"Product Sales per Capita\", 11,0, 1},",
                "                    {\"M_PC\", \"Market Sales per Capita\", 12, 0, 1},",
                "                    {\"Dummy\", \"No Elevation\", 13, 0, 1}",
                "            })"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Filter_MeasureDisplay",
            "expression": [
              "",
              "var m_selected = SELECTEDVALUE('AUX_LineChartMeasure'[LineMeasure_Display], \"Product Sales\")",
              "",
              "return if(values(AUX_LineChartMeasure_2[LineMeasure_Display]) = m_selected, 0, 1)"
            ],
            "formatString": "0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "19bce48dc1b94072bc319eb25428c492"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "68a8aa44-c03f-4dd8-9c48-a52ba6477275",
        "fromTable": "Fact_SKU_State_Sales",
        "fromColumn": "banner_id",
        "toTable": "Dim_Banner_Type",
        "toColumn": "banner_id"
      },
      {
        "name": "d190993d-fa42-46ee-b96c-75ada5a84718",
        "fromTable": "Dim_Period",
        "fromColumn": "period_key",
        "toTable": "Dim_Period_Base",
        "toColumn": "period_key"
      },
      {
        "name": "2812abf9-f722-4497-b29e-722375179a6d",
        "fromTable": "Fact_Outlet_Category_Sales",
        "fromColumn": "period_key",
        "toTable": "Dim_Period_Base",
        "toColumn": "period_key"
      },
      {
        "name": "c187f7a1-d003-4070-8a8c-6adce2b1c0ba",
        "fromTable": "Fact_SKU_State_Sales",
        "fromColumn": "period_key",
        "toTable": "Dim_Period_Base",
        "toColumn": "period_key"
      },
      {
        "name": "eb1c0ca6-3ea8-4b4e-9a9b-327adec382eb",
        "fromTable": "Fact_SKU_State_Sales",
        "fromColumn": "cw_pack_key",
        "toTable": "Dim_Product_General",
        "toColumn": "cw_pack_key"
      },
      {
        "name": "233b11dd-d3a3-4314-9a63-392734906956",
        "fromTable": "Fact_Outlet_Category_Sales",
        "fromColumn": "cw_outlet_key",
        "toTable": "Dim_Outlet",
        "toColumn": "cw_outlet_key"
      },
      {
        "name": "10fda744-8b06-4045-add0-61135eaad653",
        "fromTable": "Fact_Outlet_Category_Sales",
        "fromColumn": "product_ownership_id",
        "toTable": "Dim_Product_Ownership",
        "toColumn": "product_ownership_id"
      },
      {
        "name": "608dcafb-a524-4def-a787-7e03f42d5480",
        "fromTable": "Fact_Outlet_Category_Sales",
        "fromColumn": "market_id",
        "toTable": "Dim_Market_Type",
        "toColumn": "market_id"
      },
      {
        "name": "8995559f-5ca8-476c-9d00-a45d831d24bd",
        "fromTable": "Fact_SKU_State_Sales",
        "fromColumn": "market_id",
        "toTable": "Dim_Market_Type",
        "toColumn": "market_id"
      },
      {
        "name": "1f766087-2440-42cc-b32b-7597316dcaa1",
        "fromTable": "Fact_Outlet_Category_Sales",
        "fromColumn": "measure_id",
        "toTable": "Dim_Measure_Type",
        "toColumn": "measure_id"
      },
      {
        "name": "e00064e1-94a5-4a59-a1a0-c7da64054a75",
        "fromTable": "Fact_SKU_State_Sales",
        "fromColumn": "measure_id",
        "toTable": "Dim_Measure_Type",
        "toColumn": "measure_id"
      },
      {
        "name": "28d55714-0dbc-492c-b690-069ffb65a66b",
        "fromTable": "Fact_SKU_State_Sales",
        "fromColumn": "state_key",
        "toTable": "Dim_State",
        "toColumn": "state_key"
      },
      {
        "name": "5d066e7d-1643-4674-96f4-391d43bf5a7f",
        "fromTable": "Dim_Outlet",
        "fromColumn": "state_key",
        "toTable": "Dim_State",
        "toColumn": "state_key"
      },
      {
        "name": "f3fc90ab-85f0-4c48-a649-79a5741d6f64",
        "fromTable": "Dim_Hierarchy_Name_Product",
        "fromColumn": "client_number",
        "toTable": "Client",
        "toColumn": "client_number"
      },
      {
        "name": "290a2359-b131-4bf7-b9aa-c518dcb321ec",
        "fromTable": "Dim_Hierarchy_Level_Name_Product",
        "fromColumn": "client_number",
        "toTable": "Client",
        "toColumn": "client_number"
      },
      {
        "name": "667cbd23-b4b0-4be8-a8eb-6ad2167f29a8",
        "fromTable": "Dim_Product_Client_Hierarchy",
        "fromColumn": "hierarchy_id",
        "toTable": "Dim_Hierarchy_Name_Product",
        "toColumn": "hierarchy_id"
      },
      {
        "name": "2ab2733b-efdf-4798-a650-08d44599b534",
        "fromTable": "Dim_Product_Client",
        "fromColumn": "cw_pack_key",
        "toTable": "Dim_Product_General",
        "toColumn": "cw_pack_key",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "629031f0-89a6-4a3b-a5ea-ee741e655d0f",
        "fromTable": "Dim_Product_Client",
        "fromColumn": "product_ownership_id",
        "toTable": "Dim_Product_Ownership",
        "toColumn": "product_ownership_id"
      },
      {
        "name": "5ac10a69-e8dd-4486-bbd1-a5a0d700147f",
        "fromTable": "Dim_Product_Client_Hierarchy",
        "fromColumn": "product_client_id",
        "toTable": "Dim_Product_Client",
        "toColumn": "product_client_id",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "6ba1746b-240e-45e5-a08d-f4c5af361eb0",
        "fromTable": "Dim_Product_Client",
        "fromColumn": "product_source_id",
        "toTable": "Dim_Product_Coding_Source",
        "toColumn": "product_source_id"
      },
      {
        "name": "d7b0d6d8-bccb-4c17-bf55-529a7ab0f022",
        "fromTable": "Fact_Outlet_Category_Sales",
        "fromColumn": "client_category_id",
        "toTable": "Dim_Category",
        "toColumn": "client_category_id"
      },
      {
        "name": "654bd910-6567-4845-89e1-1a040221441d",
        "fromTable": "Dim_Product_Client",
        "fromColumn": "client_category_id",
        "toTable": "Dim_Category",
        "toColumn": "client_category_id",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "53e24770-6b7d-45a0-b26a-cf53355a6d48",
        "fromTable": "Dim_Product_Client_Top_Analysis",
        "fromColumn": "product_client_id",
        "toTable": "Dim_Product_Client",
        "toColumn": "product_client_id",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "d41f21ad-2d6a-4962-9bed-064f4f1f572b",
        "fromTable": "Fact_SKU_Outlet_Sales",
        "fromColumn": "cw_pack_key",
        "toTable": "Dim_Product_General",
        "toColumn": "cw_pack_key"
      },
      {
        "name": "c0a62805-dc9a-4cbc-9ba0-69e22e1a1a87",
        "fromTable": "Fact_SKU_Outlet_Sales",
        "fromColumn": "measure_id",
        "toTable": "Dim_Measure_Type",
        "toColumn": "measure_id"
      },
      {
        "name": "3eb5320e-33da-4a07-abea-21c29c2366b6",
        "fromTable": "Fact_SKU_Outlet_Sales",
        "fromColumn": "market_id",
        "toTable": "Dim_Market_Type",
        "toColumn": "market_id"
      },
      {
        "name": "72ba7113-fded-4f6b-b834-614418cc3e2f",
        "fromTable": "Fact_SKU_Outlet_Sales",
        "fromColumn": "period_key",
        "toTable": "Dim_Period_Base",
        "toColumn": "period_key"
      },
      {
        "name": "ae3c846f-bd4f-48f7-97a9-b792d8a1b456",
        "fromTable": "Fact_SKU_Outlet_Sales",
        "fromColumn": "cw_outlet_key",
        "toTable": "Dim_Outlet",
        "toColumn": "cw_outlet_key"
      },
      {
        "name": "3a7b54ff-b5b8-44eb-ab3a-89fbf2740b83",
        "fromTable": "Dim_Period",
        "fromColumn": "Period_Name",
        "toTable": "Dim_Period_Alone",
        "toColumn": "period_name"
      },
      {
        "name": "4bc6ff03-2848-45f4-b58c-9b2ffac95ae6",
        "fromTable": "Dim_Geography_Store",
        "fromColumn": "cw_outlet_key",
        "toTable": "Dim_Outlet",
        "toColumn": "cw_outlet_key",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "f1892aae-1042-4356-a3ca-79b22c69d08b",
        "fromTable": "Dim_Geography_Store",
        "fromColumn": "geography_name_id",
        "toTable": "Dim_Geography",
        "toColumn": "geography_name_id",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "b93793a5-9183-4a23-862e-bcd9d6810bd8",
        "fromTable": "Dim_Geography",
        "fromColumn": "geography_id",
        "toTable": "Dim_Geography_Type",
        "toColumn": "geography_id"
      }
    ],
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "annotations": [
      {
        "name": "PBIDesktopVersion",
        "value": "2.84.661.0 (20.08)"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "TabularEditor_SerializeOptions",
        "value": "{\"IgnoreInferredObjects\":true,\"IgnoreInferredProperties\":true,\"IgnoreTimestamps\":true,\"SplitMultilineStrings\":true,\"PrefixFilenames\":false,\"LocalTranslations\":false,\"LocalPerspectives\":false,\"LocalRelationships\":false,\"Levels\":[\"Data Sources\",\"Perspectives\",\"Relationships\",\"Roles\",\"Tables\",\"Tables/Columns\",\"Tables/Hierarchies\",\"Tables/Measures\",\"Tables/Partitions\",\"Translations\"]}"
      }
    ]
  }
}